package org.muslim.app.feature.learn.domain

/**
 * A comprehensive Hajj & Umrah reference (PROJECT_PROMPT.md §10): definition,
 * rulings, types, mawaqit (miqat), the rites step by step — what to do, why,
 * and what to say — plus ihram prohibitions and the key supplications.
 *
 * Content note (§10): the texts follow mainstream, widely published fiqh
 * wording; madhhab differences are noted neutrally. The Arabic is primary and
 * an English rendering is given for every step. Numbers are Western digits.
 */
data class HajjStep(
    val title: String,
    val titleEn: String,
    val what: String,
    val whatEn: String,
    val evidence: String? = null,
    val evidenceEn: String? = null,
    val why: String? = null,
    val whyEn: String? = null,
    val say: String? = null,
    val sayEn: String? = null,
)

data class HajjTopic(
    val id: String,
    val title: String,
    val titleEn: String,
    val summary: String,
    val summaryEn: String,
    val steps: List<HajjStep>,
    val notes: String? = null,
    val notesEn: String? = null,
)

data class HajjCategory(
    val id: String,
    val title: String,
    val titleEn: String,
    val subtitle: String,
    val subtitleEn: String,
    val iconKey: String,
    val topics: List<HajjTopic>,
)

object HajjUmrahContent {

    val CATEGORIES: List<HajjCategory> = listOf(
        HajjCategory(
            id = "hajj_intro",
            title = "الحج: التعريف والحكم",
            titleEn = "Hajj: definition and rulings",
            subtitle = "تعريفه، حكمه، شروطه، أركانه وواجباته",
            subtitleEn = "Definition, obligation, conditions, pillars and duties",
            iconKey = "info",
            topics = listOf(
                HajjTopic(
                    id = "hajj_definition",
                    title = "تعريف الحج وحكمه وفضله",
                    titleEn = "Definition, obligation and virtue of Hajj",
                    summary = "الحج هو الركن الخامس من أركان الإسلام، فرضه الله مرة واحدة في العمر على المستطيع.",
                    summaryEn = "Hajj is the fifth pillar of Islam, made obligatory once in a lifetime upon those who are able.",
                    steps = listOf(
                        HajjStep(
                            "تعريف الحج",
                            "What Hajj is",
                            "الحج لغةً: القصد. وشرعًا: قصد بيت الله الحرام لأداء مناسك مخصوصة — الإحرام والطواف والسعي والوقوف بعرفة وغيرها — في زمان مخصوص (أشهر الحج) وبصفة مخصوصة.",
                            "Linguistically 'Hajj' means to intend or head towards. In Islamic law it means heading to the Sacred House of Allah to perform specific rites — ihram, tawaf, sa'i, the standing at Arafah and others — in a specific time (the months of Hajj) and a specific manner.",
                            "الحج ركن من أركان الإسلام الخمسة، فرضه الله على عباده: ﴿وَلِلَّهِ عَلَى النَّاسِ حِجُّ الْبَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا﴾ [آل عمران 97]، وقال ﷺ: «بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ... وَحَجِّ الْبَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا».",
                            "Hajj is one of the five pillars of Islam; Allah made it obligatory: 'And upon Allah is the pilgrimage to the House — for whoever is able to find a way' [Aal-Imran 97]. The Prophet ﷺ said: 'Islam is built upon five... and the pilgrimage to the House for whoever is able.'",
                        ),
                        HajjStep(
                            "فضله وأجره",
                            "Its virtue and reward",
                            "من حج فلم يرفث ولم يفسق رجع من ذنوبه كيوم ولدته أمه، والحج المبرور ليس له جزاء إلا الجنة.",
                            "Whoever performs Hajj without obscenity or sin returns from his sins like the day his mother bore him, and the accepted Hajj has no reward but Paradise.",
                            "قال ﷺ: «مَنْ حَجَّ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ»، وقال: «الْعُمْرَةُ إِلَى الْعُمْرَةِ كَفَّارَةٌ لِمَا بَيْنَهُمَا، وَالْحَجُّ الْمَبْرُورُ لَيْسَ لَهُ جَزَاءٌ إِلَّا الْجَنَّةُ».",
                            "The Prophet ﷺ said: 'Whoever performs Hajj and does not commit obscenity or sin returns like the day his mother bore him,' and: 'Umrah to Umrah is expiation for what is between them, and the accepted Hajj has no reward but Paradise.'",
                        ),
                        HajjStep(
                            "ما هو الحج المبرور",
                            "What the accepted Hajj is",
                            "الحج المبرور: هو الذي وقع خالصًا لله، موافقًا لهدي النبي ﷺ في مناسكه، مع كفّ اللسان والجوارح عن الرفث والفسوق والجدال.",
                            "The accepted Hajj is one performed sincerely for Allah, following the Prophet's ﷺ way in its rites, while keeping the tongue and limbs free from obscenity, sin and quarrelling.",
                            "قال تعالى: ﴿الْحَجُّ أَشْهُرٌ مَّعْلُومَاتٌ ۚ فَمَن فَرَضَ فِيهِنَّ الْحَجَّ فَلَا رَفَثَ وَلَا فُسُوقَ وَلَا جِدَالَ فِي الْحَجِّ﴾ [البقرة 197].",
                            "Allah says: 'Hajj is in months well-known. Whoever intends the Hajj therein — there is no obscenity, no sin and no quarrelling during Hajj' [Al-Baqarah 197].",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "hajj_conditions",
                    title = "شروط وجوب الحج",
                    titleEn = "Conditions of the obligation of Hajj",
                    summary = "لا يجب الحج إلا بشروط خمسة: الإسلام، والعقل، والبلوغ، والحرية، والاستطاعة.",
                    summaryEn = "Hajj is not obligatory except under five conditions: Islam, sanity, maturity, freedom and capability.",
                    steps = listOf(
                        HajjStep(
                            "الإسلام والعقل والبلوغ",
                            "Islam, sanity and maturity",
                            "يشترط أن يكون الحاج مسلمًا عاقلًا بالغًا؛ فغير المسلم لا يصح منه الحج، والمجنون غير مكلف، والصبي إذا حج صحّ حجه نفلًا ولا يجزئه عن حجة الإسلام.",
                            "The pilgrim must be a Muslim, sane and mature. Hajj from a non-Muslim is not valid, the insane are not accountable, and if a child performs Hajj it counts as voluntary and does not fulfil the obligatory Hajj.",
                            "قال ﷺ: «رُفِعَ الْقَلَمُ عَنْ ثَلَاثَةٍ: عَنِ النَّائِمِ حَتَّى يَسْتَيْقِظَ، وَعَنِ الصَّبِيِّ حَتَّى يَحْتَلِمَ، وَعَنِ الْمَجْنُونِ حَتَّى يَعْقِلَ».",
                            "The Prophet ﷺ said: 'The pen is lifted from three: the sleeper until he wakes, the child until he reaches puberty, and the insane until he regains his mind.'",
                        ),
                        HajjStep(
                            "الاستطاعة",
                            "Capability (istita'ah)",
                            "الاستطاعة: أن يملك الزاد والراحلة (أو ثمنهما) فاضلًا عن نفقة من يعول، مع أمن الطريق وصحة البدن، وتوفير نفقة من تلزمه نفقته حتى عودته.",
                            "Capability means having provision and means of transport (or their price) beyond the needs of dependents, a safe route, sound health, and leaving enough for those he supports until his return.",
                            "قال تعالى: ﴿مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا﴾ [آل عمران 97]، وقال ﷺ لمن سأل عن الحج: «أَعْجَلَهُ» أي فرضه فورًا — ومَن عجز عنه سقط عنه الوجوب.",
                            "Allah says: 'Whoever is able to find a way' [Aal-Imran 97]. Whoever is unable is excused from the obligation until he is able.",
                        ),
                        HajjStep(
                            "المرأة والمحرم",
                            "Women and the mahram",
                            "يشترط لوجوب الحج على المرأة — عند جمهور الفقهاء — وجود محرم (زوج أو قريب محرم) يرافقها، مع أمن الطريق.",
                            "In the view of the majority of scholars, a woman's Hajj requires a mahram (husband or unmarriageable relative) to accompany her and a safe route.",
                            "قال ﷺ: «لَا تُسَافِرِ الْمَرْأَةُ إِلَّا مَعَ ذِي مَحْرَمٍ» — وتنازع الفقهاء في وجوب المحرم للحج تحديدًا، وهو الاحتياط والأرجح عند الجمهور.",
                            "The Prophet ﷺ said: 'A woman must not travel except with a mahram.' Scholars differ on its application to Hajj, but the majority hold the mahram is required.",
                        ),
                    ),
                    notes = "من حج قبل بلوغه ثم بلغ: حجه نفل ولا يجزئه عن حجة الإسلام. ومن عجز عن الحج لكبر أو مرض لا يرجى برؤه: يُنيب من يحج عنه. الاستطاعة تشمل توفير نفقة من تجب نفقته مدة غيابه.",
                    notesEn = "If one performs Hajj before puberty it counts as voluntary, not the obligatory Hajj. Whoever cannot perform Hajj due to old age or incurable illness may appoint someone to perform it on his behalf. Capability includes leaving provision for dependents during the journey.",
                ),
                HajjTopic(
                    id = "hajj_pillars",
                    title = "أركان الحج وواجباته وسننه",
                    titleEn = "Pillars, duties and sunnahs of Hajj",
                    summary = "للحج أركان لا يصح إلا بها، وواجبات يلزم بتركها دم، وسنن يُندب فعلها.",
                    summaryEn = "Hajj has pillars without which it is invalid, duties whose omission requires a sacrificial animal, and recommended sunnahs.",
                    steps = listOf(
                        HajjStep(
                            "أركان الحج",
                            "The pillars of Hajj",
                            "أركان الحج عند جمهور الفقهاء أربعة: الإحرام، والوقوف بعرفة، وطواف الإفاضة، والسعي بين الصفا والمروة. من ترك ركنًا لم يصح حجه إلا به.",
                            "The pillars of Hajj in the view of the majority are four: ihram, standing at Arafah, the Tawaf al-Ifadah, and the sa'i between Safa and Marwah. Omitting a pillar invalidates the Hajj until it is made up.",
                            "قال ﷺ: «الْحَجُّ عَرَفَةُ، مَنْ جَاءَ لَيْلَةَ جَمْعٍ قَبْلَ طُلُوعِ الْفَجْرِ فَقَدْ أَدْرَكَ الْحَجَّ» — دليل عظم شأن الوقوف بعرفة.",
                            "The Prophet ﷺ said: 'Hajj is Arafah; whoever reaches it on the night of Jam' (Muzdalifah) before dawn has caught the Hajj' — showing the supreme place of the standing at Arafah.",
                            why = "الإحرام نية الدخول في النسك، والوقوف بعرفة ركن الحج الأعظم، والطواف تحية البيت، والسعي إحياء لسنة هاجر عليها السلام.",
                            whyEn = "Ihram is the intention to enter the rites, the standing at Arafah is the greatest pillar, tawaf is the greeting of the House, and sa'i revives the way of Hajar, peace be upon her.",
                        ),
                        HajjStep(
                            "واجبات الحج",
                            "The duties (wajibat) of Hajj",
                            "من الواجبات: الإحرام من الميقات، والوقوف بعرفة إلى غروب الشمس لمن وقف نهارًا، والمبيت بمزدلفة ليلة النحر، ورمي الجمار، والحلق أو التقصير، وطواف الوداع، والمبيت بمنى ليالي التشريق. من ترك واجبًا فعليه دم (هدي) عند الجمهور.",
                            "The duties include: entering ihram from the miqat, remaining at Arafah until sunset for those who stood by day, spending the night at Muzdalifah, stoning the jamarat, shaving or shortening the hair, the farewell tawaf, and spending the nights of Tashreeq at Mina. Omitting a duty requires a sacrificial animal in the view of the majority.",
                            "قال تعالى: ﴿وَاذْكُرُوا اللَّهَ فِي أَيَّامٍ مَّعْدُودَاتٍ﴾ [البقرة 203] — وهي أيام التشريق، وفيها رمي الجمار.",
                            "Allah says: 'And remember Allah during specified days' [Al-Baqarah 203] — the days of Tashreeq, in which the jamarat are stoned.",
                            why = "الواجبات جُعلت لإتمام المناسك على الهدي النبوي؛ وتركها لا يبطل الحج لكن يلزمه جبران بدم يُذبح في الحرم ويوزع على الفقراء.",
                            whyEn = "The duties complete the rites upon the Prophetic way; omitting one does not invalidate the Hajj but requires a compensatory sacrifice slaughtered in the Sanctuary and distributed to the poor.",
                        ),
                        HajjStep(
                            "سنن الحج",
                            "The sunnahs of Hajj",
                            "من السنن: الاغتسال والتطيب قبل الإحرام، وكثرة التلبية، واستلام الحجر الأسود وتقبيله عند الطواف، والاضطباع والرمل للرجل، والصعود على الصفا والمروة، والدعاء في المواقف.",
                            "The sunnahs include: bathing and perfuming before ihram, frequent talbiyah, touching and kissing the Black Stone during tawaf, idtiba' and raml for men, ascending Safa and Marwah, and supplicating at the stations.",
                            "قال ﷺ: «خُذُوا عَنِّي مَنَاسِكَكُمْ» — أي تعلموا مناسككم مني واقتدوا بي فيها.",
                            "The Prophet ﷺ said: 'Take your rites from me' — learn your rites from me and follow my example.",
                            why = "فعل السنن يزيد الحاج أجرًا ويحقّق الاقتداء بالنبي ﷺ في جميع حركاته وسكناته في النسك.",
                            whyEn = "Observing the sunnahs increases the pilgrim's reward and realises following the Prophet ﷺ in every movement and stillness of the rites.",
                        ),
                    ),
                    notes = "اختلفت المذاهب في عدّ الأركان والواجبات تفصيلًا: فالمالكية لا يعدّون السعي ركنًا بل واجبًا، والحنفية يعدّون الوقوف بعرفة وطواف الإفاضة ركنين فقط ويسمّون الباقي واجبات. هذا عرض محايد، والمأمول اتباع ما يطمئن إليه الحاج مع مراجعة أهل العلم.",
                    notesEn = "The schools differ in detail: the Malikis count sa'i as a duty rather than a pillar, and the Hanafis count only the standing at Arafah and Tawaf al-Ifadah as pillars. This is a neutral presentation; the pilgrim should follow what reassures him after consulting scholars.",
                ),
            ),
        ),

        HajjCategory(
            id = "hajj_types",
            title = "أنواع الحج",
            titleEn = "Types of Hajj",
            subtitle = "الإفراد والتمتع والقران: الفرق بينها وأفضلها",
            subtitleEn = "Ifrad, Tamattu' and Qiran: the differences and which is best",
            iconKey = "list",
            topics = listOf(
                HajjTopic(
                    id = "hajj_three_types",
                    title = "الإفراد والتمتع والقران",
                    titleEn = "Ifrad, Tamattu' and Qiran",
                    summary = "أنواع النسك ثلاثة: إفراد، وتمتع، وقران — وكلها جائزة، والتمتع أفضل لغير أهل مكة عند جمهور العلماء.",
                    summaryEn = "There are three ways to perform the rites: Ifrad, Tamattu' and Qiran — all are permissible, and Tamattu' is best for non-residents of Makkah in the view of the majority.",
                    steps = listOf(
                        HajjStep(
                            "الإفراد",
                            "Ifrad",
                            "يُنشئ الحاج نية الحج وحده (بلا عمرة)، فيبقى محرمًا من ميقاته حتى يتحلل بعد يوم النحر، وليس عليه هدي.",
                            "The pilgrim intends Hajj alone, without Umrah, remaining in ihram from his miqat until he exits after the Day of Sacrifice. No sacrificial animal is required of him.",
                            "قال تعالى: ﴿وَأَتِمُّوا الْحَجَّ وَالْعُمْرَةَ لِلَّهِ﴾ [البقرة 196] — والإفراد تحقيقٌ للإتمام دون تحلل بينهما.",
                            "Allah says: 'And complete the Hajj and the Umrah for Allah' [Al-Baqarah 196] — Ifrad fulfils completing both without a tahlul between them.",
                        ),
                        HajjStep(
                            "التمتع",
                            "Tamattu'",
                            "يُحرم بالعمرة أولًا في أشهر الحج، فيعتمر ويحلّ، ثم يُحرم بالحج في اليوم الثامن من ذي الحجة (يوم التروية) من مكانه بمكة. عليه هدي (شاة) أو صيام ثلاثة أيام في الحج وسبعة إذا رجع.",
                            "The pilgrim enters ihram for Umrah first in the months of Hajj, completes the Umrah and exits ihram, then enters ihram for Hajj on the 8th of Dhul-Hijjah (Yawm at-Tarwiyah) from his place in Makkah. He owes a sacrificial animal or fasting three days during Hajj and seven after returning.",
                            "قال ﷺ: «لَوِ اسْتَقْبَلْتُ مِنْ أَمْرِي مَا اسْتَدْبَرْتُ مَا أَهْدَيْتُ، وَلَوْلَا أَنَّ مَعِي الْهَدْيَ لَأَحْلَلْتُ» — فدلّ على أن التمتع هو الذي اختاره ﷺ لأمته.",
                            "The Prophet ﷺ said: 'Had I known what I now know, I would not have brought the sacrificial animal, and had I not brought it I would have exited ihram' — showing that Tamattu' is what he chose for his ummah.",
                            why = "التمتع يتضمن عمرة كاملة مع الحج، وفيه تحلل وراحة بين النسكين، وهو المندوب لغير أهل مكة عند الجمهور.",
                            whyEn = "Tamattu' combines a full Umrah with the Hajj, with a tahlul and ease between the two rites — the recommended way for non-residents of Makkah in the view of the majority.",
                        ),
                        HajjStep(
                            "القران",
                            "Qiran",
                            "يُحرم بالعمرة والحج معًا بنية واحدة (أو يحرم بالعمرة ثم يدخل الحج عليها قبل الطواف)، فيبقى محرمًا حتى يوم النحر، وعليه هدي كالمتمتع.",
                            "The pilgrim enters ihram for Umrah and Hajj together with a single intention (or enters Umrah then brings Hajj into it before tawaf), remaining in ihram until the Day of Sacrifice. He owes a sacrificial animal like the mutamatti'.",
                            "قال تعالى: ﴿فَمَن تَمَتَّعَ بِالْعُمْرَةِ إِلَى الْحَجِّ فَمَا اسْتَيْسَرَ مِنَ الْهَدْيِ﴾ [البقرة 196] — والقران داخل في معنى التمتع عند الجمهور.",
                            "Allah says: 'And whoever performs the Umrah within the Hajj [in this manner] — then an offering of whatever is easy for him' [Al-Baqarah 196] — Qiran is included in the meaning of Tamattu' in the view of the majority.",
                        ),
                    ),
                    notes = "أهل مكة يُفرِدون الحج ولا يتمتعون ولا يقرنون، لقوله تعالى: ﴿ذَٰلِكَ لِمَن لَّمْ يَكُنْ أَهْلُهُ حَاضِرِي الْمَسْجِدِ الْحَرَامِ﴾ [البقرة 196].",
                    notesEn = "Residents of Makkah perform Ifrad and do not do Tamattu' or Qiran, due to His saying: 'That is for whoever's family is not present at the Sacred Mosque' [Al-Baqarah 196].",
                ),
            ),
        ),

        HajjCategory(
            id = "hajj_miqat",
            title = "مواقيت الحج",
            titleEn = "The miqat (appointed places and times)",
            subtitle = "المواقيت الزمانية والمكانية للإحرام",
            subtitleEn = "The appointed times and places for entering ihram",
            iconKey = "place",
            topics = listOf(
                HajjTopic(
                    id = "time_miqat",
                    title = "المواقيت الزمانية",
                    titleEn = "The appointed times",
                    summary = "أشهر الحج: شوال، وذو القعدة، والعشر الأول من ذي الحجة — ولا يصح الإحرام بالحج قبلها.",
                    summaryEn = "The months of Hajj are Shawwal, Dhul-Qa'dah and the first ten days of Dhul-Hijjah; ihram for Hajj is not valid before them.",
                    steps = listOf(
                        HajjStep(
                            "أشهر الحج",
                            "The months of Hajj",
                            "قال تعالى: ﴿الْحَجُّ أَشْهُرٌ مَّعْلُومَاتٌ﴾ — وهي شوال وذو القعدة وعشر ذي الحجة عند جمهور المفسرين. من أحرم بالحج في غيرها لم يصح حجه بالحج.",
                            "Allah says: 'Hajj is in months well-known' — Shawwal, Dhul-Qa'dah and the (first) ten of Dhul-Hijjah in the view of most commentators. Ihram for Hajj outside them is not valid.",
                            "قال ابن عباس رضي الله عنهما: «مِنَ السُّنَّةِ أَلَّا يُحْرِمَ بِالْحَجِّ إِلَّا فِي أَشْهُرِ الْحَجِّ».",
                            "Ibn Abbas, may Allah be pleased with him, said: 'It is from the sunnah not to enter ihram for Hajj except in the months of Hajj.'",
                        ),
                        HajjStep(
                            "لماذا الأشهر المعلومة",
                            "Why these months",
                            "الحكمة أن الحج عبادة مؤقتة بزمان مخصوص، فجُعل لها موسم تعظيماً لها، وليعلم الناس وقتها فيقصدوها، وفيها وقعت مشاعر النسك كلها.",
                            "The wisdom is that Hajj is an act of worship tied to a specific time, given a season to honour it and so people know when to set out; all the rites fall within it.",
                            "قال تعالى: ﴿يَسْأَلُونَكَ عَنِ الْأَهِلَّةِ ۖ قُلْ هِيَ مَوَاقِيتُ لِلنَّاسِ وَالْحَجِّ﴾ [البقرة 189].",
                            "Allah says: 'They ask you about the new moons. Say: they are measurements of time for the people and for the Hajj' [Al-Baqarah 189].",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "place_miqat",
                    title = "المواقيت المكانية",
                    titleEn = "The appointed places",
                    summary = "خمسة مواقيت حدّها النبي ﷺ لأهل الآفاق، ومن جاوزها بلا إحرام فعليه دم.",
                    summaryEn = "Five miqat the Prophet ﷺ appointed for the peoples of the regions; passing them without ihram requires a sacrificial animal.",
                    steps = listOf(
                        HajjStep(
                            "المواقيت الخمسة",
                            "The five miqat",
                            "ذو الحليفة (أبيار علي): لأهل المدينة، الجحفة (رابغ): لأهل الشام ومصر والمغرب، قرن المنازل (السيل): لأهل نجد، يلملم: لأهل اليمن، ذات عرق: لأهل العراق وما وراءها.",
                            "Dhul-Hulayfah (Abyar Ali) for the people of Madinah; al-Juhfah (Rabigh) for the people of Syria, Egypt and the Maghrib; Qarn al-Manazil (as-Sayl) for the people of Najd; Yalamlam for the people of Yemen; Dhat 'Irq for the people of Iraq and beyond.",
                            "قال ﷺ: «مِيقَاتُ أَهْلِ الْمَدِينَةِ ذُو الْحُلَيْفَةِ، وَمِيقَاتُ أَهْلِ الشَّأْمِ الْجُحْفَةُ، وَمِيقَاتُ أَهْلِ نَجْدٍ قَرْنُ الْمَنَازِلِ، وَمِيقَاتُ أَهْلِ الْيَمَنِ يَلَمْلَمُ».",
                            "The Prophet ﷺ said: 'The miqat of the people of Madinah is Dhul-Hulayfah, of the people of Syria al-Juhfah, of the people of Najd Qarn al-Manazil, and of the people of Yemen Yalamlam.'",
                        ),
                        HajjStep(
                            "حكم مجاوزة الميقات",
                            "Passing the miqat without ihram",
                            "من جاوز الميقات يريد حجًا أو عمرة ولم يُحرم، فعليه أن يرجع إليه فيحرم منه إن أمكن؛ فإن أحرم من دونه فعليه دم (شاة تُذبح في الحرم) عند جمهور الفقهاء.",
                            "Whoever passes the miqat intending Hajj or Umrah without entering ihram must return to it and enter ihram from there if possible. If he enters ihram from before it, he owes a sacrificial animal in the view of the majority.",
                            "قال ﷺ: «مَنْ أَرَادَ أَنْ يُهِلَّ بِحَجٍّ أَوْ عُمْرَةٍ فَلَا يَجُوزَنَّ الْمِيقَاتَ إِلَّا وَهُوَ مُحْرِمٌ».",
                            "The Prophet ﷺ said: 'Whoever wishes to enter ihram for Hajj or Umrah must not pass the miqat except in ihram.'",
                            why = "المواقيت حدود شرعية جعلها الله ورسوله لتعظيم حرمات النسك، ولتكون موسمًا واحدًا يجتمع فيه الحجاج، مع التوسعة على من لم يرد النسك.",
                            whyEn = "The miqat are legal boundaries set by Allah and His Messenger to honour the rites, unite the pilgrims in one season, and spare those not intending the rites.",
                        ),
                        HajjStep(
                            "القادم بالطائرة",
                            "Coming by plane",
                            "من قدم جواً: يُحرم عند محاذاة الميقات (يسأل الطاقم أو يحدد بنفسه)، ويستحب أن يغتسل ويلبس ملابس الإحرام قبلها أو في الطائرة، ولا يجاوزها إلا محرمًا.",
                            "A traveller by plane enters ihram when his flight is level with the miqat (he may ask the crew or determine it himself). He should bathe and put on ihram garments before reaching it and not pass it except in ihram.",
                            "قال ﷺ: «مَنْ أَرَادَ أَنْ يُهِلَّ بِحَجٍّ أَوْ عُمْرَةٍ فَلَا يَجُوزَنَّ الْمِيقَاتَ إِلَّا وَهُوَ مُحْرِمٌ» — وهو يعم القادم برًا وجوًا.",
                            "The Prophet's ﷺ instruction covers every arrival, by land or by air.",
                            why = "المحاذاة الجوية للميقات حكمها حكم المرور عليه أرضًا؛ فالعلة عبور الحد الذي عيّنه الشرع، لا طريقة العبور.",
                            whyEn = "Flying over the miqat has the same ruling as crossing it on land, since the cause is crossing the boundary set by the law, not the means of crossing.",
                        ),
                    ),
                    notes = "من كان دون الميقات (كأهل جدة): ميقاته من حيث أنشأ النسك من بيته. والقادم بغير نية نسك لا يلزمه الإحرام حتى يعزم على الحج أو العمرة.",
                    notesEn = "Whoever resides before the miqat (such as the people of Jeddah) enters ihram from his own place. A traveller not intending the rites need not enter ihram until he decides to perform Hajj or Umrah.",
                ),
            ),
        ),

        HajjCategory(
            id = "hajj_rites",
            title = "مناسك الحج خطوة بخطوة",
            titleEn = "The rites of Hajj step by step",
            subtitle = "من الإحرام إلى طواف الوداع: ماذا تفعل ولماذا وماذا تقول",
            subtitleEn = "From ihram to the farewell tawaf: what to do, why, and what to say",
            iconKey = "calendar",
            topics = listOf(
                HajjTopic(
                    id = "ihram_step",
                    title = "الإحرام",
                    titleEn = "Ihram",
                    summary = "الإحرام نية الدخول في النسك، يسبقها الاغتسال والتنظف، ثم التلبية والدعاء.",
                    summaryEn = "Ihram is the intention to enter the rites, preceded by bathing and grooming, then the talbiyah and supplication.",
                    steps = listOf(
                        HajjStep(
                            "قبل الإحرام",
                            "Before ihram",
                            "يستحب الاغتسال، وتقليم الأظافر، وقص الشارب، ونتف الإبط وحلق العانة، والتنظف، والتطيب في البدن (لا في ملابس الإحرام)، والتجرد من المخيط للرجل (إزار ورداء أبيضان).",
                            "It is recommended to bathe, trim the nails, trim the moustache, remove underarm and pubic hair, groom, apply perfume to the body (not to the ihram garments), and for men to wear the two white unsewn garments (izar and rida').",
                            "كان ﷺ يغتسل لإحرامه ويأمر أصحابه بذلك، ويلبس إزارًا ورداء.",
                            "The Prophet ﷺ bathed for his ihram, commanded his companions to do the same, and wore an izar and rida'.",
                            why = "الاغتسال والتنظف من سنن الفطرة، ولباس الإحرام شعار المساواة بين العباد، يذكّر الحاج بيوم الحشر لا فرق فيه بين غني وفقير.",
                            whyEn = "Bathing and grooming follow the fitrah, and the ihram garments symbolise equality among the servants, reminding the pilgrim of the Day of Gathering where rich and poor are alike.",
                        ),
                        HajjStep(
                            "نية النسك",
                            "Intention of the rite",
                            "ينوي الحاج النسك الذي اختاره: «لبيك اللهم حجًّا» أو «لبيك اللهم عمرةً»، والنية محلها القلب.",
                            "The pilgrim intends the rite he chose: 'Labbayka Allahumma Hajjan' or 'Labbayka Allahumma 'Umratan'; the intention resides in the heart.",
                            "قال ﷺ: «إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى».",
                            "The Prophet ﷺ said: 'Actions are but by intentions, and every man gets what he intended.'",
                        ),
                        HajjStep(
                            "التلبية",
                            "The talbiyah",
                            "بعد الإحرام يلبي الحاج: «لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ» — يرفع بها صوته، ويرفع الرجال أصواتهم دون النساء.",
                            "After ihram the pilgrim recites: 'Labbayka Allahumma labbayk, labbayka la sharika laka labbayk, inna al-hamda wan-ni'mata laka wal-mulk, la sharika lak.' Men raise their voices; women recite quietly.",
                            "قال ﷺ: «أَتَانِي جِبْرِيلُ فَأَمَرَنِي أَنْ آمُرَ أَصْحَابِي أَنْ يَرْفَعُوا أَصْوَاتَهُمْ بِالتَّلْبِيَةِ».",
                            "The Prophet ﷺ said: 'Jibreel came to me and commanded me to order my companions to raise their voices with the talbiyah.'",
                            why = "التلبية إجابة لدعوة الله حين نادى إبراهيم ﷺ في الناس بالحج، وهي شعار الحاج تعلو بها أصواته في كل موقف.",
                            whyEn = "The talbiyah answers Allah's call when Ibrahim ﷺ called the people to Hajj; it is the pilgrim's slogan in every station.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "tarvia_day",
                    title = "يوم التروية (8 ذي الحجة)",
                    titleEn = "Yawm at-Tarwiyah (8th of Dhul-Hijjah)",
                    summary = "يتوجه الحاج إلى منى فيصلي بها الظهر والعصر والمغرب والعشاء والفجر، ويبيت ليلة عرفة فيها.",
                    summaryEn = "The pilgrim heads to Mina, prays Dhuhr, Asr, Maghrib, Isha and Fajr there, and spends the night before Arafah in Mina.",
                    steps = listOf(
                        HajjStep(
                            "الذهاب إلى منى",
                            "Going to Mina",
                            "من كان متمتعًا أحرم بالحج من مكانه بمكة (بالنية والتلبية)، ثم يتوجه إلى منى في اليوم الثامن، ويصلي بها الصلوات الخمس قصرًا (دون جمع) عند من يقصر.",
                            "The mutamatti' enters ihram for Hajj from his place in Makkah (with intention and talbiyah), then heads to Mina on the 8th day and prays the five prayers there, shortening them where shortening applies.",
                            "كان ﷺ يصلّي بمنى الظهر والعصر والمغرب والعشاء والفجر، ثم يغدو إلى عرفة.",
                            "The Prophet ﷺ prayed Dhuhr, Asr, Maghrib, Isha and Fajr in Mina, then set out to Arafah at dawn.",
                            why = "سمي يوم التروية لأنهم كانوا يتروون فيه الماء ويحملونه إلى عرفة؛ والمبيت بمنى تأسٍّ بالنبي ﷺ وتأهب للوقوف.",
                            whyEn = "It is called Yawm at-Tarwiyah because the pilgrims used to water (tarawwa) there and carry water to Arafah; staying in Mina follows the Prophet's ﷺ example and prepares for the standing.",
                        ),
                        HajjStep(
                            "ماذا تقول في منى",
                            "What to say in Mina",
                            "يلازم الحاج التلبية والذكر والدعاء، ويستعد نفسيًا لليوم الأعظم (عرفة): بكثرة الاستغفار والصلاة على النبي ﷺ.",
                            "The pilgrim keeps the talbiyah, dhikr and supplication, and prepares himself spiritually for the greatest day (Arafah) with abundant istighfar and salawat upon the Prophet ﷺ.",
                            "قال تعالى: ﴿فَإِذَا قَضَيْتُم مَّنَاسِكَكُمْ فَاذْكُرُوا اللَّهَ كَذِكْرِكُمْ آبَاءَكُمْ أَوْ أَشَدَّ ذِكْرًا﴾ [البقرة 200].",
                            "Allah says: 'And when you have completed your rites, remember Allah like your remembrance of your fathers or with much greater remembrance' [Al-Baqarah 200].",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "arafah_day",
                    title = "الوقوف بعرفة (9 ذي الحجة)",
                    titleEn = "The standing at Arafah (9th of Dhul-Hijjah)",
                    summary = "ركن الحج الأعظم: يوم الدعاء والذكر من الزوال إلى الغروب، وفيه يُغفر الذنب ويعتق من النار.",
                    summaryEn = "The greatest pillar of Hajj: a day of supplication and remembrance from noon to sunset, in which sins are forgiven and people are freed from the Fire.",
                    steps = listOf(
                        HajjStep(
                            "الوصول والجمع",
                            "Arrival and joining prayers",
                            "بعد شروق شمس اليوم التاسع يتوجه الحاج من منى إلى عرفة، ويصلي الظهر والعصر جمع تقديم قصرًا بأذان واحد وإقامتين (عند الجمهور)، ثم يتفرغ للدعاء والذكر.",
                            "After sunrise on the 9th the pilgrim goes from Mina to Arafah, prays Dhuhr and Asr combined and shortened (in the view of the majority), then devotes himself to supplication and remembrance.",
                            "كان ﷺ يصلي بعرفة الظهر والعصر جمعًا ثم يقبل على الدعاء حتى غروب الشمس.",
                            "The Prophet ﷺ prayed Dhuhr and Asr combined at Arafah, then turned to supplication until sunset.",
                        ),
                        HajjStep(
                            "الوقوف والدعاء",
                            "The standing and supplication",
                            "يقف الحاج في أي موضع من عرفة (سوى بطن عرنة) مستقبلًا القبلة، رافعًا يديه، مكثرًا من الذكر والدعاء والتلبية والاستغفار حتى غروب الشمس، وهذا هو الركن الأعظم.",
                            "The pilgrim stands anywhere in Arafah (except the valley of 'Uranah) facing the qiblah, raising his hands, repeating dhikr, supplication, talbiyah and istighfar until sunset — this is the greatest pillar.",
                            "قال ﷺ: «خَيْرُ الدُّعَاءِ دُعَاءُ يَوْمِ عَرَفَةَ، وَخَيْرُ مَا قُلْتُ أَنَا وَالنَّبِيُّونَ مِنْ قَبْلِي: لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ».",
                            "The Prophet ﷺ said: 'The best of supplication is the supplication of the Day of Arafah, and the best of what I and the prophets before me said is: La ilaha illa Allah wahdahu la sharika lah, lahul-mulk wa lahul-hamd wa huwa 'ala kulli shay'in qadir.'",
                            say = "«لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ» — ثم يدعو بما شاء من خير الدنيا والآخرة.",
                            sayEn = "'There is no god but Allah alone, with no partner; His is the dominion and His is the praise, and He is over all things competent' — then supplicate for whatever good of this world and the next you wish.",
                            why = "عرفة هو الموقف الذي قال فيه ﷺ: «الْحَجُّ عَرَفَةُ»، وفيه ينزل الله مغفرته، قال ﷺ: «مَا مِنْ يَوْمٍ أَكْثَرَ مِنْ أَنْ يُعْتِقَ اللَّهُ فِيهِ عَبْدًا مِنَ النَّارِ مِنْ يَوْمِ عَرَفَةَ».",
                            whyEn = "Arafah is the station of which the Prophet ﷺ said: 'Hajj is Arafah.' No day has more people freed from the Fire by Allah than the Day of Arafah.",
                        ),
                        HajjStep(
                            "الدفع بعد الغروب",
                            "Departure after sunset",
                            "إذا غربت الشمس دفع الحاج من عرفة إلى مزدلفة بسكينة ووقار، ملبيًا ذاكرًا داعيًا، ولا يصل المغرب حتى يأتي مزدلفة.",
                            "After sunset the pilgrim departs from Arafah to Muzdalifah with tranquility and dignity, reciting talbiyah, dhikr and supplication, not praying Maghrib until he reaches Muzdalifah.",
                            "قال تعالى: ﴿ثُمَّ أَفِيضُوا مِنْ حَيْثُ أَفَاضَ النَّاسُ وَاسْتَغْفِرُوا اللَّهَ ۚ إِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ﴾ [البقرة 199].",
                            "Allah says: 'Then depart from where the people depart and ask Allah for forgiveness. Indeed, Allah is Forgiving and Merciful' [Al-Baqarah 199].",
                        ),
                    ),
                    notes = "من وقف بعرفة نهارًا ودفع قبل الغروب: فعليه دم عند الجمهور لتركه المبيت إلى الليل. ومن فاته الوقوف بعرفة حتى طلع فجر يوم النحر فقد فاته الحج.",
                    notesEn = "Whoever stands at Arafah by day and departs before sunset owes a sacrificial animal in the view of the majority. Whoever misses the standing at Arafah until dawn of the Day of Sacrifice has missed the Hajj.",
                ),
                HajjTopic(
                    id = "muzdalifah",
                    title = "المبيت بمزدلفة",
                    titleEn = "Spending the night at Muzdalifah",
                    summary = "يجمع المغرب والعشاء، ويبيت حتى الفجر، ويجمع حصى الجمار، ثم يدفع إلى منى قبل الشروق.",
                    summaryEn = "Combine Maghrib and Isha, stay until dawn, collect the pebbles for stoning, then depart to Mina before sunrise.",
                    steps = listOf(
                        HajjStep(
                            "الجمع والمبيت",
                            "Combining and staying",
                            "يصل الحاج مزدلفة فيصلي المغرب والعشاء جمعًا (قصرًا عند من يقصر)، ثم يبيت بها ليلة النحر، ويصلي الفجر، ويستمر في الذكر والدعاء حتى الإسفار.",
                            "The pilgrim reaches Muzdalifah, prays Maghrib and Isha combined, stays the night of the Day of Sacrifice, prays Fajr, and continues in dhikr and supplication until dawn light spreads.",
                            "كان ﷺ يصلي بمزدلفة المغرب والعشاء ويبيت حتى الصبح ثم يقف عند المشعر الحرام يدعو حتى أسفر جدًا.",
                            "The Prophet ﷺ prayed Maghrib and Isha at Muzdalifah, stayed until dawn, then stood at al-Mash'ar al-Haram supplicating until the light was bright.",
                        ),
                        HajjStep(
                            "التقاط الحصى",
                            "Collecting the pebbles",
                            "يلتقط الحاج سبع حصيات (لجمرة العقبة) وأربعًا وعشرين (لأيام التشريق) إن شاء من مزدلفة أو من أي مكان، والحصى صغير بحجم حبة الحمص تقريبًا.",
                            "The pilgrim collects seven pebbles (for Jamrat al-Aqabah) and twenty-four more (for the days of Tashreeq) from Muzdalifah or anywhere; each pebble is about the size of a chickpea.",
                            "قال ﷺ: «ارْمُوا بِمِثْلِ حَصَى الْخَذْفِ» — أي بحجم حصى القذف الصغيرة.",
                            "The Prophet ﷺ said: 'Stone with pebbles the size of the pebbles of al-khadhf' — small pebbles.",
                            why = "المبيت بمزدلفة واجب عند الجمهور، وفيه يجتمع الحجاج في موقف واحد بعد عرفة، ويبيتون تحت سماء الله ذاكرين مستغفرين.",
                            whyEn = "Staying at Muzdalifah is a duty in the view of the majority; the pilgrims gather in one station after Arafah, spending the night under the sky in remembrance and seeking forgiveness.",
                        ),
                        HajjStep(
                            "الوقوف عند المشعر الحرام",
                            "Standing at al-Mash'ar al-Haram",
                            "يقف الحاج بعد الفجر عند المشعر الحرام (جبل قزح بمزدلفة) مستقبلًا القبلة، يهلل ويكبر ويدعو حتى يسفر جدًا، ثم يدفع إلى منى قبل طلوع الشمس.",
                            "After Fajr the pilgrim stands at al-Mash'ar al-Haram (Mount Quzah in Muzdalifah) facing the qiblah, saying la ilaha illa Allah, takbir and supplication until the light is bright, then departs to Mina before sunrise.",
                            "قال تعالى: ﴿فَإِذَا أَفَضْتُم مِّنْ عَرَفَاتٍ فَاذْكُرُوا اللَّهَ عِندَ الْمَشْعَرِ الْحَرَامِ ۖ وَاذْكُرُوهُ كَمَا هَدَاكُمْ﴾ [البقرة 198].",
                            "Allah says: 'And when you depart from Arafat, remember Allah at the Sacred Monument, and remember Him as He has guided you' [Al-Baqarah 198].",
                            say = "يدعو عند المشعر الحرام بما شاء، ويكثر من: «لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ».",
                            sayEn = "Supplicate at the Sacred Monument as you wish, repeating: 'There is no god but Allah alone, with no partner; His is the dominion and His is the praise, and He is over all things competent.'",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "yawm_nahr",
                    title = "يوم النحر (10 ذي الحجة)",
                    titleEn = "Yawm an-Nahr (10th of Dhul-Hijjah)",
                    summary = "يوم أعماله كثيرة: رمي جمرة العقبة، ثم النحر، ثم الحلق أو التقصير، ثم طواف الإفاضة والسعي.",
                    summaryEn = "A day of many deeds: stoning Jamrat al-Aqabah, then the sacrifice, then shaving or shortening the hair, then Tawaf al-Ifadah and the sa'i.",
                    steps = listOf(
                        HajjStep(
                            "رمي جمرة العقبة",
                            "Stoning Jamrat al-Aqabah",
                            "يتوجه الحاج من مزدلفة إلى منى، فيرمي جمرة العقبة (الكبرى) بسبع حصيات متعاقبات، ويكبر مع كل حصاة: «الله أكبر».",
                            "The pilgrim goes from Muzdalifah to Mina and stones Jamrat al-Aqabah with seven pebbles, one after another, saying 'Allahu akbar' with each.",
                            "كان ﷺ يرمي جمرة العقبة ضحى يوم النحر، ويكبر مع كل حصاة.",
                            "The Prophet ﷺ stoned Jamrat al-Aqabah in the forenoon of the Day of Sacrifice, saying takbir with each pebble.",
                            say = "«الله أكبر» مع كل حصاة، وبعد الرمي لا دعاء عند جمرة العقبة (بخلاف الصغرى والوسطى).",
                            sayEn = "Say 'Allahu akbar' with each pebble; there is no supplication after stoning Jamrat al-Aqabah (unlike the first and middle jamarat).",
                            why = "الرمي تعظيم لشعائر الله وإظهار للطاعة، وفيه إحياء لذكر الله؛ وهو من واجبات الحج عند الجمهور.",
                            whyEn = "Stoning honours the rites of Allah and manifests obedience, reviving the remembrance of Allah; it is among the duties of Hajj in the view of the majority.",
                        ),
                        HajjStep(
                            "الهدي (النحر)",
                            "The sacrificial offering (hady)",
                            "إن كان على الحاج هدي (متمتعًا أو قارنًا) ذبحه يوم النحر أو أيام التشريق، وأكل منه وأهدى وتصدق، ولا يأكل من هدي الواجب (كفارة) شيئًا عند الجمهور.",
                            "If a sacrificial animal is due (for Tamattu' or Qiran), the pilgrim slaughters it on the Day of Sacrifice or the days of Tashreeq, eats from it, gives gifts and charity, but does not eat from a compensatory (fidyah) sacrifice in the view of the majority.",
                            "قال تعالى: ﴿فَمَن تَمَتَّعَ بِالْعُمْرَةِ إِلَى الْحَجِّ فَمَا اسْتَيْسَرَ مِنَ الْهَدْيِ﴾ [البقرة 196].",
                            "Allah says: 'Whoever performs the Umrah within the Hajj — then an offering of whatever is easy for him' [Al-Baqarah 196].",
                            why = "الهدي شكر لله على تيسير النسك، وإطعام للفقراء في موسم الخير، وتأسٍّ بنبي الله إبراهيم ﷺ.",
                            whyEn = "The hady is gratitude to Allah for making the rites easy, feeding the poor in the season of goodness, and following Prophet Ibrahim ﷺ.",
                        ),
                        HajjStep(
                            "الحلق أو التقصير",
                            "Shaving or shortening the hair",
                            "يحلق الرجل رأسه أو يقصر (والحلق أفضل)، وتقصر المرأة قدر أنملة من أطراف شعرها. بهذا يحصل التحلل الأول: يحلّ له كل شيء إلا النساء.",
                            "The man shaves his head or shortens his hair (shaving is better); the woman shortens a fingertip's length from her hair ends. This achieves the first tahlul: everything becomes lawful except sexual relations with one's spouse.",
                            "قال ﷺ: «اللَّهُمَّ ارْحَمِ الْمُحَلِّقِينَ» قالوا: والمقصرين يا رسول الله؟ قال: «اللَّهُمَّ ارْحَمِ الْمُحَلِّقِينَ» قالوا: والمقصرين؟ قال: «وَالْمُقَصِّرِينَ».",
                            "The Prophet ﷺ said: 'O Allah, have mercy on those who shave.' They said: 'And those who shorten, O Messenger of Allah?' He said: 'And those who shorten.'",
                            why = "الحلق أو التقصير علامة الخروج من الإحرام والتواضع لله، وفيه إظهار للعبودية ورفع للحرج.",
                            whyEn = "Shaving or shortening marks leaving ihram in humility before Allah, manifesting servitude and lifting restriction.",
                        ),
                        HajjStep(
                            "طواف الإفاضة والسعي",
                            "Tawaf al-Ifadah and the sa'i",
                            "يطوف الحاج طواف الإفاضة (ركن) سبعة أشواط، ثم يصلي ركعتين، ثم يسعى بين الصفا والمروة إن كان لم يسع بعد طواف القدوم (والمتمتع يسعى سعيًا واحدًا يكفيه).",
                            "The pilgrim performs Tawaf al-Ifadah (a pillar) of seven circuits, prays two rak'ahs, then performs the sa'i between Safa and Marwah if he has not already done it (the mutamatti' does one sa'i which suffices).",
                            "قال تعالى: ﴿ثُمَّ لْيَقْضُوا تَفَثَهُمْ وَلْيُوفُوا نُذُورَهُمْ وَلْيَطَّوَّفُوا بِالْبَيْتِ الْعَتِيقِ﴾ [الحج 29].",
                            "Allah says: 'Then let them end their untidiness and fulfil their vows and perform tawaf around the Ancient House' [Al-Hajj 29].",
                            say = "يكثر الحاج في الطواف من الذكر والدعاء، ويقول بين الركن اليماني والحجر الأسود: «رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ».",
                            sayEn = "During tawaf, say between the Yemeni Corner and the Black Stone: 'Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire.'",
                            why = "بعد الطواف والسعي يتحقق التحلل الثاني فيحل له كل شيء، ويتم بذلك أكثر أعمال يوم النحر: الرمي ثم النحر ثم الحلق ثم الطواف ثم السعي.",
                            whyEn = "After tawaf and sa'i the second tahlul is achieved and everything becomes lawful, completing the deeds of the Day of Sacrifice: stoning, sacrifice, shaving, tawaf and sa'i.",
                        ),
                        HajjStep(
                            "الترتيب الصحيح",
                            "The correct order",
                            "السنة ترتيب أعمال يوم النحر: الرمي، ثم النحر، ثم الحلق، ثم الطواف، ثم السعي. ومن قدم شيئًا على شيء ناسيًا أو جاهلًا فلا حرج عليه، ولا دم عليه عند الجمهور.",
                            "The sunnah orders the deeds: stoning, then sacrifice, then shaving, then tawaf, then sa'i. Whoever advances one before another out of forgetfulness or ignorance is not at fault and owes nothing in the view of the majority.",
                            "سُئل النبي ﷺ عن التقديم والتأخير يوم النحر فقال: «لَا حَرَجَ» في كل ذلك.",
                            "When the Prophet ﷺ was asked about advancing and delaying on the Day of Sacrifice, he said: 'There is no harm' in all of it.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "tashreeq_days",
                    title = "أيام التشريق (11–13 ذي الحجة)",
                    titleEn = "The days of Tashreeq (11th–13th)",
                    summary = "أيام الرمي: يرمي الحاج الجمرات الثلاث بعد الزوال، ويبيت بمنى، ويدعو بعد الرمي.",
                    summaryEn = "The days of stoning: the pilgrim stones the three jamarat after noon, stays at Mina, and supplicates after stoning.",
                    steps = listOf(
                        HajjStep(
                            "رمي الجمرات الثلاث",
                            "Stoning the three jamarat",
                            "بعد الزوال يرمي الحاج الجمرات الثلاث مرتبًا: الصغرى (الأولى) ثم الوسطى ثم الكبرى (العقبة)، كل واحدة بسبع حصيات، ويكبر مع كل حصاة.",
                            "After noon the pilgrim stones the three jamarat in order: the small (first), then the middle, then the great (Aqabah), each with seven pebbles, saying takbir with each.",
                            "كان ﷺ يرمي الجمرات الثلاث بعد الزوال أيام التشريق، ويكبر مع كل حصاة.",
                            "The Prophet ﷺ stoned the three jamarat after noon on the days of Tashreeq, saying takbir with each pebble.",
                        ),
                        HajjStep(
                            "الدعاء بعد الرمي",
                            "Supplication after stoning",
                            "بعد رمي الصغرى والوسطى يتقدم الحاج ويستقبل القبلة ويدعو طويلًا، وأما جمرة العقبة فلا دعاء بعدها.",
                            "After stoning the first and middle jamarat the pilgrim moves forward, faces the qiblah and supplicates at length; there is no supplication after Jamrat al-Aqabah.",
                            "كان ﷺ يدعو بعد رمي الصغرى والوسطى مستقبلًا القبلة رافعًا يديه.",
                            "The Prophet ﷺ supplicated after the first and middle jamarat, facing the qiblah with raised hands.",
                            say = "يدعو بعد الصغرى والوسطى بما شاء، ويلازم التلبية والتكبير والذكر في أيام التشريق كلها.",
                            sayEn = "Supplicate after the first and middle jamarat as you wish, and keep the talbiyah, takbir and dhikr throughout the days of Tashreeq.",
                            why = "الرمي في أيام التشريق من واجبات الحج، وإحياء لذكر الله: ﴿وَاذْكُرُوا اللَّهَ فِي أَيَّامٍ مَّعْدُودَاتٍ﴾، والدعاء بعد الرمي موقف عظيم تُرجى فيه الإجابة.",
                            whyEn = "Stoning on the days of Tashreeq is a duty of Hajj and a revival of remembrance: 'And remember Allah during specified days'; supplication after stoning is a great station in which answers are hoped for.",
                        ),
                        HajjStep(
                            "المبيت بمنى والتعجل",
                            "Staying at Mina and hastening",
                            "يبيت الحاج بمنى ليالي التشريق (11 و12، والثالثة لمن تأخر)، ثم يتعجل في يومين: يرمي يومين ثم ينفر (يخرج) قبل غروب ثاني أيام الرمي، أو يتأخر فيرمي اليوم الثالث ثم ينفر.",
                            "The pilgrim stays at Mina on the nights of Tashreeq (11th and 12th, plus the 13th for those who delay), then may hasten in two days: stone for two days and depart before sunset, or delay and stone the third day then depart.",
                            "قال تعالى: ﴿فَمَن تَعَجَّلَ فِي يَوْمَيْنِ فَلَا إِثْمَ عَلَيْهِ وَمَن تَأَخَّرَ فَلَا إِثْمَ عَلَيْهِ ۚ لِمَنِ اتَّقَىٰ﴾ [البقرة 203].",
                            "Allah says: 'Whoever hastens in two days — there is no sin upon him; and whoever delays — there is no sin upon him, for one who fears Allah' [Al-Baqarah 203].",
                        ),
                    ),
                    notes = "إذا نفر الحاج قبل غروب اليوم الثاني عشر فقد تعجل، وإن غربت الشمس عليه في منى لزمه المبيت والرمي في اليوم الثالث. وقت الرمي من الزوال إلى غروب الشمس، ومن كان عنده عذر جاز له التأخير.",
                    notesEn = "If the pilgrim departs before sunset on the 12th he has hastened; if sunset catches him in Mina he must stay and stone on the 13th. The time of stoning is from noon to sunset; the excused may delay.",
                ),
                HajjTopic(
                    id = "tawaf_alwada",
                    title = "طواف الوداع",
                    titleEn = "The farewell tawaf",
                    summary = "آخر عهد الحاج بالبيت: يطوف سبعة أشواط ثم ينصرف، وهو واجب عند الجمهور.",
                    summaryEn = "The pilgrim's last sight of the House: seven circuits, then departure. It is a duty in the view of the majority.",
                    steps = listOf(
                        HajjStep(
                            "طواف الوداع",
                            "The farewell tawaf",
                            "عند إرادة مغادرة مكة يطوف الحاج بالبيت سبعة أشواط (طواف الوداع)، ثم يصلي ركعتين، ويدعو، وينصرف دون سعي ولا رمي.",
                            "When intending to leave Makkah the pilgrim performs seven circuits around the House (the farewell tawaf), prays two rak'ahs, supplicates, and departs — without sa'i or stoning.",
                            "قال ﷺ: «لَا يَنْفِرَنَّ أَحَدٌ حَتَّى يَكُونَ آخِرُ عَهْدِهِ بِالْبَيْتِ».",
                            "The Prophet ﷺ said: 'Let none of you depart until his last sight is the House.'",
                            why = "طواف الوداع توديع للبيت وإظهار للشوق والتعظيم، وآخر نسك من مناسك الحج، وبه يختم الحاج نسكه على خير.",
                            whyEn = "The farewell tawaf bids the House farewell, showing longing and reverence, and closes the pilgrim's rites upon good.",
                        ),
                        HajjStep(
                            "من لا يلزمها الوداع",
                            "Who is excused from it",
                            "الحائض والنفساء لا يلزمهما طواف الوداع عند الجمهور (لقول عائشة رضي الله عنها للنبي ﷺ عن صفية: «قد حاضت» فقال: «أَحَابِسَتُنَا هِيَ؟» فقيل إنها قد أفاضت، فقال: «فَلَا إِذَنْ»)، ومن أقام بمكة بعد نسكه فلا وداع عليه حتى يغادر.",
                            "The menstruating woman and the woman in post-natal bleeding are excused from the farewell tawaf in the view of the majority. Whoever remains in Makkah after his rites owes the farewell tawaf only when he departs.",
                            "عن ابن عباس رضي الله عنهما قال: «أُمِرَ النَّاسُ أَنْ يَكُونَ آخِرُ عَهْدِهِمْ بِالْبَيْتِ، إِلَّا أَنَّهُ خُفِّفَ عَنِ الْمَرْأَةِ الْحَائِضِ».",
                            "Ibn Abbas reported: 'The people were commanded that their last sight be the House, except that it was lightened for the menstruating woman.'",
                        ),
                    ),
                ),
            ),
        ),

        HajjCategory(
            id = "umrah_rites",
            title = "العمرة خطوة بخطوة",
            titleEn = "Umrah step by step",
            subtitle = "الإحرام، الطواف، السعي، الحلق أو التقصير",
            subtitleEn = "Ihram, tawaf, sa'i, and shaving or shortening",
            iconKey = "check",
            topics = listOf(
                HajjTopic(
                    id = "umrah_ihram",
                    title = "الإحرام بالعمرة",
                    titleEn = "Entering ihram for Umrah",
                    summary = "كالإحرام بالحج: اغتسال وتنظف، ثم نية العمرة والتلبية من الميقات.",
                    summaryEn = "Like ihram for Hajj: bathing and grooming, then intending Umrah and reciting the talbiyah from the miqat.",
                    steps = listOf(
                        HajjStep(
                            "الاستعداد والإحرام",
                            "Preparation and ihram",
                            "يغتسل المعتمر ويتنظف ويتطيب في بدنه، ويلبس الرجل إزارًا ورداءً، ثم ينوي العمرة من الميقات ويقول: «لبيك اللهم عمرة»، ثم يلبي.",
                            "The pilgrim bathes, grooms and perfumes his body; the man wears izar and rida', intends Umrah from the miqat saying 'Labbayka Allahumma 'umratan', then recites the talbiyah.",
                            "قال ﷺ: «الْعُمْرَةُ إِلَى الْعُمْرَةِ كَفَّارَةٌ لِمَا بَيْنَهُمَا» — وبيان فضلها وأنها تُكرر.",
                            "The Prophet ﷺ said: 'Umrah to Umrah is expiation for what is between them' — showing its virtue and that it may be repeated.",
                            say = "«لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ».",
                            sayEn = "'Labbayka Allahumma labbayk, labbayka la sharika laka labbayk, inna al-hamda wan-ni'mata laka wal-mulk, la sharika lak.'",
                        ),
                        HajjStep(
                            "حكم العمرة",
                            "The ruling on Umrah",
                            "العمرة واجبة مرة في العمر عند الجمهور (الحنفية والحنابلة وقول للشافعية)، ومستحبة عند المالكية والراجح عند الشافعية — وفعلها في رمضان كحجة مع النبي ﷺ.",
                            "Umrah is obligatory once in a lifetime in the view of the majority (Hanafis, Hanbalis and one Shafi'i view) and recommended in the view of the Malikis and the stronger Shafi'i view. Umrah in Ramadan equals Hajj with the Prophet ﷺ.",
                            "قال ﷺ: «عُمْرَةٌ فِي رَمَضَانَ تَعْدِلُ حَجَّةً».",
                            "The Prophet ﷺ said: 'An Umrah in Ramadan equals a Hajj.'",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "umrah_tawaf",
                    title = "الطواف",
                    titleEn = "The tawaf",
                    summary = "سبعة أشواط حول الكعبة: يبدأ من الحجر الأسود، ويكثر من الذكر والدعاء.",
                    summaryEn = "Seven circuits around the Kaaba, starting from the Black Stone, with abundant dhikr and supplication.",
                    steps = listOf(
                        HajjStep(
                            "أشواط الطواف",
                            "The circuits of tawaf",
                            "عند الوصول إلى المسجد الحرام يطوف المعتمر سبعة أشواط حول الكعبة، يبدأ كل شوط باستلام الحجر الأسود (تقبيلًا أو لمسًا أو إشارة) ويكبر، والرجل يضطبع (يكشف كتفه الأيمن) ويرمل (يسرع) في الأشواط الثلاثة الأولى.",
                            "Upon reaching the Sacred Mosque the pilgrim performs seven circuits around the Kaaba, beginning each with the Black Stone (kissing, touching, or gesturing) and takbir. The man performs idtiba' (baring the right shoulder) and raml (quickening) in the first three circuits.",
                            "قال تعالى: ﴿وَلْيَطَّوَّفُوا بِالْبَيْتِ الْعَتِيقِ﴾ [الحج 29]، وكان ﷺ يستلم الحجر ويكبر.",
                            "Allah says: 'And perform tawaf around the Ancient House' [Al-Hajj 29]; the Prophet ﷺ touched the Stone and said takbir.",
                            say = "«بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ» عند الحجر، و«رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ» بين الركن اليماني والحجر الأسود، ثم يدعو بما شاء.",
                            sayEn = "Say 'Bismillah, Allahu akbar' at the Stone, and between the Yemeni Corner and the Black Stone: 'Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire,' then supplicate as you wish.",
                            why = "الطواف ركن من أركان العمرة، وفيه تعظيم البيت وإظهار للعبودية، والرمل والاضطباع إظهار للقوة والجَلَد اقتداءً بفعل النبي ﷺ.",
                            whyEn = "Tawaf is a pillar of Umrah honouring the House and manifesting servitude; raml and idtiba' display strength, following the Prophet's ﷺ example.",
                        ),
                        HajjStep(
                            "صلاة الركعتين",
                            "The two rak'ahs after tawaf",
                            "بعد إتمام الأشواط السبعة يصلي المعتمر ركعتين خلف مقام إبراهيم (إن تيسر، وإلا ففي أي موضع من المسجد)، يقرأ فيهما بالكافرون والإخلاص.",
                            "After the seven circuits the pilgrim prays two rak'ahs behind the Station of Ibrahim (if possible, otherwise anywhere in the mosque), reciting al-Kafirun and al-Ikhlas.",
                            "قال تعالى: ﴿وَاتَّخِذُوا مِن مَّقَامِ إِبْرَاهِيمَ مُصَلًّى﴾ [البقرة 125].",
                            "Allah says: 'And take from the Station of Ibrahim a place of prayer' [Al-Baqarah 125].",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "umrah_sai",
                    title = "السعي بين الصفا والمروة",
                    titleEn = "The sa'i between Safa and Marwah",
                    summary = "سبعة أشواط: يبدأ بالصفا ويختم بالمروة، يذكر الله ويدعو عند كل جبل، ويسعى بين العلمين الأخضرين.",
                    summaryEn = "Seven circuits starting at Safa and ending at Marwah, with dhikr and supplication at each hill and quickening between the two green markers.",
                    steps = listOf(
                        HajjStep(
                            "أشواط السعي",
                            "The circuits of sa'i",
                            "يصعد المعتمر على الصفا فيستقبل الكعبة ويكبر ويحمد الله ويدعو، ثم يمشي إلى المروة، ويسعى (يُسرع) بين العلمين الأخضرين، ويصعد على المروة ويفعل كفعلته الأولى، وهكذا حتى يكمل سبعة أشواط: يبدأ بالصفا ويختم بالمروة.",
                            "The pilgrim ascends Safa, faces the Kaaba, says takbir, praises Allah and supplicates, then walks to Marwah, quickening between the two green markers, ascends Marwah and repeats, completing seven circuits: starting at Safa and ending at Marwah.",
                            "قال تعالى: ﴿إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ ۚ فَمَنْ حَجَّ الْبَيْتَ أَوِ اعْتَمَرَ فَلَا جُنَاحَ عَلَيْهِ أَن يَطَّوَّفَ بِهِمَا﴾ [البقرة 158].",
                            "Allah says: 'Indeed Safa and Marwah are among the symbols of Allah. Whoever performs Hajj or Umrah — there is no blame upon him to walk between them' [Al-Baqarah 158].",
                            say = "على الصفا والمروة: «الله أكبر الله أكبر الله أكبر، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ» ثلاثًا، ثم يدعو.",
                            sayEn = "At Safa and Marwah: 'Allahu akbar, Allahu akbar, Allahu akbar; la ilaha illa Allah wahdahu la sharika lah, lahul-mulk wa lahul-hamd wa huwa 'ala kulli shay'in qadir' three times, then supplicate.",
                            why = "السعي ركن من أركان العمرة، وفيه إحياء لقصة هاجر عليها السلام لما سعت بين الجبلين تبحث عن الماء لابنها إسماعيل، ففجّر الله لها زمزم.",
                            whyEn = "Sa'i is a pillar of Umrah, reviving the story of Hajar, peace be upon her, who ran between the two hills seeking water for her son Ismail until Allah brought forth Zamzam.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "umrah_tahlul",
                    title = "الحلق أو التقصير والتحلل",
                    titleEn = "Shaving or shortening, and the tahlul",
                    summary = "بعد السعي يحلق الرجل رأسه أو يقصر، وتقصر المرأة، وبذلك تتم العمرة ويحل من إحرامه.",
                    summaryEn = "After the sa'i the man shaves his head or shortens, the woman shortens, and the Umrah is complete and ihram is exited.",
                    steps = listOf(
                        HajjStep(
                            "الحلق أو التقصير",
                            "Shaving or shortening",
                            "يحلق الرجل رأسه كله أو يقصر من جميع جهات رأسه (والحلق أفضل)، وتقصر المرأة قدر أنملة من أطراف شعرها، ثم يخلع ملابس الإحرام ويلبس ثيابه وقد حلّ من كل شيء.",
                            "The man shaves his whole head or shortens from all sides (shaving is better); the woman shortens a fingertip's length from her hair ends. Then he takes off the ihram garments, dresses normally, and everything is lawful again.",
                            "قال تعالى: ﴿مُحَلِّقِينَ رُءُوسَكُمْ وَمُقَصِّرِينَ﴾ [الفتح 27].",
                            "Allah says: 'Shaving your heads and shortening' [Al-Fath 27].",
                            why = "الحلق أو التقصير آخر مناسك العمرة، وبه يتحلل المعتمر من إحرامه، وفيه التواضع لله وإظهار العبودية.",
                            whyEn = "Shaving or shortening is the last rite of Umrah; with it the pilgrim exits ihram, in humility before Allah and manifestation of servitude.",
                        ),
                    ),
                ),
            ),
        ),

        HajjCategory(
            id = "ihram_prohibitions",
            title = "محظورات الإحرام",
            titleEn = "Prohibitions of ihram",
            subtitle = "ما يمنع على المحرم وما يفديه، وما يباح له",
            subtitleEn = "What is forbidden to the muhrim, its fidyah, and what remains permissible",
            iconKey = "warning",
            topics = listOf(
                HajjTopic(
                    id = "common_prohibitions",
                    title = "المحظورات المشتركة",
                    titleEn = "Common prohibitions",
                    summary = "أمور محرمة على المحرم والمحرمة جميعًا: الشعر، الظفر، الطيب، الصيد، النكاح، الجماع.",
                    summaryEn = "Things forbidden to both men and women in ihram: hair, nails, perfume, hunting, marriage and marital relations.",
                    steps = listOf(
                        HajjStep(
                            "المحظورات المشتركة",
                            "The shared prohibitions",
                            "يحرم على المحرم: إزالة الشعر وقص الأظافر، والتطيب (في البدن أو الثوب)، والصيد (قتل أو إعانة أو إشارة)، وعقد النكاح والخطبة له، والجماع ومقدماته، والفسوق (المعاصي) والجدال.",
                            "Forbidden to the muhrim: removing hair and trimming nails; applying perfume (to the body or garment); hunting (killing, helping or pointing); contracting or proposing marriage; sexual relations and their preludes; and sin and quarrelling.",
                            "قال تعالى: ﴿يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَقْتُلُوا الصَّيْدَ وَأَنتُمْ حُرُمٌ﴾ [المائدة 95]، وقال ﷺ: «لَا يَنْكِحُ الْمُحْرِمُ وَلَا يُنْكِحُ».",
                            "Allah says: 'O you who believe, do not kill game while you are in ihram' [Al-Ma'idah 95]; the Prophet ﷺ said: 'The muhrim must not marry nor give in marriage.'",
                            why = "هذه المحظورات حفظ لشعائر الإحرام وتدريب للنفس على الطاعة والزهد، حتى لا يشغل المحرمَ شيء عن ذكر الله.",
                            whyEn = "These prohibitions preserve the sanctity of ihram and train the soul in obedience and detachment, so that nothing distracts the pilgrim from the remembrance of Allah.",
                        ),
                        HajjStep(
                            "الجماع في الإحرام",
                            "Marital relations in ihram",
                            "الجماع قبل التحلل الأول محرم بإجماع، وهو أعظم محظورات الإحرام: من جامع قبل الوقوف بعرفة فسد حجه وعليه دم مع الإتمام؛ ومن جامع بعد التحلل الأول وقبل الثاني فحجه صحيح وعليه دم.",
                            "Marital relations before the first tahlul are forbidden by consensus and are the gravest prohibition: whoever has relations before the standing at Arafah invalidates his Hajj (he must complete it and offer a sacrifice); after the first tahlul the Hajj is valid but a sacrifice is due.",
                            "قال تعالى: ﴿فَمَن فَرَضَ فِيهِنَّ الْحَجَّ فَلَا رَفَثَ﴾ [البقرة 197] — والرفث هو الجماع ومقدماته.",
                            "Allah says: 'Whoever intends the Hajj therein — there is no obscenity (rafath)' [Al-Baqarah 197] — and rafath is marital relations and its preludes.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "male_prohibitions",
                    title = "محظورات خاصة بالرجل",
                    titleEn = "Prohibitions specific to men",
                    summary = "لبس المخيط، وتغطية الرأس، أما تغطية الوجه فعند الجمهور جائزة له.",
                    summaryEn = "Wearing sewn garments and covering the head; covering the face is permissible for men in the view of the majority.",
                    steps = listOf(
                        HajjStep(
                            "لبس المخيط وتغطية الرأس",
                            "Sewn garments and covering the head",
                            "يحرم على الرجل المحرم لبس القميص والسراويل والعمائم والخفاف ونحوها مما خيط على قدر العضو، ويحرم تغطية رأسه بما يلاصقه (كالقبعة)؛ ويباح له تغطية الوجه عند الجمهور، والإزار والرداء والخفان عند عدم النعلين.",
                            "Forbidden to the muhrim man: wearing shirts, trousers, turbans, socks and the like tailored to the body, and covering the head with anything touching it (like a cap). Covering the face is permissible in the view of the majority; the izar, rida' and leather socks when sandals are unavailable are fine.",
                            "سُئل النبي ﷺ: ماذا يلبس المحرم؟ قال: «لَا يَلْبَسُ الْقَمِيصَ، وَلَا الْعَمَائِمَ، وَلَا السَّرَاوِيلَاتِ، وَلَا الْبَرَانِسَ، وَلَا الْخِفَافَ».",
                            "Asked what the muhrim may wear, the Prophet ﷺ said: 'He must not wear shirts, turbans, trousers, hooded cloaks or khuffs (socks).'",
                            why = "لباس الإحرام شعار المساواة والتجرد من زينة الدنيا، وترك المخيط امتثال لأمر النبي ﷺ وإظهار للعبودية.",
                            whyEn = "The ihram garments symbolise equality and detachment from worldly adornment; abandoning sewn clothing obeys the Prophet's ﷺ command and manifests servitude.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "female_prohibitions",
                    title = "محظورات خاصة بالمرأة",
                    titleEn = "Prohibitions specific to women",
                    summary = "لا تنتقب ولا تلبس القفازين، وتلبس من الثياب غير المخيط المصنوع للزينة.",
                    summaryEn = "She must not wear a niqab or gloves, and wears garments that are not sewn for adornment.",
                    steps = listOf(
                        HajjStep(
                            "ما يمنع على المرأة",
                            "What is forbidden to her",
                            "تحرم على المحرمة: النقاب (تغطية الوجه بنقاب) والقفازان، ولبس ما خيط على قدر العضو من ثياب الزينة؛ ويباح لها تغطية وجهها بغير نقاب عند مرور الرجال الأجانب، ولبس ما شاءت من الثياب المباحة غير المتطيبة.",
                            "Forbidden to the muhrimah: the niqab (face-covering veil) and gloves, and wearing sewn garments of adornment. She may cover her face with something other than a niqab when unrelated men pass, and may wear whatever permissible clothing she wishes without perfume.",
                            "قال ﷺ: «الْمُحْرِمَةُ لَا تَنْتَقِبْ وَلَا تَلْبَسُ الْقُفَّازَيْنِ».",
                            "The Prophet ﷺ said: 'The muhrimah must not wear a niqab nor gloves.'",
                            why = "منع النقاب والقفازين من باب ترك الزينة في الإحرام، مع حفظ المرأة لسترها بغير ذلك عند الحاجة.",
                            whyEn = "Forbidding the niqab and gloves removes adornment during ihram, while the woman still preserves her modesty by other means when needed.",
                        ),
                        HajjStep(
                            "الحيض في النسك",
                            "Menstruation during the rites",
                            "إذا حاضت المرأة في النسك: تبقي على إحرامها وتؤدي ما عدا الطواف (كالوقوف والسعي)، وإذا طهرت طافت؛ فإن حاضت قبل طواف الوداع سقط عنها عند الجمهور.",
                            "If a woman menstruates during the rites she remains in ihram and performs all except tawaf (such as the standing and sa'i); when she becomes pure she performs tawaf. If she menstruates before the farewell tawaf, it is excused in the view of the majority.",
                            "قال النبي ﷺ لعائشة رضي الله عنها حين حاضت: «افْعَلِي مَا يَفْعَلُ الْحَاجُّ غَيْرَ أَنْ لَا تَطُوفِي بِالْبَيْتِ حَتَّى تَطْهُرِي».",
                            "The Prophet ﷺ told Aishah, may Allah be pleased with her, when she menstruated: 'Do what the pilgrim does, except do not circumambulate the House until you become pure.'",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "fidyah",
                    title = "الفدية (الكفارة)",
                    titleEn = "The fidyah (compensation)",
                    summary = "من فعل محظورًا فعليه جبران: دم أو صيام أو صدقة، بحسب المحظور.",
                    summaryEn = "Whoever commits a prohibition owes compensation: a sacrifice, fasting or charity, according to the act.",
                    steps = listOf(
                        HajjStep(
                            "أحكام الفدية",
                            "The rulings of fidyah",
                            "من ارتكب محظورًا جاهلًا أو ناسيًا أو مكرهًا فلا شيء عليه. ومن فعله باختيار من غير عذر: إن كان المحظور كإزالة الشعر أو الطيب أو اللبس، فله الخيار: دم (شاة) أو صيام ثلاثة أيام أو إطعام ستة مساكين (مد لكل مسكين). وإن كان جماعًا ففدية أعظم: بدنة أو بقرة أو شاة + صيام + إطعام عند تفصيل أهل العلم.",
                            "Whoever commits a prohibition out of ignorance, forgetfulness or coercion owes nothing. If done by choice without excuse: for hair removal, perfume or clothing, he chooses between a sacrifice (sheep), fasting three days, or feeding six poor people. For marital relations the compensation is greater: a camel, cow or sheep, plus fasting and feeding, in the detailed view of the scholars.",
                            "قال تعالى: ﴿فَمَن كَانَ مِنكُم مَّرِيضًا أَوْ بِهِ أَذًى مِّن رَّأْسِهِ فَفِدْيَةٌ مِّن صِيَامٍ أَوْ صَدَقَةٍ أَوْ نُسُكٍ﴾ [البقرة 196].",
                            "Allah says: 'Whoever among you is ill or has an ailment of the head — then a compensation of fasting, charity or a sacrifice' [Al-Baqarah 196].",
                            why = "الفدية جبران للنقص الواقع في النسك، ورحمة من الله أن جعل للعبد مخرجًا عند العذر، ودرسًا في حفظ حرمات الإحرام.",
                            whyEn = "The fidyah compensates for the shortfall in the rites, and is a mercy from Allah giving the servant an exit when excused, while teaching the sanctity of ihram.",
                        ),
                        HajjStep(
                            "حكم الصيد",
                            "The ruling on hunting",
                            "من قتل صيدًا متعمدًا فعليه الجزاء: مثل ما قتل من النعم يحكم به عدلان، يُذبح ويُطعم الفقراء، أو قيمته طعامًا، أو صيامًا بعدد الأمداد؛ ومن قتله ناسيًا أو مخطئًا: الكفارة فقط بلا إثم.",
                            "Whoever deliberately kills game owes its equivalent as judged by two just persons: a like domestic animal slaughtered and fed to the poor, or its value as food, or fasting for each mudd. If killed forgetfully or by mistake, the compensation applies without sin.",
                            "قال تعالى: ﴿وَمَن قَتَلَهُ مِنكُم مُّتَعَمِّدًا فَجَزَاءٌ مِّثْلُ مَا قَتَلَ مِنَ النَّعَمِ﴾ [المائدة 95].",
                            "Allah says: 'And whoever of you kills it intentionally — then a penalty equivalent to what he killed of livestock' [Al-Ma'idah 95].",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "allowed_ihram",
                    title = "المباحات في الإحرام",
                    titleEn = "What remains permissible in ihram",
                    summary = "أمور يشيع السؤال عنها: الاغتسال، الظل، حمل المتاع، لبس الساعة والنظارة...",
                    summaryEn = "Commonly asked about matters: bathing, shade, carrying belongings, wearing a watch or glasses...",
                    steps = listOf(
                        HajjStep(
                            "المباحات",
                            "The permissible matters",
                            "يباح للمحرم: الاغتسال والوضوء (دون استعمال طيب)، ودخول الظل، وشرب الماء، وحمل المتاع، ولبس النظارة والساعة والخاتم والحزام وحقيبة الكتف، وشد الإزار بالخاتم أو الحزام، وتغطية الوجه للرجل، وضرب الخيمة.",
                            "Permissible for the muhrim: bathing and ablution (without perfume), entering shade, drinking water, carrying belongings, wearing glasses, a watch, a ring, a belt or a shoulder bag, fastening the izar with a pin or belt, a man covering his face, and pitching a tent.",
                            "اغتسل النبي ﷺ وهو محرم، وكان ﷺ إذا نزل ضربت له قبة يستظل بها.",
                            "The Prophet ﷺ bathed while in ihram, and when he camped a tent was pitched for him to shade under.",
                            why = "الشريعة لم تضيق على المحرم في الحاجات الضرورية، فجاءت بالتيسير في المباحات حفظًا للنفس ورحمة بالعباد.",
                            whyEn = "The law does not burden the muhrim in essential needs, permitting these matters to preserve wellbeing and show mercy to the servants.",
                        ),
                    ),
                ),
            ),
        ),

        HajjCategory(
            id = "duas",
            title = "الأدعية والأذكار",
            titleEn = "Supplications and dhikr",
            subtitle = "التلبية وأدعية الطواف والسعي وعرفة والرمي",
            subtitleEn = "The talbiyah and the supplications of tawaf, sa'i, Arafah and stoning",
            iconKey = "favorite",
            topics = listOf(
                HajjTopic(
                    id = "dua_talbiyah",
                    title = "التلبية ونصها",
                    titleEn = "The talbiyah and its wording",
                    summary = "شعار الحاج من الإحرام إلى رمي جمرة العقبة يوم النحر.",
                    summaryEn = "The pilgrim's slogan from ihram until stoning Jamrat al-Aqabah on the Day of Sacrifice.",
                    steps = listOf(
                        HajjStep(
                            "نص التلبية",
                            "The wording of the talbiyah",
                            "«لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ» — يرفع الرجل صوته، وتسر المرأة.",
                            "'Labbayka Allahumma labbayk, labbayka la sharika laka labbayk, inna al-hamda wan-ni'mata laka wal-mulk, la sharika lak.' Men raise their voices; women recite quietly.",
                            why = "التلبية إجابة لنداء الله وإظهار للتوحيد؛ قال ﷺ: «أَتَانِي جِبْرِيلُ فَأَمَرَنِي أَنْ آمُرَ أَصْحَابِي أَنْ يَرْفَعُوا أَصْوَاتَهُمْ بِالتَّلْبِيَةِ»، وقال تعالى: ﴿وَأَذِّن فِي النَّاسِ بِالْحَجِّ﴾ [الحج 27].",
                            whyEn = "The talbiyah answers Allah's call and proclaims tawhid; the Prophet ﷺ said: 'Jibreel came and commanded me to order my companions to raise their voices with the talbiyah,' and Allah says: 'And proclaim to the people the Hajj' [Al-Hajj 27].",
                            say = "يكررها الحاج عند كل تغير حال: نزول، صعود، ركوب، لقاء رفقة، وعند دخول الصلاة، ويدعو بعدها بما شاء.",
                            sayEn = "Repeat it whenever circumstances change — descending, ascending, riding, meeting companions, entering prayer — and supplicate after it as you wish.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "dua_tawaf_sai",
                    title = "أدعية الطواف والسعي",
                    titleEn = "Supplications of tawaf and sa'i",
                    summary = "أذكار المواضع المخصوصة في الطواف والسعي، وفضل الدعاء فيهما.",
                    summaryEn = "The dhikr of the specific stations in tawaf and sa'i, and the virtue of supplication in them.",
                    steps = listOf(
                        HajjStep(
                            "في الطواف",
                            "During tawaf",
                            "يذكر الله ويدعو في جميع الأشواط، ويقول عند الحجر الأسود: «بسم الله والله أكبر»، وبين الركن اليماني والحجر: «رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ».",
                            "Mention Allah and supplicate in all the circuits; at the Black Stone say 'Bismillah, Allahu akbar,' and between the Yemeni Corner and the Stone: 'Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire.'",
                            "كان ﷺ يكثر في الطواف من هذا الدعاء بين الركنين، ويقول عند الحجر: «الله أكبر».",
                            "The Prophet ﷺ frequently recited this supplication between the two corners during tawaf and said 'Allahu akbar' at the Stone.",
                        ),
                        HajjStep(
                            "في السعي",
                            "During sa'i",
                            "على الصفا والمروة يقرأ: «إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ»، ثم يستقبل القبلة ويهلل ويكبر ويحمد ويدعو ثلاثًا، ويكثر من الدعاء في كل شوط.",
                            "At Safa and Marwah recite: 'Indeed Safa and Marwah are among the symbols of Allah,' then face the qiblah and say tahlil, takbir, praise and supplication three times, and supplicate frequently in every circuit.",
                            "قال ﷺ: «الدُّعَاءُ هُوَ الْعِبَادَةُ» — وقال تعالى: ﴿وَادْعُوهُ خَوْفًا وَطَمَعًا﴾ [الأعراف 56].",
                            "The Prophet ﷺ said: 'Supplication is worship'; Allah says: 'And call upon Him in fear and aspiration' [Al-A'raf 56].",
                            say = "«الله أكبر الله أكبر الله أكبر، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ» — ثلاث مرات ثم يدعو.",
                            sayEn = "'Allahu akbar (three times); la ilaha illa Allah wahdahu la sharika lah, lahul-mulk wa lahul-hamd wa huwa 'ala kulli shay'in qadir' — three times, then supplicate.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "dua_arafah",
                    title = "أدعية عرفة والمواقف",
                    titleEn = "Supplications of Arafah and the stations",
                    summary = "خير الدعاء دعاء يوم عرفة: المواقف العظيمة والأدعية الجامعة.",
                    summaryEn = "The best of supplication is the supplication of the Day of Arafah: the great stations and the comprehensive supplications.",
                    steps = listOf(
                        HajjStep(
                            "دعاء يوم عرفة",
                            "The supplication of Arafah",
                            "أفضل ما يقول الحاج يوم عرفة: «لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ»، ثم يدعو لنفسه ووالديه وأهله وللمسلمين، ويرفع يديه مستقبلًا القبلة.",
                            "The best thing to say on the Day of Arafah: 'La ilaha illa Allah wahdahu la sharika lah, lahul-mulk wa lahul-hamd wa huwa 'ala kulli shay'in qadir,' then supplicate for yourself, your parents, your family and all Muslims, with raised hands facing the qiblah.",
                            "قال ﷺ: «خَيْرُ الدُّعَاءِ دُعَاءُ يَوْمِ عَرَفَةَ».",
                            say = "«لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ» + «اللهم اغفر لي ولوالدي وللمسلمين» + أي دعاء جامع من خير الدنيا والآخرة.",
                            sayEn = "The tahlil of Arafah, then: 'O Allah, forgive me, my parents and the Muslims,' plus any comprehensive supplication for the good of this world and the next.",
                            why = "قال ﷺ: «خَيْرُ الدُّعَاءِ دُعَاءُ يَوْمِ عَرَفَةَ»، ويوم عرفة يوم مغفرة وعتق من النار: «مَا مِنْ يَوْمٍ أَكْثَرَ مِنْ أَنْ يُعْتِقَ اللَّهُ فِيهِ عَبْدًا مِنَ النَّارِ مِنْ يَوْمِ عَرَفَةَ».",
                            whyEn = "The Prophet ﷺ said: 'The best of supplication is the supplication of the Day of Arafah'; Arafah is a day of forgiveness and freedom from the Fire: 'No day has more people freed from the Fire by Allah than the Day of Arafah.'",
                        ),
                        HajjStep(
                            "دعاء المشعر الحرام",
                            "Supplication at the Sacred Monument",
                            "بعد الفجر بمزدلفة يقف عند المشعر الحرام مستقبلًا القبلة، فيهلل ويكبر ويدعو حتى يسفر جدًا، ويكثر من: «اللهم كما وقفتنا فيه وأريتناه فوفقنا لذكرك وشكرك وحسن عبادتك».",
                            "After Fajr at Muzdalifah, stand at the Sacred Monument facing the qiblah, saying tahlil, takbir and supplication until the light is bright, repeating: 'O Allah, as You have made us stand here and shown it to us, grant us success in Your remembrance, gratitude and excellent worship.'",
                            "قال تعالى: ﴿فَاذْكُرُوا اللَّهَ عِندَ الْمَشْعَرِ الْحَرَامِ ۖ وَاذْكُرُوهُ كَمَا هَدَاكُمْ﴾ [البقرة 198].",
                            "Allah says: 'Remember Allah at the Sacred Monument, and remember Him as He has guided you' [Al-Baqarah 198].",
                        ),
                        HajjStep(
                            "دعاء يوم النحر والتشريق",
                            "Supplication on the Day of Sacrifice and Tashreeq",
                            "عند رمي الجمار يكبر مع كل حصاة، وبعد رمي الصغرى والوسطى يدعو طويلًا، ويكثر في أيام التشريق من التكبير: «الله أكبر الله أكبر لا إله إلا الله، والله أكبر الله أكبر ولله الحمد».",
                            "When stoning, say takbir with each pebble; after the first and middle jamarat supplicate at length; during the days of Tashreeq repeat the takbir: 'Allahu akbar, Allahu akbar, la ilaha illa Allah; Allahu akbar, Allahu akbar, wa lillahil-hamd.'",
                            "قال تعالى: ﴿وَاذْكُرُوا اللَّهَ فِي أَيَّامٍ مَّعْدُودَاتٍ﴾ [البقرة 203] — وأمر بالذكر في أيام التشريق.",
                            "Allah says: 'And remember Allah during specified days' [Al-Baqarah 203] — commanding remembrance in the days of Tashreeq.",
                        ),
                    ),
                ),
                HajjTopic(
                    id = "dua_general",
                    title = "أدعية جامعة للحج والعمرة",
                    titleEn = "Comprehensive supplications for Hajj and Umrah",
                    summary = "دعاء دخول مكة، وعند رؤية الكعبة، وأدعية جامعة لأوقات الإجابة.",
                    summaryEn = "Supplications for entering Makkah, upon seeing the Kaaba, and comprehensive duas for the answered moments.",
                    steps = listOf(
                        HajjStep(
                            "دخول مكة ورؤية الكعبة",
                            "Entering Makkah and seeing the Kaaba",
                            "عند دخول المسجد الحرام يقدم رجله اليمنى ويدعو بدعاء دخول المسجد، وعند رؤية الكعبة يرفع يديه ويدعو: «اللهم زد هذا البيت تعظيمًا وتشريفًا وتكريمًا ومهابة، وزد من عظمه وشرّفه تكريمًا» ويسأل الله من فضله.",
                            "Entering the Sacred Mosque, step with the right foot and recite the du'a of entering the mosque. Upon seeing the Kaaba, raise your hands and supplicate: 'O Allah, increase this House in reverence, honour, veneration and awe, and increase in honour those who honour it,' and ask Allah of His bounty.",
                            "كان ﷺ إذا رأى الكعبة رفع يديه ودعا، وقال: «هَذَا الْبَيْتُ الْحَرَامُ، اللَّهُمَّ زِدْهُ تَعْظِيمًا».",
                            "When the Prophet ﷺ saw the Kaaba he raised his hands and supplicated: 'This is the Sacred House; O Allah, increase it in reverence.'",
                        ),
                        HajjStep(
                            "أدعية جامعة",
                            "Comprehensive supplications",
                            "من الجوامع: «اللهم اجعل حجي مبرورًا وسعيي مشكورًا وذنبي مغفورًا»، و«رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ»، و«اللهم إني أسألك رضاك والجنة، وأعوذ بك من سخطك والنار».",
                            "Among the comprehensive supplications: 'O Allah, make my Hajj accepted, my sa'i appreciated, and my sin forgiven'; 'Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire'; and 'O Allah, I ask You for Your pleasure and Paradise, and I seek refuge in You from Your wrath and the Fire.'",
                            why = "مواسم الحج من أعظم أوقات إجابة الدعاء؛ قال ﷺ: «أَفْضَلُ الذِّكْرِ لَا إِلَهَ إِلَّا اللَّهُ، وَأَفْضَلُ الدُّعَاءِ الْحَمْدُ لِلَّهِ»، والموفق من اغتنم كل موقف.",
                            whyEn = "The seasons of Hajj are among the greatest times for answered supplication; the Prophet ﷺ said: 'The best dhikr is la ilaha illa Allah, and the best supplication is al-hamdulillah.' The successful one seizes every moment.",
                        ),
                    ),
                ),
            ),
        ),
    )

    fun categoryById(id: String): HajjCategory? = CATEGORIES.firstOrNull { it.id == id }
}
