package org.muslim.app.feature.learn.domain

import org.muslim.app.feature.learn.R

/**
 * Structured learning content (PROJECT_PROMPT.md §6 Phase 5): step-by-step
 * wudu / ghusl / tayammum / salah guides, special prayers and a rak'ah
 * reference table.
 *
 * Religious content note (§10): the texts follow mainstream, widely
 * published fiqh wording. Madhhab differences are noted neutrally. Always
 * subject to independent scholarly review before release.
 */
data class LearnStep(
    val title: String,
    val description: String,
    val dua: String? = null,
)

data class LearnTopic(
    val id: String,
    val titleRes: Int,
    val subtitleRes: Int,
    val steps: List<LearnStep>,
    val notes: String? = null,
)

object LearnContent {

    val topics: List<LearnTopic> = listOf(
        LearnTopic(
            id = "wudu",
            titleRes = R.string.learn_topic_wudu,
            subtitleRes = R.string.learn_topic_wudu_sub,
            steps = listOf(
                LearnStep("النية", "ينوي الطهارة في قلبه، ويسمي (بسم الله)."),
                LearnStep("غسل الكفين", "يغسل كفيه ثلاث مرات."),
                LearnStep("المضمضة والاستنشاق", "يتمضمض ويستنشق ثلاثًا، ويستنثر."),
                LearnStep("غسل الوجه", "يغسل وجهه ثلاثًا من منابت الشعر إلى الذقن."),
                LearnStep("غسل اليدين إلى المرفقين", "يغسل يده اليمنى ثم اليسرى إلى المرفقين ثلاثًا."),
                LearnStep("مسح الرأس والأذنين", "يمسح رأسه مرة، ويمسح أذنيه بالماء الجديد."),
                LearnStep("غسل الرجلين", "يغسل رجله اليمنى ثم اليسرى إلى الكعبين ثلاثًا."),
                LearnStep(
                    "الدعاء بعد الوضوء",
                    "يستحب بعد الفراغ أن يقول: «أشهد أن لا إله إلا الله وحده لا شريك له، وأشهد أن محمدًا عبده ورسوله».",
                    dua = "اللهم اجعلني من التوابين واجعلني من المتطهرين",
                ),
            ),
            notes = "الترتيب والموالاة من الفرائض عند الجمهور. تكرار الغسل ثلاثًا سنة. خلاف مذهبي يسير في مسح الأذنين (بماء الرأس أو بماء جديد) يعرضه المختصون بحياد.",
        ),
        LearnTopic(
            id = "ghusl",
            titleRes = R.string.learn_topic_ghusl,
            subtitleRes = R.string.learn_topic_ghusl_sub,
            steps = listOf(
                LearnStep("النية والتسمية", "ينوي الاغتسال ويسمي."),
                LearnStep("غسل اليدين والفرج", "يغسل يديه، ثم يغسل فرجه."),
                LearnStep("الوضوء", "يتوضأ وضوءه للصلاة."),
                LearnStep("إفاضة الماء على الرأس", "يُفْضِئ الماء على رأسه ثلاثًا مع تدليك الأصول."),
                LearnStep("غسل بقية الجسد", "يغسل سائر جسده، ويتيامن في الغسل."),
            ),
            notes = "الغسل واجب عند الجنابة والحيض والنفاس. يكفي أن يعمّ الماء جميع البدن مع النية والمضمضة والاستنشاق عند الجمهور.",
        ),
        LearnTopic(
            id = "tayammum",
            titleRes = R.string.learn_topic_tayammum,
            subtitleRes = R.string.learn_topic_tayammum_sub,
            steps = listOf(
                LearnStep("النية", "ينوي التيمم لرفع الحدث — عند فقد الماء أو العجز عن استعماله."),
                LearnStep("الضربة الأولى", "يضرب يديه على التراب الطاهر."),
                LearnStep("مسح الوجه", "يمسح وجهه بهما."),
                LearnStep("الضربة الثانية ومسح اليدين", "يضرب ضربة ثانية ويمسح يديه إلى المرفقين."),
            ),
            notes = "يجوز التيمم عند فقد الماء أو المرض الذي يمنع استعماله. يبطل التيمم بوجود الماء (مع القدرة) وبما يبطل الوضوء.",
        ),
        LearnTopic(
            id = "salah",
            titleRes = R.string.learn_topic_salah,
            subtitleRes = R.string.learn_topic_salah_sub,
            steps = listOf(
                LearnStep("القيام والتكبير", "يستقبل القبلة، ويرفع يديه مكبِّرًا (تكبيرة الإحرام) قائلًا: «الله أكبر»."),
                LearnStep("الاستفتاح والقراءة", "يقرأ دعاء الاستفتاح ثم الفاتحة وما تيسر من القرآن."),
                LearnStep("الركوع", "يركع قائلًا: «الله أكبر»، ويطمئن، ويقول: «سبحان ربي العظيم» ثلاثًا."),
                LearnStep("الرفع من الركوع", "يرفع قائلًا: «سمع الله لمن حمده، ربنا ولك الحمد»."),
                LearnStep("السجود الأول", "يسجد قائلًا: «الله أكبر»، ويقول: «سبحان ربي الأعلى» ثلاثًا."),
                LearnStep("الجلسة بين السجدتين", "يجلس مطمئنًا ويقول: «رب اغفر لي وارحمني»."),
                LearnStep("السجود الثاني", "يسجد الثانية كالأولى، ثم يقوم للركعة التالية."),
                LearnStep("التشهد الأخير والتسليم", "في آخر الصلاة يجلس للتشهد، ويصلي على النبي ﷺ، ثم يسلم عن يمينه وعن شماله."),
            ),
            notes = "الطمأنينة ركن عند الجمهور. التفاصيل الدقيقة (موضع اليدين، كيفية السجود، القنوت) تختلف بين المذاهب الأربعة — تُعرض فروقها بحياد في قسم الفروقات المذهبية.",
        ),
        LearnTopic(
            id = "special",
            titleRes = R.string.learn_topic_special,
            subtitleRes = R.string.learn_topic_special_sub,
            steps = listOf(
                LearnStep("صلاة الجنازة", "أربع تكبيرات بلا ركوع ولا سجود؛ بعد الأولى الفاتحة، وبعد الثانية الصلاة على النبي ﷺ، وبعد الثالثة الدعاء للميت، وبعد الرابعة التسليم."),
                LearnStep("صلاة العيدين", "ركعتان: يكبر في الأولى سبع تكبيرات (بعد تكبيرة الإحرام) وفي الثانية خمسًا (عند الجمهور)، ثم يخطب الإمام بعدها."),
                LearnStep("التراويح", "قيام رمضان بعد صلاة العشاء، مثنى مثنى، ويُختم بوتر."),
                LearnStep("الوتر", "ركعة فأكثر (وصلًا أو فصلًا)؛ يختم بها صلاة الليل."),
                LearnStep("الضحى", "ركعتان فأكثر، من ارتفاع الشمس إلى قبل الزوال."),
                LearnStep("التهجد", "قيام الليل بعد نوم، مثنى مثنى، وأفضله في الثلث الأخير."),
                LearnStep("الاستخارة", "ركعتان من غير الفريضة ثم دعاء الاستخارة: «اللهم إني أستخيرك بعلمك...»."),
                LearnStep("الجمع والقصر للمسافر", "يقصر المسافر الرباعية إلى ركعتين، ويجمع بين الظهر والعصر والمغرب والعشاء جمع تقديم أو تأخير."),
            ),
        ),
        LearnTopic(
            id = "rakats",
            titleRes = R.string.learn_topic_rakats,
            subtitleRes = R.string.learn_topic_rakats_sub,
            steps = listOf(
                LearnStep("الفجر", "ركعتان، تجهر فيهما القراءة."),
                LearnStep("الظهر", "أربع ركعات، تُسرّ القراءة."),
                LearnStep("العصر", "أربع ركعات، تُسرّ القراءة."),
                LearnStep("المغرب", "ثلاث ركعات، يجهر في الأوليين."),
                LearnStep("العشاء", "أربع ركعات، يجهر في الأوليين."),
                LearnStep("الجمعة", "ركعتان بعد الخطبة — بدل الظهر."),
                LearnStep("العيدان", "ركعتان."),
                LearnStep("التراويح والوتر", "التراويح 8 أو 20 ركعة (خلاف مشهور)، ثم الوتر 1–11 ركعة."),
            ),
        ),
        LearnTopic(
            id = "madhhab",
            titleRes = R.string.learn_topic_madhhab,
            subtitleRes = R.string.learn_topic_madhhab_sub,
            steps = listOf(
                LearnStep("مسح الرأس", "الحنفية: مسح ربع الرأس. الشافعية: مسح كل الرأس. المالكية والحنابلة: مسح جميع الرأس أيضًا (الحنابلة يمسح الأذنين معه)."),
                LearnStep("موضع اليدين في الصلاة", "الحنفية: تحت السرة. الشافعية: تحت الصدر. المالكية: تحت الصدر (بعد التكبير). الحنابلة: تحت السرة أو فوقها."),
                LearnStep("القنوت", "شافعية: في الفجر دائمًا. الحنفية: في الوتر. المالكية والحنابلة: عند النوازل في الفريضة."),
                LearnStep("التشهد الأول", "الجميع يتشهدون بعد الركعتين في الثلاثية والرباعية، ويقومون بعدها."),
                LearnStep("جلسة التشهد", "الافتراش في الجلسات كلها عند الشافعية؛ والتورك في الأخيرة عند الحنفية والمالكية والحنابلة (مع خلاف في موضعه)."),
            ),
            notes = "هذه الفروق عرض محايد لا ترجيح فيه؛ يختار المسلم ما يطمئن إليه مع مراجعة أهل العلم. المشروع لا يرجّح مذهبًا على آخر (§6 المرحلة 5 و§10).",
        ),
        LearnTopic(
            id = "names_of_allah",
            titleRes = R.string.learn_topic_names_of_allah,
            subtitleRes = R.string.learn_topic_names_of_allah_sub,
            steps = listOf(
                LearnStep("اللَّه", "المعبود بحق الذي تألهه القلوب محبةً وتعظيمًا — The One true God worshipped by all hearts"),
                LearnStep("الرَّحْمَٰن", "ذو الرحمة الواسعة التي وسعت كل شيء — The Most Merciful to all creation"),
                LearnStep("الرَّحِيم", "الموصِل رحمته لمن يشاء من عباده — The Bestower of special mercy on believers"),
                LearnStep("الْمَلِك", "المالك المتصرف في الملك كله — The King, the Owner of all dominion"),
                LearnStep("الْقُدُّوس", "المنزه عن كل عيب ونقص — The Most Pure and Holy"),
                LearnStep("السَّلَام", "السالم من كل نقص، ومانح السلام لخلقه — The Source of peace and perfection"),
                LearnStep("الْمُؤْمِن", "المصدق لرسله، المؤمِّن لخلقه من الخوف — The Granter of security and faith"),
                LearnStep("الْمُهَيْمِن", "الرقيب الحافظ لكل شيء — The Watchful Guardian over all"),
                LearnStep("الْعَزِيز", "القوي الغالب الذي لا يُقهر — The Almighty, the Invincible"),
                LearnStep("الْجَبَّار", "القاهر لخلقه بجبروته، جابر كل كسير — The Compeller who mends and subdues"),
                LearnStep("الْمُتَكَبِّر", "المتعالي عن صفات الخلق — The Supreme in greatness"),
                LearnStep("الْخَالِق", "الموجد للأشياء من غير مثال سابق — The Creator"),
                LearnStep("الْبَارِئ", "المنشئ للخلق بريئًا من التفاوت — The Originator who creates flawlessly"),
                LearnStep("الْمُصَوِّر", "الذي صوّر المخلوقات وأحسن صورها — The Fashioner of forms"),
                LearnStep("الْغَفَّار", "الذي يغفر الذنوب مهما تكررت — The Ever-Forgiving"),
                LearnStep("الْقَهَّار", "الغالب لكل شيء — The All-Dominant"),
                LearnStep("الْوَهَّاب", "المعطي بلا عوض ولا حد — The Bestower of gifts"),
                LearnStep("الرَّزَّاق", "المتكفل بأرزاق العباد كلهم — The Provider for all"),
                LearnStep("الْفَتَّاح", "فاتح أبواب الرحمة والرزق — The Opener of doors and hearts"),
                LearnStep("الْعَلِيم", "المحيط علمه بكل شيء — The All-Knowing"),
                LearnStep("الْقَابِض", "الذي يقبض الرزق والأرواح بحكمته — The Withholder in wisdom"),
                LearnStep("الْبَاسِط", "الذي يبسط الرزق لمن يشاء — The Expander of provision"),
                LearnStep("الْخَافِض", "مذل المتكبرين — The Abaser of the arrogant"),
                LearnStep("الرَّافِع", "رافع أوليائه بالطاعات — The Exalter of the humble"),
                LearnStep("الْمُعِزّ", "معطي العزة لمن يشاء — The Giver of honour"),
                LearnStep("الْمُذِلّ", "مذل من يشاء بعدله — The Humbler of whom He wills"),
                LearnStep("السَّمِيع", "السامع لكل صوت ظاهر وخفي — The All-Hearing"),
                LearnStep("الْبَصِير", "المبصر لكل شيء وإن دق — The All-Seeing"),
                LearnStep("الْحَكَم", "الحاكم بين خلقه بالعدل — The Impartial Judge"),
                LearnStep("الْعَدْل", "الذي لا يظلم مثقال ذرة — The utterly Just"),
                LearnStep("اللَّطِيف", "اللطيف بعباده العالم بدقائق الأمور — The Subtle, the Kind"),
                LearnStep("الْخَبِير", "العالم ببواطن الأشياء — The All-Aware"),
                LearnStep("الْحَلِيم", "الذي لا يعاجل العصاة بالعقوبة — The Most Forbearing"),
                LearnStep("الْعَظِيم", "ذو العظمة والجلال في كل شيء — The Magnificent"),
                LearnStep("الْغَفُور", "الساتر لذنوب عباده التوابين — The Great Forgiver"),
                LearnStep("الشَّكُور", "الذي يجازي على اليسير بالكثير — The Most Appreciative"),
                LearnStep("الْعَلِيّ", "المتعالي فوق كل شيء ذاتًا وقهرًا — The Most High"),
                LearnStep("الْكَبِير", "الكبير في ذاته وصفاته — The Most Great"),
                LearnStep("الْحَفِيظ", "الحافظ لخلقه وأعمالهم — The Preserver"),
                LearnStep("الْمُقِيت", "المقتدر الرزاق — The Sustainer, the Powerful"),
                LearnStep("الْحَسِيب", "الكافي عباده، المحاسب لهم — The Reckoner, the Sufficient"),
                LearnStep("الْجَلِيل", "الموصوف بمعاني الجلال — The Majestic"),
                LearnStep("الْكَرِيم", "العطاء الذي لا ينفد — The Most Generous"),
                LearnStep("الرَّقِيب", "المطالع على أحوال عباده — The Watchful"),
                LearnStep("الْمُجِيب", "الذي يجيب دعاء من دعاه — The Responsive to prayers"),
                LearnStep("الْوَاسِع", "الواسع الرحمة والعلم والملك — The All-Encompassing"),
                LearnStep("الْحَكِيم", "المحكم لخلقه وأمره — The All-Wise"),
                LearnStep("الْوَدُود", "المحب لأوليائه المحبوب لهم — The Most Loving"),
                LearnStep("الْمَجِيد", "الواسع الكرم مع كمال الشرف — The Most Glorious"),
                LearnStep("الْبَاعِث", "باعث الخلق يوم القيامة — The Resurrector"),
                LearnStep("الشَّهِيد", "الحاضر المطالع على كل شيء — The Witness over all"),
                LearnStep("الْحَقّ", "الثابت الذي لا يزول — The Absolute Truth"),
                LearnStep("الْوَكِيل", "المتكفل بأرزاق العباد القائم بمصالحهم — The Trustee, the Disposer of affairs"),
                LearnStep("الْقَوِيّ", "التام القدرة — The All-Strong"),
                LearnStep("الْمَتِين", "الشديد القوة الذي لا تنقطع قوته — The Firm, the Steadfast"),
                LearnStep("الْوَلِيّ", "الناصر لأوليائه المتولي أمورهم — The Protecting Friend"),
                LearnStep("الْحَمِيد", "المحمود على كل حال — The Most Praiseworthy"),
                LearnStep("الْمُحْصِي", "الذي أحصى كل شيء عددًا وعلمًا — The All-Enumerating"),
                LearnStep("الْمُبْدِئ", "الذي بدأ الخلق — The Initiator of creation"),
                LearnStep("الْمُعِيد", "الذي يعيد الخلق بعد الفناء — The Restorer of life"),
                LearnStep("الْمُحْيِي", "الذي يهب الحياة — The Giver of life"),
                LearnStep("الْمُمِيت", "الذي كتب الفناء على خلقه — The Bringer of death"),
                LearnStep("الْحَيّ", "الحي حياة كاملة لا تشبه حياة خلقه — The Ever-Living"),
                LearnStep("الْقَيُّوم", "القائم بنفسه المقيم لغيره — The Self-Subsisting Sustainer"),
                LearnStep("الْوَاجِد", "الغني الذي لا يعوزه شيء — The Self-Sufficient Finder"),
                LearnStep("الْمَاجِد", "الكريم الشريف في أفعاله — The Noble, the Illustrious"),
                LearnStep("الْوَاحِد", "المتفرد بالألوهية المنفرد بكل كمال — الأحد الذي لا شريك له — The One, the Unique with no partner"),
                LearnStep("الصَّمَد", "المقصود في الحوائج السيد الكامل — The Eternal Refuge"),
                LearnStep("الْقَادِر", "التام القدرة على كل شيء — The All-Able"),
                LearnStep("الْمُقْتَدِر", "البالغ في القدرة — The All-Determiner"),
                LearnStep("الْمُقَدِّم", "الذي يقدم من يشاء بفضله — The Promoter"),
                LearnStep("الْمُؤَخِّر", "الذي يؤخر من يشاء بحكمته — The Delayer"),
                LearnStep("الْأَوَّل", "الذي ليس قبله شيء — The First"),
                LearnStep("الْآخِر", "الذي ليس بعده شيء — The Last"),
                LearnStep("الظَّاهِر", "الظاهر بأدلته فوق كل شيء — The Manifest"),
                LearnStep("الْبَاطِن", "العالم بالخفايا القريب — The Hidden, the Inward"),
                LearnStep("الْوَالِي", "المتولي لأمور الخلق — The Sole Governor"),
                LearnStep("الْمُتَعَالِي", "المتنزه عن صفات المخلوقين — The Most Exalted"),
                LearnStep("الْبَرّ", "المحسن إلى خلقه الذي لا ينقطع إحسانه — The Source of all goodness"),
                LearnStep("التَّوَّاب", "الذي يقبل التوبة مرة بعد مرة — The Ever-Pardoning, who accepts repentance"),
                LearnStep("الْمُنْتَقِم", "الذي ينتصف للمظلوم من الظالم — The Avenger"),
                LearnStep("الْعَفُوّ", "الماحي للذنوب بالعفو — The Pardoner who erases sins"),
                LearnStep("الرَّءُوف", "شديد الرحمة والرأفة بعباده — The Most Compassionate"),
                LearnStep("مَالِكُ الْمُلْك", "المتصرف في ملكه كما يشاء — The Owner of all sovereignty"),
                LearnStep("ذُو الْجَلَالِ وَالْإِكْرَام", "المتصف بالجلال والعظمة والكرم — The Lord of Majesty and Generosity"),
                LearnStep("الْمُقْسِط", "العادل في حكمه — The Equitable"),
                LearnStep("الْجَامِع", "جامع الخلق ليوم الحساب — The Gatherer of all"),
                LearnStep("الْغَنِيّ", "الغني عن كل شيء — The Self-Sufficient"),
                LearnStep("الْمُغْنِي", "الذي يغني من يشاء من عباده — The Enricher"),
                LearnStep("الْمَانِع", "الذي يمنع العطاء بحكمته لا بخلًا — The Withholder in wisdom"),
                LearnStep("الضَّارّ", "الذي يقدّر الضرر على من يشاء بحكمته — The Creator of harm by wisdom"),
                LearnStep("النَّافِع", "الذي يوصل النفع لمن يشاء — The Bestower of benefit"),
                LearnStep("النُّور", "الهادي، منور السماوات والأرض — The Light of the heavens and earth"),
                LearnStep("الْهَادِي", "الذي يهدي عباده لمصالحهم — The Guide"),
                LearnStep("الْبَدِيع", "الذي خلق الخلق على غير مثال — The Incomparable Originator"),
                LearnStep("الْبَاقِي", "الدائم الذي لا يفنى — The Everlasting"),
                LearnStep("الْوَارِث", "الباقي بعد فناء الخلق — The Inheritor of all"),
                LearnStep("الرَّشِيد", "المرشد لمصالح الخلق بحكمته — The Guide to the right path"),
                LearnStep("الصَّبُور", "الذي لا يعاجل بالعقوبة عصاته — The Most Patient")
            ),
            notes = "أسماء الله الحسنى التسعة والتسعون الواردة في قول النبي ﷺ: «إن لله تسعةً وتسعين اسمًا، من أحصاها دخل الجنة». المعاني عربية مع ترجمة إنجليزية تقريبية.",
        ),
    )

    fun byId(id: String): LearnTopic? = topics.firstOrNull { it.id == id }
}
