package org.muslim.app.feature.learn.domain

/**
 * The ninety-nine beautiful names of Allah (أسماء الله الحسنى) with a full,
 * detailed, bilingual (Arabic + English) explanation of every name and its
 * evidence from the Quran.
 *
 * Content note (§10): the explanations follow mainstream, widely published
 * summaries (Ibn al-Qayyim, al-Ghazali and standard tafsir works). The
 * verses are quoted in the Uthmani script. Arabic-Indic numerals are never
 * used anywhere in this content — all numbers are Western digits.
 */
data class DivineName(
    val number: Int,
    val arabic: String,
    val transliteration: String,
    val meaningAr: String,
    val meaningEn: String,
    val explanationAr: String,
    val explanationEn: String,
    val evidenceAr: String,
    val evidenceRefAr: String,
    val evidenceEn: String,
    val evidenceRefEn: String,
)

object NamesOfAllahContent {

    val NAMES: List<DivineName> = listOf(
        DivineName(
            1, "اللَّه", "Allah",
            "المعبود بحق الذي تألهه القلوب محبةً وتعظيمًا",
            "The One truly worshipped, whom hearts love and revere",
            "الاسم الأعظم الجامع لمعاني الألوهية كلها؛ هو المعبود بحق الذي تألهه القلوب محبةً وتعظيمًا وخوفًا ورجاء، ولا يستحق العبادة سواه. جميع الأسماء الحسنى ترجع إليه وتدل عليه.",
            "The Greatest Name that gathers all the meanings of divinity. He is the One truly worshipped, whom hearts love, revere, fear and hope in. None deserves worship but Him, and all the beautiful names refer back to Him.",
            "﴿هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ ۖ عَالِمُ الْغَيْبِ وَالشَّهَادَةِ﴾",
            "الحشر 22",
            "He is Allah, other than whom there is no deity, Knower of the unseen and the witnessed.",
            "Al-Hashr 22",
        ),
        DivineName(
            2, "الرَّحْمَٰن", "Ar-Rahman",
            "ذو الرحمة الواسعة التي وسعت كل شيء",
            "The Most Merciful, whose mercy encompasses all things",
            "ذو الرحمة الواسعة التي وسعت كل شيء في الدنيا؛ رحمته العامة تشمل المؤمن والكافر والبر والفاجر، كما قال تعالى: ﴿وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ﴾. من رحمته أن أرسل الرسل وأنزل الكتب.",
            "The One whose vast mercy encompasses everything in this world. His general mercy covers believer and disbeliever alike, as He says: 'My mercy encompasses all things.' From His mercy He sent the messengers and revealed the books.",
            "﴿الرَّحْمَٰنُ عَلَى الْعَرْشِ اسْتَوَىٰ﴾",
            "طه 5",
            "The Most Merciful established Himself above the Throne.",
            "Ta-Ha 5",
        ),
        DivineName(
            3, "الرَّحِيم", "Ar-Raheem",
            "الموصل رحمته الخاصة لمن يشاء من عباده",
            "The Bestower of special mercy upon whom He wills",
            "الموصل رحمته الخاصة لمن يشاء من عباده المؤمنين. فرحمة الله نوعان: رحمة عامة وسعت كل شيء وهي للرَّحمن، ورحمة خاصة بالمؤمنين وهي للرَّحيم، كما قال تعالى: ﴿وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا﴾.",
            "The One who delivers His special mercy to whom He wills of His believing servants. Allah's mercy is of two kinds: a general mercy that encompasses all things (Ar-Rahman), and a special mercy for the believers (Ar-Raheem).",
            "﴿وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا﴾",
            "الأحزاب 43",
            "And He is ever Merciful to the believers.",
            "Al-Ahzab 43",
        ),
        DivineName(
            4, "الْمَلِك", "Al-Malik",
            "المالك المتصرف في ملكه كله تصرفًا مطلقًا",
            "The King, the Owner of all dominion",
            "المالك المتصرف في ملكه كله تصرفًا مطلقًا لا معقب لحكمه؛ له الملك كله في الدنيا والآخرة، وهو ملك يوم الدين الذي لا ينفع فيه ملك ولا سلطان إلا بإذنه.",
            "The King who disposes of His entire dominion with absolute authority; none revokes His judgement. To Him belongs all sovereignty in this world and the next, and He is the Master of the Day of Judgement when no sovereignty avails but by His leave.",
            "﴿مَالِكِ يَوْمِ الدِّينِ﴾",
            "الفاتحة 4",
            "Master of the Day of Judgement.",
            "Al-Fatiha 4",
        ),
        DivineName(
            5, "الْقُدُّوس", "Al-Quddus",
            "المنزه عن كل عيب ونقص",
            "The Most Pure and Holy",
            "المنزه عن كل عيب ونقص وعن كل ما لا يليق بجلاله؛ المقدس عن مشابهة المخلوقين في ذاته وصفاته وأفعاله. تسبحه الملائكة وتقدسه، ويقدسه من في السماوات والأرض.",
            "The One free of every flaw, deficiency and anything unbefitting His majesty; sanctified above resembling His creation in essence, attributes and acts. The angels glorify Him, and all in the heavens and the earth extol His purity.",
            "﴿هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ﴾",
            "الحشر 23",
            "He is Allah, other than whom there is no deity, the Sovereign, the Pure.",
            "Al-Hashr 23",
        ),
        DivineName(
            6, "السَّلَام", "As-Salam",
            "السالم من كل نقص، ومانح السلام لخلقه",
            "The Source of peace and perfection",
            "السالم من كل نقص وعيب وآفة، ومانح السلام والأمان لخلقه؛ إليه ترفع السلامة من كل مخوف، ويسلم العباد من عذابه بإحسانه. تحية أهل الجنة: سلام.",
            "The One free of every imperfection, defect and affliction, and the Giver of peace and safety to His creation. From Him all safety comes, and the greeting of the people of Paradise is 'Peace.'",
            "﴿السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ﴾",
            "الحشر 23",
            "The Peace, the Giver of Security, the Guardian.",
            "Al-Hashr 23",
        ),
        DivineName(
            7, "الْمُؤْمِن", "Al-Mu'min",
            "المصدق لرسله، المؤمِّن لخلقه من الخوف",
            "The Granter of security and faith",
            "الذي صدّق رسله بما آتاهم من الآيات والمعجزات، وأمّن عباده من ظلمه فلا يظلم أحدًا، ويؤمن المؤمنين من الفزع الأكبر يوم القيامة، والمصدق لوعده الحق.",
            "The One who confirms His messengers with signs and miracles, grants His servants security from His injustice, and gives the believers safety from the Greatest Terror on the Day of Judgement. He is the Confirmer of His true promise.",
            "﴿هُوَ الَّذِي أَنزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ لِيَزْدَادُوا إِيمَانًا مَّعَ إِيمَانِهِمْ﴾",
            "الفتح 4",
            "It is He who sent down tranquility into the hearts of the believers to increase them in faith.",
            "Al-Fath 4",
        ),
        DivineName(
            8, "الْمُهَيْمِن", "Al-Muhaymin",
            "الرقيب الحافظ الشاهد على خلقه",
            "The Watchful Guardian over all",
            "الرقيب الحافظ الشاهد على خلقه، المطلع على سرائرهم وظواهرهم، المهيمن على كل شيء بعلمه وقدرته، الحافظ لكتبه ورسله وعباده الصالحين.",
            "The Watchful Guardian who observes His creation, aware of their secrets and their outward affairs, overseeing all things by His knowledge and power, and preserving His books, messengers and righteous servants.",
            "﴿الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ﴾",
            "الحشر 23",
            "The Guardian, the Almighty, the Compeller, the Supreme.",
            "Al-Hashr 23",
        ),
        DivineName(
            9, "الْعَزِيز", "Al-Aziz",
            "القوي الغالب الذي لا يُقهر",
            "The Almighty, the Invincible",
            "القوي الغالب الذي لا يغلب ولا يقهر، العزيز في ملكه وسلطانه، الذي من عزّ به فلا يذل، ومن أعزه الله فلا خاذل له. العزة كلها له: عزة القدرة والقوة والامتناع.",
            "The Almighty who cannot be overcome nor subdued, mighty in His dominion and authority. Whom He honours none can humiliate, and whom He exalts none can abase. All might belongs to Him: the might of power, strength and self-sufficiency.",
            "﴿وَلِلَّهِ الْعِزَّةُ وَلِرَسُولِهِ وَلِلْمُؤْمِنِينَ﴾",
            "المنافقون 8",
            "And to Allah belongs honour, and to His Messenger, and to the believers.",
            "Al-Munafiqun 8",
        ),
        DivineName(
            10, "الْجَبَّار", "Al-Jabbar",
            "القاهر لخلقه، جابر كل كسير",
            "The Compeller who mends and subdues",
            "الجابر لكل كسير، والمصلح لكل شأن، والقاهر لخلقه على ما أراد، الغني المتعالي عن حاجة خلقه. جبروته عظمة وقدرة لا ظلم؛ وهو الذي يجبر قلوب الخائفين والمكسورين.",
            "The One who mends every broken heart and sets right every affair, subduing His creation to His will, and self-sufficient above their need. His omnipotence is majesty and power, not oppression — He mends the hearts of the fearful and the broken.",
            "﴿الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ ۚ سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ﴾",
            "الحشر 23",
            "The Almighty, the Compeller, the Supreme. Exalted is Allah above what they associate with Him.",
            "Al-Hashr 23",
        ),
        DivineName(
            11, "الْمُتَكَبِّر", "Al-Mutakabbir",
            "المتعالي عن صفات الخلق",
            "The Supreme in greatness",
            "المتعالي عن صفات الخلق وعن كل نقص، المتكبر بعظمته وكبريائه الذي لا يليق التكبر إلا به؛ فالتكبر صفة مدح لله وذمّ لغيره، ومن تكبر على خلقه أذله الله.",
            "The One exalted above the attributes of creation and above all deficiency. Greatness and pride belong only to Him — pride is praise for Allah but blameworthy in others; whoever acts arrogantly toward creation, Allah humiliates him.",
            "﴿الْجَبَّارُ الْمُتَكَبِّرُ ۚ سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ﴾",
            "الحشر 23",
            "The Compeller, the Supreme. Exalted is Allah above what they associate with Him.",
            "Al-Hashr 23",
        ),
        DivineName(
            12, "الْخَالِق", "Al-Khaliq",
            "الموجد للأشياء من غير مثال سابق",
            "The Creator of all things",
            "الموجد للأشياء من العدم على غير مثال سابق، خالق كل شيء بقدرته ومشيئته، الذي خلق السماوات والأرض وما بينهما في أحسن تقويم، وخلق الخلق لعبادته.",
            "The One who brings things into existence from nothing without a prior example, creating everything by His power and will. He created the heavens and the earth and all between them in the best form, and created creation to worship Him.",
            "﴿هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ ۖ لَهُ الْأَسْمَاءُ الْحُسْنَىٰ﴾",
            "الحشر 24",
            "He is Allah, the Creator, the Originator, the Fashioner — to Him belong the best names.",
            "Al-Hashr 24",
        ),
        DivineName(
            13, "الْبَارِئ", "Al-Bari'",
            "المنشئ للخلق بريئًا من التفاوت",
            "The Originator who creates flawlessly",
            "المنشئ للخلق من العدم، المبرئ للمخلوقات من التفاوت والتناقض، الذي برأ النفوس على الفطرة، وخلق كل شيء فسواه فعدله، بارئ السماوات والأرض بقدرته.",
            "The Originator who brings creation forth from nothing, producing creatures free of disproportion and contradiction. He created souls upon the fitrah and created everything, giving it due proportion — the Originator of the heavens and the earth by His power.",
            "﴿الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ﴾",
            "الحشر 24",
            "The Creator, the Originator, the Fashioner.",
            "Al-Hashr 24",
        ),
        DivineName(
            14, "الْمُصَوِّر", "Al-Musawwir",
            "الذي صوّر المخلوقات وأحسن صورها",
            "The Fashioner of forms",
            "الذي صوّر المخلوقات وصوّر كل ذي روح في أحسن صورة، وصوّر لكم الصور فأحسنها، وأتقن كل شيء صنعه، فصورته سبحانه لا تشبه صور الخلائق.",
            "The One who fashioned every creature and shaped every soul in the finest form. He formed you and perfected your forms, perfecting everything He makes — and His forming is unlike the forming of His creatures.",
            "﴿هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ ۖ لَهُ الْأَسْمَاءُ الْحُسْنَىٰ﴾",
            "الحشر 24",
            "He is Allah, the Creator, the Originator, the Fashioner — to Him belong the best names.",
            "Al-Hashr 24",
        ),
        DivineName(
            15, "الْغَفَّار", "Al-Ghaffar",
            "الذي يغفر الذنوب مهما تكررت",
            "The Ever-Forgiving",
            "الذي يغفر الذنوب مهما عظمت وتكررت، ويستر العيوب، ويقبل التوبة من عباده التائبين؛ غفرانه متكرر دائم، يغفر الخطايا والذنوب والزلات، ولا ييأس العبد من رحمته.",
            "The One who forgives sins however great and repeated, veils faults and accepts the repentance of His servants. His forgiveness is continual and repeated — He pardons sins, faults and slips, and the servant never despairs of His mercy.",
            "﴿اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا﴾",
            "نوح 10",
            "Seek forgiveness of your Lord; indeed He is ever a Perpetual Forgiver.",
            "Nuh 10",
        ),
        DivineName(
            16, "الْقَهَّار", "Al-Qahhar",
            "الغالب لكل شيء",
            "The All-Dominant",
            "الغالب القاهر لكل شيء، الذي قهر الجبابرة والطغاة، وخضعت له الرقاب وذلت له الوجوه، وقهر كل مخلوق بقدرته، فلا يخرج شيء عن مشيئته ولا يتعاظم عليه شيء.",
            "The One who prevails over and subdues everything. He conquered the tyrants, necks bow and faces humble before Him, and every creature is subdued by His power — nothing escapes His will and nothing is too great for Him.",
            "﴿وَهُوَ الْوَاحِدُ الْقَهَّارُ﴾",
            "الرعد 16",
            "And He is the One, the Prevailing.",
            "Ar-Ra'd 16",
        ),
        DivineName(
            17, "الْوَهَّاب", "Al-Wahhab",
            "المعطي بلا عوض ولا حد",
            "The Bestower of gifts",
            "المعطي بلا عوض ولا حد، الواهب للذرية والرزق والعلم والحكمة، العطاء الكثير المتوالي الذي لا ينقطع؛ يهب لمن يشاء ما يشاء، وكل عطاء منه ابتداء لا استحقاقًا.",
            "The One who gives without compensation or limit — granting children, provision, knowledge and wisdom with abundant, continuous giving that never ends. He bestows on whom He wills, and every gift from Him is a beginning, not a repayment.",
            "﴿إِنَّكَ أَنتَ الْوَهَّابُ﴾",
            "آل عمران 8",
            "Indeed, You are the Bestower.",
            "Aal-Imran 8",
        ),
        DivineName(
            18, "الرَّزَّاق", "Ar-Razzaq",
            "المتكفل بأرزاق العباد كلهم",
            "The Provider for all creation",
            "المتكفل بأرزاق العباد كلهم، الذي خلقهم ورزقهم، لا ينسى أحدًا ولا ينسى رزقه؛ يرزق الجنين في بطن أمه والطير في جو السماء والحوت في قاع البحر، وهو الرزاق ذو القوة المتين.",
            "The One who guarantees the provision of all His servants, having created them and provided for them, forgetting no one and no one's sustenance. He provides for the embryo in its mother's womb, the bird in the sky and the fish in the deep — the Provider, the Firm Possessor of strength.",
            "﴿إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ﴾",
            "الذاريات 58",
            "Indeed, it is Allah who is the Provider, the Firm Possessor of strength.",
            "Adh-Dhariyat 58",
        ),
        DivineName(
            19, "الْفَتَّاح", "Al-Fattah",
            "فاتح أبواب الرحمة والرزق والهداية",
            "The Opener of doors and hearts",
            "فاتح أبواب الرحمة والرزق والهداية، الحاكم بين عباده بالحق، يفتح ما أغلق من الأمور، ويفتح قلوب عباده لفهم الحق، وما يفتح الله من رحمة فلا ممسك لها.",
            "The One who opens the gates of mercy, provision and guidance, judging between His servants with truth and unlocking what is closed. He opens the hearts of His servants to understanding, and whatever mercy Allah opens for people, none can withhold.",
            "﴿وَهُوَ الْفَتَّاحُ الْعَلِيمُ﴾",
            "سبأ 26",
            "And He is the Opener, the Knowing.",
            "Saba 26",
        ),
        DivineName(
            20, "الْعَلِيم", "Al-'Aleem",
            "المحيط علمه بكل شيء",
            "The All-Knowing",
            "المحيط علمه بكل شيء ظاهرًا وباطنًا دقيقًا وجليلًا، لا يعزب عنه مثقال ذرة في السماوات ولا في الأرض، يعلم السر وأخفى، ويعلم ما كان وما يكون وما لم يكن لو كان كيف يكون.",
            "The One whose knowledge encompasses everything, outward and inward, subtle and grand. Not even an atom's weight escapes Him in the heavens or the earth. He knows the secret and what is more hidden, and knows what was, what will be, and what never was.",
            "﴿وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ﴾",
            "البقرة 29",
            "And He is Knowing of all things.",
            "Al-Baqarah 29",
        ),
        DivineName(
            21, "الْقَابِض", "Al-Qabid",
            "الذي يقبض الرزق والأرواح بحكمته",
            "The Withholder in wisdom",
            "الذي يقبض الرزق عمن يشاء بحكمته وعدله، ويقبض الأرواح عند آجالها، ويقبض القلوب بين أصبعيه؛ يقبض ويبسط كما يشاء، وفي قبضه حكمة بالغة.",
            "The One who withholds provision from whom He wills by His wisdom and justice, takes souls at their appointed times, and holds hearts between His fingers. He withholds and He expands as He wills, and in His withholding is profound wisdom.",
            "﴿وَاللَّهُ يَقْبِضُ وَيَبْسُطُ ۖ وَإِلَيْهِ تُرْجَعُونَ﴾",
            "البقرة 245",
            "And Allah withholds and grants abundantly, and to Him you will be returned.",
            "Al-Baqarah 245",
        ),
        DivineName(
            22, "الْبَاسِط", "Al-Basit",
            "الذي يبسط الرزق لمن يشاء",
            "The Expander of provision",
            "الذي يبسط الرزق والرحمة والمعرفة لمن يشاء، يبسط يديه بالعطاء، ويوسع على عباده في أرزاقهم، وبسطه كقبضه بحكمة وعلم.",
            "The One who expands provision, mercy and knowledge for whom He wills, spreading forth His hand with giving and widening His servants' sustenance. His expansion, like His withholding, is by wisdom and knowledge.",
            "﴿وَاللَّهُ يَقْبِضُ وَيَبْسُطُ ۖ وَإِلَيْهِ تُرْجَعُونَ﴾",
            "البقرة 245",
            "And Allah withholds and grants abundantly, and to Him you will be returned.",
            "Al-Baqarah 245",
        ),
        DivineName(
            23, "الْخَافِض", "Al-Khafid",
            "مذل المتكبرين",
            "The Abaser of the arrogant",
            "الذي يخفض الجبابرة والمتكبرين ويذلهم، ويخفض درجات من يستحق الخفض بعدله، ويرفع أولياءه ويخفض أعداءه؛ ومن يهن الله فما له من مكرم.",
            "The One who lowers and humiliates the tyrants and the arrogant, lowering the ranks of those who deserve it by His justice, while exalting His allies. Whoever Allah humiliates — there is none to honour him.",
            "﴿وَمَن يُهِنِ اللَّهُ فَمَا لَهُ مِن مُّكْرِمٍ ۚ إِنَّ اللَّهَ يَفْعَلُ مَا يَشَاءُ﴾",
            "الحج 18",
            "And whoever Allah humiliates — for him there is no one to honour. Indeed, Allah does what He wills.",
            "Al-Hajj 18",
        ),
        DivineName(
            24, "الرَّافِع", "Ar-Rafi'",
            "رافع أوليائه بالطاعات",
            "The Exalter of the humble",
            "الرافع لأوليائه بالطاعات والدرجات، رافع السماء فوق الأرض، رافع عباده المؤمنين في الدنيا والآخرة، ويرفع درجات من يشاء من عباده الصالحين.",
            "The One who raises His allies through obedience and degrees, raised the heavens above the earth, and exalts His believing servants in this world and the next, raising the ranks of whom He wills among His righteous servants.",
            "﴿رَفِيعُ الدَّرَجَاتِ ذُو الْعَرْشِ﴾",
            "غافر 15",
            "Exalted in degrees, Owner of the Throne.",
            "Ghafir 15",
        ),
        DivineName(
            25, "الْمُعِزّ", "Al-Mu'izz",
            "معطي العزة لمن يشاء",
            "The Giver of honour",
            "معطي العزة لمن يشاء من عباده، يعز أولياءه وينصرهم، ويعز المؤمنين بالطاعة، «قل اللهم مالك الملك تؤتي الملك من تشاء وتنزع الملك ممن تشاء وتعز من تشاء وتذل من تشاء».",
            "The One who grants honour to whom He wills of His servants, honouring His allies and granting them victory, and exalting the believers through obedience — 'You give honour to whom You will and humiliate whom You will.'",
            "﴿تُعِزُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ﴾",
            "آل عمران 26",
            "You give honour to whom You will and humiliate whom You will; in Your hand is all good.",
            "Aal-Imran 26",
        ),
        DivineName(
            26, "الْمُذِلّ", "Al-Mudhill",
            "مذل من يشاء بعدله",
            "The Humbler of whom He wills",
            "مذل من يشاء بعدله، يذل الجبابرة والمستكبرين ويضعهم، ويذل من عصاه وخالف أمره؛ فالعزة لله جميعًا، يمنحها من شاء ويسلبها ممن شاء.",
            "The One who humbles whom He wills in justice, debasing the tyrants and the arrogant and lowering those who disobey Him. All might belongs to Allah — He grants it to whom He wills and takes it from whom He wills.",
            "﴿وَتُذِلُّ مَن تَشَاءُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ﴾",
            "آل عمران 26",
            "And You humiliate whom You will; indeed You are over all things competent.",
            "Aal-Imran 26",
        ),
        DivineName(
            27, "السَّمِيع", "As-Sami'",
            "السامع لكل صوت ظاهر وخفي",
            "The All-Hearing",
            "السامع لكل الأصوات ظاهرها وخفيها، لا يخفى عليه شيء، يسمع الدعاء والمناجاة والنجوى، ويسمع شكوى عباده وحاجاتهم؛ سمعه محيط بكل مسموع.",
            "The One who hears every voice, apparent and hidden — nothing escapes Him. He hears supplication, whispered prayer and secret counsel, and hears the complaints and needs of His servants; His hearing encompasses all that is heard.",
            "﴿إِنَّ اللَّهَ سَمِيعٌ بَصِيرٌ﴾",
            "لقمان 28",
            "Indeed, Allah is Hearing and Seeing.",
            "Luqman 28",
        ),
        DivineName(
            28, "الْبَصِير", "Al-Baseer",
            "المبصر لكل شيء وإن دق",
            "The All-Seeing",
            "المبصر لكل شيء وإن دق ولطف، يرى دبيب النملة السوداء على الصخرة الصماء في الليلة الظلماء، ويرى ما تحت الأرضين السبع وما فوق السماوات؛ بصره محيط بكل مبصر.",
            "The One who sees everything however fine and subtle — He sees the black ant crawling on a solid rock in the darkest night, and sees what is beneath the seven earths and above the heavens. His sight encompasses all that is seen.",
            "﴿إِنَّ اللَّهَ سَمِيعٌ بَصِيرٌ﴾",
            "لقمان 28",
            "Indeed, Allah is Hearing and Seeing.",
            "Luqman 28",
        ),
        DivineName(
            29, "الْحَكَم", "Al-Hakam",
            "الحاكم بين خلقه بالعدل",
            "The Impartial Judge",
            "الحاكم بين خلقه بالعدل في الدنيا والآخرة، لا معقب لحكمه ولا راد لقضائه، أحكم الحاكمين وأعدلهم، يحكم بالحق ويفصل في الخصومات، وإليه التحاكم في كل نازلة.",
            "The Judge who arbitrates between His creation with justice in this world and the next. None revokes His judgement and none repels His decree — He is the wisest and most just of judges, deciding in truth and settling disputes.",
            "﴿أَفَغَيْرَ اللَّهِ أَبْتَغِي حَكَمًا وَهُوَ الَّذِي أَنزَلَ إِلَيْكُمُ الْكِتَابَ مُفَصَّلًا﴾",
            "الأنعام 114",
            "Then is it other than Allah I should seek as judge while it is He who has revealed to you the Book explained in detail?",
            "Al-An'am 114",
        ),
        DivineName(
            30, "الْعَدْل", "Al-'Adl",
            "الذي لا يظلم مثقال ذرة",
            "The utterly Just",
            "العادل في حكمه وقضائه، الذي لا يظلم مثقال ذرة، ويضع الأمور في مواضعها، ولا يجور في قضائه؛ عدله سبحانه عدل مطلق لا يشوبه ظلم، وقد أنصف المظلوم من الظالم.",
            "The Just in His judgement and decree, who wrongs no one by even an atom's weight and places everything in its proper place. His justice is absolute, unmixed with any injustice — He grants the oppressed their right from the oppressor.",
            "﴿تَمَّتْ كَلِمَتُ رَبِّكَ صِدْقًا وَعَدْلًا ۚ لَّا مُبَدِّلَ لِكَلِمَاتِهِ﴾",
            "الأنعام 115",
            "The word of your Lord has been fulfilled in truth and justice; none can alter His words.",
            "Al-An'am 115",
        ),
        DivineName(
            31, "اللَّطِيف", "Al-Lateef",
            "اللطيف بعباده العالم بدقائق الأمور",
            "The Subtle, the Kind",
            "اللطيف بعباده، الذي يرفق بهم ويلطف بهم من حيث لا يحتسبون، ويوصل إليهم الخير والرزق من طرق خفية، والعالم بدقائق الأمور وخباياها؛ لطفه بخلقه لا يدركه وصف.",
            "The Subtle and Kind to His servants, gentle with them in ways they do not perceive, delivering good and provision to them through hidden paths, and knowing the finest secrets of affairs. His kindness to His creation defies description.",
            "﴿اللَّهُ لَطِيفٌ بِعِبَادِهِ يَرْزُقُ مَن يَشَاءُ ۖ وَهُوَ الْقَوِيُّ الْعَزِيزُ﴾",
            "الشورى 19",
            "Allah is Subtle with His servants; He provides for whom He wills, and He is the Powerful, the Almighty.",
            "Ash-Shura 19",
        ),
        DivineName(
            32, "الْخَبِير", "Al-Khabeer",
            "العالم ببواطن الأشياء",
            "The All-Aware",
            "العالم ببواطن الأشياء وأسرارها، المطلع على خفايا القلوب وما تخفي الصدور، الخبير بما كان وما سيكون، لا تخفى عليه خافية في الأرض ولا في السماء.",
            "The One aware of the inward realities and secrets of things, acquainted with the hidden recesses of hearts and what the breasts conceal. He knows what was and what will be — nothing is hidden from Him in the earth or the heavens.",
            "﴿وَهُوَ اللَّطِيفُ الْخَبِيرُ﴾",
            "الملك 14",
            "And He is the Subtle, the Aware.",
            "Al-Mulk 14",
        ),
        DivineName(
            33, "الْحَلِيم", "Al-Haleem",
            "الذي لا يعاجل العصاة بالعقوبة",
            "The Most Forbearing",
            "الذي لا يعاجل العصاة بالعقوبة، يمهل ولا يهمل، ويستر ويتجاوز، حليم لا يستفزه شيء ولا يستعجله؛ حلمه يسبق غضبه، ومن حلمه أن رزق العاصي كما يرزق المطيع.",
            "The One who does not hasten punishment upon the disobedient; He gives respite without neglect, veils and pardons. Nothing provokes Him or hurries Him — His forbearance precedes His anger, and from His forbearance He provides for the disobedient as He provides for the obedient.",
            "﴿وَاللَّهُ غَفُورٌ حَلِيمٌ﴾",
            "البقرة 225",
            "And Allah is Forgiving and Forbearing.",
            "Al-Baqarah 225",
        ),
        DivineName(
            34, "الْعَظِيم", "Al-'Azeem",
            "ذو العظمة والجلال في كل شيء",
            "The Magnificent",
            "ذو العظمة والجلال في ذاته وصفاته وأفعاله، عظمته لا يدركها وصف ولا يبلغها فكر، وتعاظم عن كل شيء، وعظمة الله أكبر من كل شيء، فلا شيء أعظم منه.",
            "The One of grandeur and majesty in His essence, attributes and acts. His greatness defies description and exceeds all thought; He is magnified above everything, and nothing is greater than Him.",
            "﴿وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
            "البقرة 255",
            "And He is the Most High, the Most Great.",
            "Al-Baqarah 255",
        ),
        DivineName(
            35, "الْغَفُور", "Al-Ghafoor",
            "الساتر لذنوب عباده التوابين",
            "The Great Forgiver",
            "الساتر لذنوب عباده، كثير المغفرة واسعها، يغفر الذنب العظيم ويتجاوز عن الزلل، ويستر العيوب في الدنيا والآخرة؛ مغفرته تشمل كل ذنب إذا تاب العبد واستغفر.",
            "The One who veils His servants' sins, vast and abundant in pardon. He forgives the great sin and overlooks the slip, veiling faults in this world and the next. His forgiveness covers every sin when the servant repents and seeks forgiveness.",
            "﴿وَإِنَّ اللَّهَ لَغَفُورٌ رَّحِيمٌ﴾",
            "البقرة 173",
            "And indeed, Allah is Forgiving and Merciful.",
            "Al-Baqarah 173",
        ),
        DivineName(
            36, "الشَّكُور", "Ash-Shakoor",
            "الذي يجازي على اليسير بالكثير",
            "The Most Appreciative",
            "الذي يجازي على القليل بالكثير، ويشكر اليسير من العمل فيجازيه بالكثير من الثواب، شاكر لعباده على طاعتهم، ويزيد الشاكرين شكرًا ونعمة.",
            "The One who rewards the little with much and acknowledges even small deeds with abundant recompense. He is Appreciative of His servants' obedience and increases the grateful in gratitude and blessings.",
            "﴿إِنَّ رَبَّنَا لَغَفُورٌ شَكُورٌ﴾",
            "فاطر 34",
            "Indeed, our Lord is Forgiving and Appreciative.",
            "Fatir 34",
        ),
        DivineName(
            37, "الْعَلِيّ", "Al-'Aliyy",
            "المتعالي فوق كل شيء ذاتًا وقهرًا",
            "The Most High",
            "المتعالي فوق كل شيء ذاتًا وقدرًا وقهرًا، العالي الذي لا أعلى منه، علا على العرش واستوى، وعلا على كل شيء بقدرته، وعلا شأنه عن أن يدركه وصف.",
            "The Most High, exalted above all things in essence, rank and dominion. He rose over the Throne, prevails over everything by His power, and His station is too lofty for any description to grasp.",
            "﴿وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
            "البقرة 255",
            "And He is the Most High, the Most Great.",
            "Al-Baqarah 255",
        ),
        DivineName(
            38, "الْكَبِير", "Al-Kabeer",
            "الكبير في ذاته وصفاته",
            "The Most Great",
            "الكبير في ذاته وصفاته، الذي لا أكبر منه، كل شيء دونه في الكبرياء والعظمة، كبير في أسمائه وصفاته وأفعاله، ولا يبلغ كبرياءه وصف.",
            "The Most Great in His essence and attributes — nothing is greater than Him. Everything is lesser than Him in majesty and grandeur; He is great in His names, attributes and acts, beyond all description of His grandeur.",
            "﴿وَهُوَ الْكَبِيرُ الْمُتَعَالِ﴾",
            "الرعد 9",
            "And He is the Most Great, the Most Exalted.",
            "Ar-Ra'd 9",
        ),
        DivineName(
            39, "الْحَفِيظ", "Al-Hafeez",
            "الحافظ لخلقه وأعمالهم",
            "The Preserver",
            "الحافظ لخلقه ولأعمالهم وأقوالهم، الحافظ للسماوات والأرض، يحفظ عبده من الشرور والآفات، ويحفظ كتابه من التحريف، والحفظ منه نوعان: حفظ بحفظ الأعمال، وحفظ بحفظ من الآفات.",
            "The Preserver of His creation, their deeds and their words; He preserves the heavens and the earth, protects His servant from harms and afflictions, and guards His Book from distortion. His preservation is of two kinds: preserving deeds and preserving from harm.",
            "﴿إِنَّ رَبِّي عَلَىٰ كُلِّ شَيْءٍ حَفِيظٌ﴾",
            "هود 57",
            "Indeed, my Lord is, over all things, a Preserver.",
            "Hud 57",
        ),
        DivineName(
            40, "الْمُقِيت", "Al-Muqeet",
            "المقتدر الرزاق الحاضر لكل شيء",
            "The Sustainer, the Powerful",
            "المقتدر على كل شيء، الممد للأقوات، الحاضر لكل شيء المشاهد له، وهو الحفيظ الشهيد؛ يقيت الخلائق أرزاقهم وأقواتهم، فلا يضيع عنده شيء.",
            "The All-Powerful over everything, the Nourisher who supplies sustenance, present over all things and witnessing them — the Preserver and Witness. He supplies His creatures their provisions, and nothing is lost with Him.",
            "﴿وَكَانَ اللَّهُ عَلَىٰ كُلِّ شَيْءٍ مُّقِيتًا﴾",
            "النساء 85",
            "And Allah is, over all things, an Overseer.",
            "An-Nisa 85",
        ),
        DivineName(
            41, "الْحَسِيب", "Al-Haseeb",
            "الكافي عباده، المحاسب لهم",
            "The Reckoner, the Sufficient",
            "الكافي عباده، المحاسب لهم على أعمالهم، يجزي بالخير خيرًا وبالشر شرًا، وكفى به حسيبًا، وحسبنا الله ونعم الوكيل؛ من توكل عليه كفاه، ومن استند إليه حسبه.",
            "The One who suffices His servants and reckons their deeds, rewarding good with good and evil with evil. Sufficient is Allah as a Reckoner; whoever relies on Him, He suffices him.",
            "﴿وَكَفَىٰ بِاللَّهِ حَسِيبًا﴾",
            "النساء 6",
            "And sufficient is Allah as a Reckoner.",
            "An-Nisa 6",
        ),
        DivineName(
            42, "الْجَلِيل", "Al-Jaleel",
            "الموصوف بمعاني الجلال",
            "The Majestic",
            "الموصوف بمعاني الجلال والعظمة، صاحب الكبرياء والعظمة المطلقة، الجليل الذي يجلّه كل شيء، وتعظمه القلوب وتخشاه النفوس.",
            "The One described with all meanings of grandeur and glory, the Owner of absolute majesty and might. Everything venerates Him; hearts revere Him and souls fear Him.",
            "﴿وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ﴾",
            "الرحمن 27",
            "And there remains the Face of your Lord, Owner of Majesty and Honour.",
            "Ar-Rahman 27",
        ),
        DivineName(
            43, "الْكَرِيم", "Al-Kareem",
            "الجواد العطاء الذي لا ينفد",
            "The Most Generous",
            "الجواد العطاء الذي لا ينفد عطاؤه، الكريم الذي يعطي ويسخو، وكرمه لا يحده حد، الكريم الذي تجاوز عن المسيء وأعطى السائل، ومن كرمه أن يغفر مع قدرته على العقوبة.",
            "The Most Generous whose giving never runs out, who gives abundantly and liberally — His generosity has no limit. He overlooks the wrongdoer and gives the asker, and from His generosity He forgives despite His power to punish.",
            "﴿إِنَّ رَبِّي غَنِيٌّ كَرِيمٌ﴾",
            "النمل 40",
            "Indeed, my Lord is Self-Sufficient, Generous.",
            "An-Naml 40",
        ),
        DivineName(
            44, "الرَّقِيب", "Ar-Raqeeb",
            "المطالع على أحوال عباده",
            "The Watchful",
            "المطالع على أحوال عباده، الحافظ لأعمالهم وأقوالهم، الرقيب الذي لا يغيب عنه شيء، يرقب حركات العباد وسكناتهم، وهو معهم بعلمه ورقابته أينما كانوا.",
            "The One who watches over His servants' conditions and preserves their deeds and words. Nothing is hidden from the Watchful — He observes the movements and stillness of His servants and is with them by His knowledge wherever they are.",
            "﴿إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا﴾",
            "النساء 1",
            "Indeed, Allah is ever, over you, a Watcher.",
            "An-Nisa 1",
        ),
        DivineName(
            45, "الْمُجِيب", "Al-Mujeeb",
            "الذي يجيب دعاء من دعاه",
            "The Responsive to prayers",
            "الذي يجيب دعاء من دعاه، ويقضي حاجة من سأله، قريب مجيب لعباده، لا يخيب سائلًا ولا يرد داعيًا، يجيب المضطر إذا دعاه ويكشف السوء.",
            "The One who answers the supplication of those who call upon Him and fulfils the needs of those who ask. He is near and answering — He never disappoints a petitioner nor turns away a caller, answering the distressed when he calls and removing harm.",
            "﴿إِنِّي قَرِيبٌ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ﴾",
            "البقرة 186",
            "I am near; I answer the call of the caller when he calls upon Me.",
            "Al-Baqarah 186",
        ),
        DivineName(
            46, "الْوَاسِع", "Al-Wasi'",
            "الواسع الرحمة والعلم والملك",
            "The All-Encompassing",
            "الواسع الرحمة والعلم والملك والعطاء، لا تضيق رحمته عن شيء، ولا يعجزه شيء، وسعت رحمته كل شيء، ووسع كل شيء رحمة وعلمًا.",
            "The All-Encompassing in mercy, knowledge, dominion and giving. His mercy is not constrained by anything, nothing frustrates Him, and His mercy and knowledge encompass everything.",
            "﴿وَاللَّهُ وَاسِعٌ عَلِيمٌ﴾",
            "البقرة 115",
            "And Allah is All-Encompassing and Knowing.",
            "Al-Baqarah 115",
        ),
        DivineName(
            47, "الْحَكِيم", "Al-Hakeem",
            "المحكم لخلقه وأمره",
            "The All-Wise",
            "المحكم لخلقه وأمره، الحكيم في أفعاله وأقواله وشرعه، يضع الأشياء في مواضعها، ويعطي كل شيء خلقه ثم هدى، ولا يفعل إلا لحكمة بالغة.",
            "The One who perfects His creation and command, wise in His acts, words and law, placing everything in its proper place. He gave everything its form and then guided it, and does nothing except with profound wisdom.",
            "﴿وَهُوَ الْعَزِيزُ الْحَكِيمُ﴾",
            "إبراهيم 4",
            "And He is the Almighty, the Wise.",
            "Ibrahim 4",
        ),
        DivineName(
            48, "الْوَدُود", "Al-Wadood",
            "المحب لأوليائه المحبوب لهم",
            "The Most Loving",
            "المحب لأوليائه، المحبوب في قلوب عباده، الذي يود عباده ويحبهم ويحبونه، ويغفر للمحسن والمسيء؛ ومن ودّه الله أحبه وأحبته قلوب العباد.",
            "The Most Loving, who loves His allies and is beloved in the hearts of His servants. He loves them and they love Him, forgiving the good-doer and the wrongdoer; whom Allah loves, He loves, and the hearts of the servants come to love him.",
            "﴿وَهُوَ الْغَفُورُ الْوَدُودُ﴾",
            "البروج 14",
            "And He is the Forgiving, the Loving.",
            "Al-Buruj 14",
        ),
        DivineName(
            49, "الْمَجِيد", "Al-Majeed",
            "الواسع الكرم مع كمال الشرف",
            "The Most Glorious",
            "الواسع الكرم مع كمال الشرف والعلو، صاحب المجد الذي لا يبلغه أحد، المجيد في ذاته وصفاته وأفعاله، الكريم الشريف الذي يجلّ عن كل نقص.",
            "The Most Glorious, vast in generosity with perfect nobility and loftiness — of a glory none can attain. Glorious in His essence, attributes and acts, noble and honoured, exalted above every deficiency.",
            "﴿إِنَّهُ حَمِيدٌ مَّجِيدٌ﴾",
            "هود 73",
            "Indeed, He is Praiseworthy, Glorious.",
            "Hud 73",
        ),
        DivineName(
            50, "الْبَاعِث", "Al-Ba'ith",
            "باعث الخلق يوم القيامة",
            "The Resurrector",
            "الذي يبعث الخلق من قبورهم يوم القيامة للحساب، وباعث الرسل إلى خلقه، وباعث الهمم إلى العمل؛ هو الذي يحيي الموتى ويخرجهم من الأجداث.",
            "The One who raises creation from their graves on the Day of Judgement for reckoning, sent the messengers to His creation, and stirs determination to action. It is He who revives the dead and brings them forth from the graves.",
            "﴿وَأَنَّ اللَّهَ يَبْعَثُ مَن فِي الْقُبُورِ﴾",
            "الحج 7",
            "And that Allah will resurrect those in the graves.",
            "Al-Hajj 7",
        ),
        DivineName(
            51, "الشَّهِيد", "Ash-Shaheed",
            "الحاضر المطالع على كل شيء",
            "The Witness over all",
            "الحاضر المطالع على كل شيء، الشاهد على أعمال عباده، لا يغيب عنه شيء ولا يخفى عليه، يشهد على العباد يوم القيامة بأعمالهم، وهو على كل شيء شهيد.",
            "The Witness present over all things, observing His servants' deeds. Nothing is absent from Him and nothing is hidden — He will bear witness to His servants' deeds on the Day of Judgement, and He is over all things a Witness.",
            "﴿وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ شَهِيدٌ﴾",
            "المجادلة 6",
            "And Allah is, over all things, a Witness.",
            "Al-Mujadila 6",
        ),
        DivineName(
            52, "الْحَقّ", "Al-Haqq",
            "الثابت الذي لا يزول",
            "The Absolute Truth",
            "الثابت الذي لا يزول، الذي حق وجوده وصدق وعده، وكل ما سواه باطل، فالله هو الحق، وعبادتهم من دونه باطل، ووعده حق ولقاؤه حق.",
            "The Absolute Truth, the Real whose existence is certain and whose promise is true. Everything besides Him is false — Allah is the Truth, worship of anything other than Him is false, and His promise and meeting are true.",
            "﴿ذَٰلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ وَأَنَّ مَا يَدْعُونَ مِن دُونِهِ هُوَ الْبَاطِلُ﴾",
            "الحج 62",
            "That is because Allah is the Truth, and that which they call upon other than Him is falsehood.",
            "Al-Hajj 62",
        ),
        DivineName(
            53, "الْوَكِيل", "Al-Wakeel",
            "المتكفل بأرزاق العباد القائم بمصالحهم",
            "The Trustee, the Disposer of affairs",
            "المتكفل بأمور عباده، القائم بمصالحهم، الكافي من توكل عليه، وحسبنا الله ونعم الوكيل؛ من فوض أمره إليه كفاه، ومن استند إليه لم يضعه.",
            "The One who undertakes His servants' affairs and manages their interests, sufficient for whoever relies on Him. 'Allah is sufficient for us, and He is the best Disposer.' Whoever entrusts his affair to Him is sufficed, and whoever leans on Him is never forsaken.",
            "﴿وَكَفَىٰ بِاللَّهِ وَكِيلًا﴾",
            "النساء 81",
            "And sufficient is Allah as Disposer of affairs.",
            "An-Nisa 81",
        ),
        DivineName(
            54, "الْقَوِيّ", "Al-Qawiyy",
            "التام القدرة",
            "The All-Strong",
            "التام القدرة، الذي لا يعجزه شيء، القوي الذي لا يضعف ولا يعتريه عجز ولا فتور، قوته لا تنتهي، وقدرته نافذة في كل شيء.",
            "The All-Strong, perfect in power, whom nothing can frustrate. He is strong, never weak, never struck by incapacity or fatigue; His strength never ends and His power prevails over everything.",
            "﴿إِنَّ اللَّهَ هُوَ الْقَوِيُّ الْعَزِيزُ﴾",
            "الحج 40",
            "Indeed, Allah is the Powerful, the Almighty.",
            "Al-Hajj 40",
        ),
        DivineName(
            55, "الْمَتِين", "Al-Mateen",
            "الشديد القوة الذي لا تنقطع قوته",
            "The Firm, the Steadfast",
            "الشديد القوة الذي لا تنقطع قوته ولا توهن، المتين الذي لا يلحقه في قدرته عجز، قوته متينة شديدة، وهو الرزاق ذو القوة المتين.",
            "The Firm and Steadfast whose strength never lapses nor weakens — mighty in power, never failing. His strength is firm and severe, and He is the Provider, the Firm Possessor of strength.",
            "﴿إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ﴾",
            "الذاريات 58",
            "Indeed, it is Allah who is the Provider, the Firm Possessor of strength.",
            "Adh-Dhariyat 58",
        ),
        DivineName(
            56, "الْوَلِيّ", "Al-Waliyy",
            "الناصر لأوليائه المتولي أمورهم",
            "The Protecting Friend",
            "الناصر لأوليائه، المتولي أمور عباده الصالحين، يتولى المؤمنين فيخرجهم من الظلمات إلى النور، وهو ولي الذين آمنوا ونصيرهم، والمتكفل بحفظهم ورعايتهم.",
            "The Protecting Friend who supports His allies and manages the affairs of His righteous servants. He takes charge of the believers, bringing them out of darkness into light — the Ally and Helper of those who believe, entrusted with their protection and care.",
            "﴿اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا يُخْرِجُهُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ﴾",
            "البقرة 257",
            "Allah is the Ally of those who believe; He brings them out from darknesses into the light.",
            "Al-Baqarah 257",
        ),
        DivineName(
            57, "الْحَمِيد", "Al-Hameed",
            "المحمود على كل حال",
            "The Most Praiseworthy",
            "المحمود على كل حال، المستحق للحمد بذاته وصفاته وأفعاله، المحمود في السماء والأرض، حمدته الخلائق كلها، وكل نعمة منه فله الحمد عليها.",
            "The Most Praiseworthy in every state, deserving of praise for His essence, attributes and acts. He is praised in the heavens and the earth — all creation praises Him, and every blessing from Him is deserving of His praise.",
            "﴿فَإِنَّ اللَّهَ غَنِيٌّ حَمِيدٌ﴾",
            "لقمان 12",
            "Then indeed, Allah is Self-Sufficient and Praiseworthy.",
            "Luqman 12",
        ),
        DivineName(
            58, "الْمُحْصِي", "Al-Muhsi",
            "الذي أحصى كل شيء عددًا وعلمًا",
            "The All-Enumerating",
            "الذي أحصى كل شيء عددًا وعلمًا، لا يفوته من أعمال العباد شيء صغير ولا كبير، وأحصى أنفاسهم وخطواتهم وأعمالهم، وهو على كل شيء محصٍ.",
            "The One who has enumerated all things in number and knowledge. Nothing of His servants' deeds escapes Him, small or great — He counts their breaths, steps and deeds, and is over all things an Enumerator.",
            "﴿وَأَحْصَىٰ كُلَّ شَيْءٍ عَدَدًا﴾",
            "الجن 28",
            "And He has enumerated all things in number.",
            "Al-Jinn 28",
        ),
        DivineName(
            59, "الْمُبْدِئ", "Al-Mubdi'",
            "الذي بدأ الخلق",
            "The Initiator of creation",
            "الذي بدأ الخلق من غير سابق مثال، ابتدأ الأشياء من العدم إلى الوجود، وأبدع السماوات والأرض، وابتدأ خلق الإنسان من طين.",
            "The One who began creation without a prior example, bringing things from nothing into existence. He originated the heavens and the earth and began the creation of man from clay.",
            "﴿إِنَّهُ هُوَ يُبْدِئُ وَيُعِيدُ﴾",
            "البروج 13",
            "Indeed, He is the One who originates and repeats.",
            "Al-Buruj 13",
        ),
        DivineName(
            60, "الْمُعِيد", "Al-Mu'eed",
            "الذي يعيد الخلق بعد الفناء",
            "The Restorer of life",
            "الذي يعيد الخلق بعد فنائهم كما بدأهم أول مرة، إعادته أهون عليه من ابتدائهم، يعيدهم يوم القيامة أحياءً للحساب، وإعادة كل شيء عليه يسيرة.",
            "The One who restores creation after their perishing just as He began them — His repetition is easier for Him than their beginning. He returns them alive on the Day of Judgement for reckoning, and restoring everything is easy for Him.",
            "﴿إِنَّهُ هُوَ يُبْدِئُ وَيُعِيدُ﴾",
            "البروج 13",
            "Indeed, He is the One who originates and repeats.",
            "Al-Buruj 13",
        ),
        DivineName(
            61, "الْمُحْيِي", "Al-Muhyi",
            "الذي يهب الحياة",
            "The Giver of life",
            "الذي يهب الحياة لكل حي، يحيي النطف والرمم، ويحيي القلوب بالإيمان، ويحيي الأرض بعد موتها بالمطر؛ بيده الحياة كلها، يحيي من يشاء من خلقه.",
            "The One who grants life to every living thing, reviving sperm and decayed bones, enlivening hearts with faith and the earth after its death with rain. All life is in His hand; He gives life to whom He wills.",
            "﴿وَهُوَ الَّذِي يُحْيِي وَيُمِيتُ وَلَهُ اخْتِلَافُ اللَّيْلِ وَالنَّهَارِ﴾",
            "المؤمنون 80",
            "And He is the One who gives life and causes death, and His is the alternation of night and day.",
            "Al-Mu'minun 80",
        ),
        DivineName(
            62, "الْمُمِيت", "Al-Mumeet",
            "الذي كتب الفناء على خلقه",
            "The Bringer of death",
            "الذي كتب الموت على خلقه، يميت الأحياء إذا شاء، والموت بيده وحده، لا يملكه أحد سواه؛ وكل نفس ذائقة الموت، وإليه ترجع الأمور.",
            "The One who has written death upon His creation and causes the living to die as He wills. Death is in His hand alone — no one else controls it; every soul shall taste death, and to Him all matters return.",
            "﴿وَهُوَ الَّذِي يُحْيِي وَيُمِيتُ﴾",
            "يونس 56",
            "And He is the One who gives life and causes death.",
            "Yunus 56",
        ),
        DivineName(
            63, "الْحَيّ", "Al-Hayy",
            "الحي حياة كاملة لا تشبه حياة خلقه",
            "The Ever-Living",
            "الحي حياة كاملة لا أول لها ولا آخر، لا يلحقه نوم ولا موت، حياة لا تشبه حياة خلقه، حي بنفسه لا يحتاج إلى من يحييه، والخلق كلهم يموتون وهو حي لا يموت.",
            "The Ever-Living with a complete life without beginning or end, whom neither slumber nor death overtakes — a life unlike that of His creation. He is alive by Himself, needing none to give Him life; all creation dies while He lives and never dies.",
            "﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ﴾",
            "البقرة 255",
            "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence; neither slumber nor sleep overtakes Him.",
            "Al-Baqarah 255",
        ),
        DivineName(
            64, "الْقَيُّوم", "Al-Qayyoom",
            "القائم بنفسه المقيم لغيره",
            "The Self-Subsisting Sustainer",
            "القائم بنفسه المقيم لغيره، الذي قامت به السماوات والأرض، وبه قوام كل شيء، وهو القائم على كل نفس بما كسبت، لا يقوم شيء إلا به.",
            "The Self-Subsisting who stands by Himself and sustains all else. By Him the heavens and the earth stand, and by Him everything subsists. He is the One who stands over every soul for what it has earned — nothing stands except by Him.",
            "﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ﴾",
            "البقرة 255",
            "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence.",
            "Al-Baqarah 255",
        ),
        DivineName(
            65, "الْوَاجِد", "Al-Wajid",
            "الغني الذي لا يعوزه شيء",
            "The Self-Sufficient Finder",
            "الغني الذي لا يعوزه شيء، الواجد لكل ما يريد لا يفوته مطلوب، لا يفقد شيئًا ولا يعجزه شيء، وكل شيء عنده محصى، وهو الذي وجدك فهداك.",
            "The Self-Sufficient Finder who wants nothing and finds everything He wills — no desire escapes Him. He loses nothing and nothing frustrates Him; everything is enumerated with Him, and He is the One who found you and guided you.",
            "﴿وَوَجَدَكَ ضَالًّا فَهَدَىٰ﴾",
            "الضحى 7",
            "And He found you lost and guided you.",
            "Ad-Duha 7",
        ),
        DivineName(
            66, "الْمَاجِد", "Al-Majid",
            "الكريم الشريف في أفعاله",
            "The Noble, the Illustrious",
            "الكريم الشريف في أفعاله، صاحب المجد والعظمة والإكرام، الماجد الذي يجلّ عن كل نقص، ومن مجده أن له العرش المجيد.",
            "The Noble and Illustrious in His acts, the Owner of glory, grandeur and honour. He is exalted above every deficiency, and from His glory He owns the Glorious Throne.",
            "﴿ذُو الْعَرْشِ الْمَجِيدُ﴾",
            "البروج 15",
            "Owner of the Glorious Throne.",
            "Al-Buruj 15",
        ),
        DivineName(
            67, "الْوَاحِد", "Al-Wahid",
            "المتفرد بالألوهية المنفرد بكل كمال",
            "The One, the Unique",
            "المتفرد بالألوهية والربوبية، الواحد الذي لا شريك له في ذاته وصفاته وأفعاله، الأحد الذي لا نظير له، وإلهكم إله واحد لا إله إلا هو.",
            "The One, unique in divinity and lordship, without partner in His essence, attributes and acts — the Unique with no equal. Your God is one God; there is no deity but Him.",
            "﴿وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ ۖ لَّا إِلَٰهَ إِلَّا هُوَ الرَّحْمَٰنُ الرَّحِيمُ﴾",
            "البقرة 163",
            "And your God is one God; there is no deity except Him, the Most Merciful, the Most Compassionate.",
            "Al-Baqarah 163",
        ),
        DivineName(
            68, "الصَّمَد", "As-Samad",
            "المقصود في الحوائج السيد الكامل",
            "The Eternal Refuge",
            "المقصود في الحوائج، السيد الكامل الذي يصمد إليه الخلق في قضاء حوائجهم، لا يقضيها غيره، وليس له ولد ولا والد ولا كفؤ؛ يصمد إليه كل شيء ويفتقر إليه كل شيء.",
            "The Eternal Refuge sought in every need, the Perfect Master to whom all creation turns to fulfil their needs, which none but He fulfils. He has no child, no parent and no equal; everything turns to Him and everything is in need of Him.",
            "﴿اللَّهُ الصَّمَدُ﴾",
            "الإخلاص 2",
            "Allah, the Eternal Refuge.",
            "Al-Ikhlas 2",
        ),
        DivineName(
            69, "الْقَادِر", "Al-Qadir",
            "التام القدرة على كل شيء",
            "The All-Able",
            "التام القدرة على كل شيء، القادر على الإحياء والإماتة والبعث، لا يعجزه شيء في السماوات ولا في الأرض، وهو على كل شيء قدير.",
            "The All-Able, perfect in power over everything — able to give life, cause death and resurrect. Nothing in the heavens or the earth frustrates Him, and He is over all things competent.",
            "﴿أَوَلَيْسَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِقَادِرٍ عَلَىٰ أَن يَخْلُقَ مِثْلَهُم ۚ بَلَىٰ وَهُوَ الْخَلَّاقُ الْعَلِيمُ﴾",
            "يس 81",
            "Is not He who created the heavens and the earth Able to create the likes of them? Yes, and He is the Knowing Creator.",
            "Ya-Sin 81",
        ),
        DivineName(
            70, "الْمُقْتَدِر", "Al-Muqtadir",
            "البالغ في القدرة",
            "The All-Determiner",
            "البالغ في القدرة، الذي لا يمتنع عليه شيء، القدرة الكاملة النافذة، يقدر على ما يشاء، وعنده مليك مقتدر، وإذا أراد شيئًا فإنما يقول له كن فيكون.",
            "The All-Determiner, utmost in power, from whom nothing is withheld — complete and effective power. He is able to do what He wills; when He intends a thing, He says to it 'Be,' and it is.",
            "﴿عِندَ مَلِيكٍ مُّقْتَدِرٍ﴾",
            "القمر 55",
            "In the seat of honour with a Mighty King.",
            "Al-Qamar 55",
        ),
        DivineName(
            71, "الْمُقَدِّم", "Al-Muqaddim",
            "الذي يقدم من يشاء بفضله",
            "The Promoter",
            "الذي يقدم من يشاء من خلقه بفضله، يقدم الأشياء في مواضعها بحكمته، يقدم من أطاعه ويرفع درجاته، والآجال والأرزاق والسعادة عنده مقدم ومؤخر.",
            "The One who advances whom He wills by His grace, placing things in their proper order by His wisdom. He advances those who obey Him and raises their ranks, and with Him terms, provisions and fortunes are advanced and delayed.",
            "﴿يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ﴾",
            "المجادلة 11",
            "Allah will raise those who have believed among you and those who were given knowledge, by degrees.",
            "Al-Mujadila 11",
        ),
        DivineName(
            72, "الْمُؤَخِّر", "Al-Mu'akhkhir",
            "الذي يؤخر من يشاء بحكمته",
            "The Delayer",
            "الذي يؤخر من يشاء بحكمته، يؤخر الأشياء إلى آجالها المقدورة، ويؤخر العصاة فلا يعاجلهم بالعقوبة، ولا يؤخر شيئًا عن وقته إذا جاء أجله.",
            "The One who defers whom He wills by His wisdom, postponing things to their appointed times. He delays the disobedient without hastening punishment, yet delays nothing past its time when its term arrives.",
            "﴿وَلَوْ يُؤَاخِذُ اللَّهُ النَّاسَ بِظُلْمِهِم مَّا تَرَكَ عَلَيْهَا مِن دَابَّةٍ وَلَٰكِن يُؤَخِّرُهُمْ إِلَىٰ أَجَلٍ مُّسَمًّى﴾",
            "النحل 61",
            "If Allah were to seize people for their wrongdoing, He would not leave upon it a single creature, but He defers them for a specified term.",
            "An-Nahl 61",
        ),
        DivineName(
            73, "الْأَوَّل", "Al-Awwal",
            "الذي ليس قبله شيء",
            "The First",
            "الذي ليس قبله شيء، الأول بلا بداية، الأزلي القدم، موجود قبل كل شيء، وكل ما سواه مخلوق بعد أن لم يكن.",
            "The First — nothing is before Him. He is without beginning, pre-eternal, existing before everything; all else was created after having not been.",
            "﴿هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ﴾",
            "الحديد 3",
            "He is the First and the Last, the Manifest and the Hidden, and He is Knowing of all things.",
            "Al-Hadid 3",
        ),
        DivineName(
            74, "الْآخِر", "Al-Akhir",
            "الذي ليس بعده شيء",
            "The Last",
            "الذي ليس بعده شيء، الباقي بعد فناء كل شيء، الآخر الذي لا نهاية لوجوده، وكل شيء هالك إلا وجهه.",
            "The Last — nothing is after Him. He remains after all things perish; His existence has no end, and everything is perishing except His Face.",
            "﴿هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ﴾",
            "الحديد 3",
            "He is the First and the Last, the Manifest and the Hidden, and He is Knowing of all things.",
            "Al-Hadid 3",
        ),
        DivineName(
            75, "الظَّاهِر", "Adh-Dhahir",
            "الظاهر بأدلته فوق كل شيء",
            "The Manifest",
            "الظاهر بأدلته وآياته فوق كل شيء، الذي ظهر بالأدلة العقلية والشرعية، وظهرت آياته في الآفاق والأنفس، وهو فوق كل شيء علوًا وقهرًا.",
            "The Manifest, above all things in His proofs and signs, evident through rational and revealed evidence. His signs appear in the horizons and within yourselves, and He is above everything in height and dominion.",
            "﴿هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ﴾",
            "الحديد 3",
            "He is the First and the Last, the Manifest and the Hidden, and He is Knowing of all things.",
            "Al-Hadid 3",
        ),
        DivineName(
            76, "الْبَاطِن", "Al-Batin",
            "العالم بالخفايا القريب",
            "The Hidden, the Inward",
            "القريب العالم بالخفايا، الباطن عن إدراك الأبصار، الذي لا يخفى عليه شيء، باطن في علمه ببواطن الأمور، قريب من عباده بعلمه وإحاطته.",
            "The Hidden, near and knowing of all secrets, beyond the perception of eyes, from whom nothing is concealed. Inward in His knowledge of the hidden realities, and near to His servants by His knowledge and encompassing awareness.",
            "﴿هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ﴾",
            "الحديد 3",
            "He is the First and the Last, the Manifest and the Hidden, and He is Knowing of all things.",
            "Al-Hadid 3",
        ),
        DivineName(
            77, "الْوَالِي", "Al-Wali",
            "المتولي لأمور الخلق",
            "The Sole Governor",
            "المتولي أمور الخلق والتصرف فيها، الولي الحقيقي الذي يرعى كل شيء، ويدبر الأمور كلها، لا والي غيره، ومن والاه نجا ومن عاداه هلك.",
            "The One who manages and directs the affairs of creation — the true Governor who cares for everything and disposes of all matters. There is no governor besides Him; whoever allies with Him is saved, and whoever opposes Him perishes.",
            "﴿وَمَا لَهُم مِّن دُونِهِ مِن وَالٍ ۖ يُشْرِكُ فِي حُكْمِهِ أَحَدًا﴾",
            "الكهف 26",
            "And they have no protector besides Him, and He shares His rule with no one.",
            "Al-Kahf 26",
        ),
        DivineName(
            78, "الْمُتَعَالِي", "Al-Muta'ali",
            "المتنزه عن صفات المخلوقين",
            "The Most Exalted",
            "المتنزه عن صفات المخلوقين، المتعالي عن كل عيب ونقص، العالي فوق خلقه، تعالى عن أن يدركه وصف أو يبلغه فكر، وهو الكبير المتعال.",
            "The Most Exalted, free of the attributes of creatures and of every flaw, high above His creation. He is exalted beyond any description grasping Him or any thought reaching Him — the Most Great, the Most Exalted.",
            "﴿وَهُوَ الْكَبِيرُ الْمُتَعَالِ﴾",
            "الرعد 9",
            "And He is the Most Great, the Most Exalted.",
            "Ar-Ra'd 9",
        ),
        DivineName(
            79, "الْبَرّ", "Al-Barr",
            "المحسن إلى خلقه الذي لا ينقطع إحسانه",
            "The Source of all goodness",
            "المحسن إلى خلقه، الذي لا ينقطع إحسانه، البر بمن أطاعه وبمن عصاه، يوصل الخير والإحسان إلى خلقه، وهو البر الرحيم، وبِرّه لا يحده حد.",
            "The Source of all goodness whose kindness to His creation never ceases — good to those who obey Him and those who disobey. He delivers goodness and kindness to His creation; He is the Righteous, the Merciful, and His goodness has no limit.",
            "﴿إِنَّهُ هُوَ الْبَرُّ الرَّحِيمُ﴾",
            "الطور 28",
            "Indeed, He is the Righteous, the Merciful.",
            "At-Tur 28",
        ),
        DivineName(
            80, "التَّوَّاب", "At-Tawwab",
            "الذي يقبل التوبة مرة بعد مرة",
            "The Ever-Pardoning, who accepts repentance",
            "الذي يقبل التوبة مرة بعد مرة، يفتح بابها لعباده كل وقت، ويفرح بتوبة عبده، ويبدل سيئات التائب حسنات، وهو تواب رحيم.",
            "The One who accepts repentance time after time, keeping its door open for His servants at all times and rejoicing in their return. He turns the sins of the repentant into good deeds — the Acceptor of repentance, the Merciful.",
            "﴿إِنَّ اللَّهَ تَوَّابٌ رَّحِيمٌ﴾",
            "الحجرات 12",
            "Indeed, Allah is Accepting of repentance and Merciful.",
            "Al-Hujurat 12",
        ),
        DivineName(
            81, "الْمُنْتَقِم", "Al-Muntaqim",
            "الذي ينتصف للمظلوم من الظالم",
            "The Avenger",
            "الذي ينتقم من الظالمين والمعاندين بعد الإعذار والإنذار، عدل لا ظلم فيه، ينتقم من المجرمين في الدنيا والآخرة، وينتقم لأوليائه من أعدائهم.",
            "The One who takes retribution from the oppressors and the obstinate after warning them — a justice with no injustice. He avenges the criminals in this world and the next, and takes vengeance for His allies against their enemies.",
            "﴿إِنَّا مِنَ الْمُجْرِمِينَ مُنتَقِمُونَ﴾",
            "السجدة 22",
            "Indeed, We will take retribution from the criminals.",
            "As-Sajdah 22",
        ),
        DivineName(
            82, "الْعَفُوّ", "Al-'Afuww",
            "الماحي للذنوب بالعفو",
            "The Pardoner who erases sins",
            "الماحي للذنوب وآثارها، العفو الذي يعفو عن الذنوب العظام فلا يعاقب عليها، والعفو أبلغ من المغفرة؛ لأنه محو الذنب مع إزالة أثره.",
            "The One who erases sins and their traces, pardoning even the greatest offences without punishment. Pardon is greater than forgiveness, for it wipes out the sin along with its effect.",
            "﴿إِنَّ اللَّهَ كَانَ عَفُوًّا غَفُورًا﴾",
            "النساء 99",
            "Indeed, Allah is ever Pardoning and Forgiving.",
            "An-Nisa 99",
        ),
        DivineName(
            83, "الرَّءُوف", "Ar-Ra'uf",
            "شديد الرحمة والرأفة بعباده",
            "The Most Compassionate",
            "شديد الرحمة والرأفة بعباده، الذي يجمع لعباده الرحمة مع العطف والإحسان، ورأفته أبلغ من الرحمة، يرفق بعباده الضعفاء ويرأف بهم.",
            "The Most Compassionate, who combines mercy with tenderness and kindness toward His servants. His compassion is deeper than mercy — He is gentle with His weak servants and has compassion on them.",
            "﴿إِنَّ اللَّهَ بِالنَّاسِ لَرَءُوفٌ رَّحِيمٌ﴾",
            "البقرة 143",
            "Indeed, Allah is to the people Kind and Merciful.",
            "Al-Baqarah 143",
        ),
        DivineName(
            84, "مَالِكُ الْمُلْك", "Malik-ul-Mulk",
            "المتصرف في ملكه كما يشاء",
            "The Owner of all sovereignty",
            "المتصرف في الملك كله كما يشاء، يؤتي الملك من يشاء وينزعه ممن يشاء، ويعز من يشاء ويذل من يشاء، وبيده الخير كله، وهو على كل شيء قدير.",
            "The One who disposes of the entire dominion as He wills, granting kingship to whom He wills and taking it from whom He wills. He honours whom He wills and humiliates whom He wills; all good is in His hand, and He is over all things competent.",
            "﴿قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَن تَشَاءُ وَتَنزِعُ الْمُلْكَ مِمَّن تَشَاءُ﴾",
            "آل عمران 26",
            "Say: O Allah, Owner of Sovereignty, You give sovereignty to whom You will and take sovereignty away from whom You will.",
            "Aal-Imran 26",
        ),
        DivineName(
            85, "ذُو الْجَلَالِ وَالْإِكْرَام", "Dhul-Jalali wal-Ikram",
            "المتصف بالجلال والعظمة والكرم",
            "The Lord of Majesty and Generosity",
            "المتصف بالجلال والعظمة والكرم، أهل لأن يجل ويعظم ويوقر ويكرم، ذو الجلال الذي يجل عن كل نقص، والإكرام الذي يكرم أولياءه ويكرم أهل طاعته.",
            "The One described with majesty, grandeur and generosity, worthy of glorification, veneration and honour. Owner of Majesty, exalted above every deficiency, and of Generosity, honouring His allies and those who obey Him.",
            "﴿تَبَارَكَ اسْمُ رَبِّكَ ذِي الْجَلَالِ وَالْإِكْرَامِ﴾",
            "الرحمن 78",
            "Blessed is the name of your Lord, Owner of Majesty and Honour.",
            "Ar-Rahman 78",
        ),
        DivineName(
            86, "الْمُقْسِط", "Al-Muqsit",
            "العادل في حكمه",
            "The Equitable",
            "العادل في حكمه وقضائه، الذي يقسط في الرزق بين خلقه، يعدل فلا يجور، ويرزق كل مخلوق قسطه، وهو يحب المقسطين.",
            "The Equitable, just in His judgement and decree, fair in providing for His creation. He deals justly and never wrongs, providing every creature its share, and He loves those who act equitably.",
            "﴿وَأَقْسِطُوا ۖ إِنَّ اللَّهَ يُحِبُّ الْمُقْسِطِينَ﴾",
            "الحجرات 9",
            "And be equitable; indeed, Allah loves the equitable.",
            "Al-Hujurat 9",
        ),
        DivineName(
            87, "الْجَامِع", "Al-Jami'",
            "جامع الخلق ليوم الحساب",
            "The Gatherer of all",
            "جامع الخلق ليوم لا ريب فيه للحساب، جامع المتفرق، وجامع القلوب على الهدى، وجامع الأولين والآخرين في صعيد واحد يوم القيامة.",
            "The Gatherer who brings creation together on a Day without doubt for reckoning, gathering the scattered and uniting hearts upon guidance, and gathering the first and the last upon one plain on the Day of Judgement.",
            "﴿رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ﴾",
            "آل عمران 9",
            "Our Lord, You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.",
            "Aal-Imran 9",
        ),
        DivineName(
            88, "الْغَنِيّ", "Al-Ghaniyy",
            "الغني عن كل شيء",
            "The Self-Sufficient",
            "الغني عن كل شيء، الذي لا يحتاج إلى أحد، وكل خلقه فقراء إليه، غني بذاته عن خلقه، وهم الفقراء إليه في كل شيء، والله الغني وأنتم الفقراء.",
            "The Self-Sufficient who needs no one, while all His creation stands in need of Him. He is rich by His essence, independent of His creation, while they are poor before Him in everything — Allah is the Free of need, and you are the needy.",
            "﴿وَاللَّهُ الْغَنِيُّ وَأَنتُمُ الْفُقَرَاءُ﴾",
            "محمد 38",
            "And Allah is the Free of need, while you are the needy.",
            "Muhammad 38",
        ),
        DivineName(
            89, "الْمُغْنِي", "Al-Mughni",
            "الذي يغني من يشاء من عباده",
            "The Enricher",
            "الذي يغني من يشاء من عباده، أغنى وأقنى، يغني الفقير ويرزقه، ويجعل الغنى في القلوب بالقناعة، وهو الذي أغنى العباد وأرضاهم.",
            "The One who enriches whom He wills of His servants — He enriched and contented, enriching the poor and providing for them, and placing richness in hearts through contentment.",
            "﴿وَأَنَّهُ هُوَ أَغْنَىٰ وَأَقْنَىٰ﴾",
            "النجم 48",
            "And that it is He who enriches and contents.",
            "An-Najm 48",
        ),
        DivineName(
            90, "الْمَانِع", "Al-Mani'",
            "الذي يمنع العطاء بحكمته لا بخلًا",
            "The Withholder in wisdom",
            "الذي يمنع العطاء بحكمته لا بخلًا، يمنع عن العبد ما يضره، ويمنع البلايا والفتن، وما يمسك من رحمة فلا مرسل له بعده؛ ومانعه عين حكمته.",
            "The One who withholds by wisdom, not stinginess — preventing what harms His servant and warding off calamities and trials. Whatever mercy He withholds, none can release it after Him; His withholding is itself His wisdom.",
            "﴿مَّا يَفْتَحِ اللَّهُ لِلنَّاسِ مِن رَّحْمَةٍ فَلَا مُمْسِكَ لَهَا ۖ وَمَا يُمْسِكْ فَلَا مُرْسِلَ لَهُ مِن بَعْدِهِ﴾",
            "فاطر 2",
            "Whatever Allah opens for people of mercy — none can withhold it; and whatever He withholds — none can release it after Him.",
            "Fatir 2",
        ),
        DivineName(
            91, "الضَّارّ", "Ad-Darr",
            "الذي يقدّر الضرر على من يشاء بحكمته",
            "The Creator of harm by wisdom",
            "الذي يقدّر الضرر على من يشاء بحكمته وعدله، كل شيء بقضائه وقدره، لا ضار ولا نافع إلا هو، والضرر الذي يقدّره عين الحكمة والعدل.",
            "The One who ordains harm upon whom He wills by His wisdom and justice. Everything is by His decree and measure; none harms or benefits but Him, and the harm He ordains is itself wisdom and justice.",
            "﴿وَإِن يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ ۖ وَإِن يُرِدْكَ بِخَيْرٍ فَلَا رَادَّ لِفَضْلِهِ﴾",
            "يونس 107",
            "And if Allah touches you with harm, none can remove it but Him; and if He intends good for you, none can repel His bounty.",
            "Yunus 107",
        ),
        DivineName(
            92, "النَّافِع", "An-Nafi'",
            "الذي يوصل النفع لمن يشاء",
            "The Bestower of benefit",
            "الذي يوصل النفع لمن يشاء، بيده الخير كله، لا نافع إلا هو، وإذا أراد العبد نفعًا فليطلب من الله، فالنفع كله من عنده وحده.",
            "The One who conveys benefit to whom He wills. All good is in His hand — none benefits but Him. If a servant desires benefit, let him seek it from Allah, for all benefit comes from Him alone.",
            "﴿وَإِن يُرِدْكَ بِخَيْرٍ فَلَا رَادَّ لِفَضْلِهِ ۚ يُصِيبُ بِهِ مَن يَشَاءُ مِنْ عِبَادِهِ﴾",
            "يونس 107",
            "And if He intends good for you, none can repel His bounty; He causes it to reach whom He wills of His servants.",
            "Yunus 107",
        ),
        DivineName(
            93, "النُّور", "An-Nur",
            "الهادي، منور السماوات والأرض",
            "The Light of the heavens and earth",
            "الهادي لمن يشاء، منور السماوات والأرض بالحق، نوره الذي يهدي به عباده، وهو النور الذي لا نور إلا هو، والقرآن نور وهدى من عنده.",
            "The Light who guides whom He wills, illuminating the heavens and the earth with truth. He is the Light by which He guides His servants — the Light with no light besides Him, and the Quran is light and guidance from Him.",
            "﴿اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ﴾",
            "النور 35",
            "Allah is the Light of the heavens and the earth.",
            "An-Nur 35",
        ),
        DivineName(
            94, "الْهَادِي", "Al-Hadi",
            "الذي يهدي عباده لمصالحهم",
            "The Guide",
            "الذي يهدي عباده لمصالحهم، ويهدي القلوب إلى معرفته وطاعته، هدى الخلق إلى ما فيه صلاحهم، ومن يهد الله فهو المهتدي، ومن يضلل فلن تجد له وليًا مرشدًا.",
            "The One who directs His servants to their interests and guides hearts to knowing and obeying Him. He guided creation to what is good for them; whom Allah guides is rightly guided, and whom He lets stray has no guide.",
            "﴿إِنَّكَ لَا تَهْدِي مَنْ أَحْبَبْتَ وَلَٰكِنَّ اللَّهَ يَهْدِي مَن يَشَاءُ ۚ وَهُوَ أَعْلَمُ بِالْمُهْتَدِينَ﴾",
            "القصص 56",
            "You cannot guide whom you love, but Allah guides whom He wills, and He is most knowing of the rightly guided.",
            "Al-Qasas 56",
        ),
        DivineName(
            95, "الْبَدِيع", "Al-Badee'",
            "الذي خلق الخلق على غير مثال",
            "The Incomparable Originator",
            "الذي خلق الخلق على غير مثال سابق، المبدع للأشياء بلا نظير، بديع السماوات والأرض، أبدعها من غير شيء يحتذي به، وأبدع كل صنع.",
            "The One who created creation without a prior example, originating things with no precedent. Originator of the heavens and the earth, He brought them forth from nothing to imitate, and originated every craft.",
            "﴿بَدِيعُ السَّمَاوَاتِ وَالْأَرْضِ ۖ وَإِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُن فَيَكُونُ﴾",
            "البقرة 117",
            "Originator of the heavens and the earth. When He decrees a matter, He only says to it, 'Be,' and it is.",
            "Al-Baqarah 117",
        ),
        DivineName(
            96, "الْبَاقِي", "Al-Baqi",
            "الدائم الذي لا يفنى",
            "The Everlasting",
            "الدائم الذي لا يفنى، الباقي بعد فناء كل شيء، لا يلحقه عدم ولا فناء، وكل شيء هالك إلا وجهه، وكل من عليها فان ويبقى وجه ربك.",
            "The Everlasting who never perishes, remaining after all things cease. Non-existence never touches Him, everything is perishing except His Face, and all upon the earth passes away while His Face remains.",
            "﴿وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ﴾",
            "الرحمن 27",
            "And there remains the Face of your Lord, Owner of Majesty and Honour.",
            "Ar-Rahman 27",
        ),
        DivineName(
            97, "الْوَارِث", "Al-Warith",
            "الباقي بعد فناء الخلق",
            "The Inheritor of all",
            "الباقي بعد فناء الخلق، يرث الأرض ومن عليها، وهو خير الوارثين، وإنا لنحن نرث الأرض ومن عليها وإلينا يرجعون.",
            "The One who remains after creation perishes, inheriting the earth and all upon it — the Best of inheritors. 'Indeed, We will inherit the earth and whoever is upon it, and to Us they will be returned.'",
            "﴿إِنَّا نَحْنُ نَرِثُ الْأَرْضَ وَمَنْ عَلَيْهَا وَإِلَيْنَا يُرْجَعُونَ﴾",
            "مريم 40",
            "Indeed, We will inherit the earth and whoever is upon it, and to Us they will be returned.",
            "Maryam 40",
        ),
        DivineName(
            98, "الرَّشِيد", "Ar-Rasheed",
            "المرشد لمصالح الخلق بحكمته",
            "The Guide to the right path",
            "المرشد لمصالح الخلق بحكمته، الرشيد في تدبيره وأفعاله، الذي لا يخرج عن حكمته شيء، ويرشد عباده إلى ما فيه صلاح دينهم ودنياهم.",
            "The Guide to right conduct, directing creation to their interests by His wisdom — prudent in His management and acts. Nothing departs from His wisdom, and He guides His servants to what benefits their religion and world.",
            "﴿وَمَن يُضْلِلِ اللَّهُ فَمَا لَهُ مِنْ هَادٍ﴾",
            "الزمر 23",
            "And whoever Allah lets stray — for him there is no guide.",
            "Az-Zumar 23",
        ),
        DivineName(
            99, "الصَّبُور", "As-Saboor",
            "الذي لا يعاجل بالعقوبة عصاته",
            "The Most Patient",
            "الذي لا يعاجل العصاة بالعقوبة، الصبور الذي يمهل ولا يهمل، ويؤخر العقوبة عن مستحقها إمهالًا ورحمة، حتى إذا جاء الأجل لم يؤخر.",
            "The Most Patient who does not hasten punishment upon the disobedient, giving respite without neglect. He delays punishment from those who deserve it out of forbearance and mercy, until the appointed time comes and nothing is delayed.",
            "﴿وَلَوْ يُؤَاخِذُ اللَّهُ النَّاسَ بِمَا كَسَبُوا مَا تَرَكَ عَلَىٰ ظَهْرِهَا مِن دَابَّةٍ وَلَٰكِن يُؤَخِّرُهُمْ إِلَىٰ أَجَلٍ مُّسَمًّى﴾",
            "فاطر 45",
            "If Allah were to seize people for what they earned, He would not leave upon its back a single creature, but He defers them for a specified term.",
            "Fatir 45",
        ),
    )

    fun byNumber(number: Int): DivineName? = NAMES.firstOrNull { it.number == number }
}
