package org.muslim.app.feature.hadith.domain

/**
 * Arabic display labels for bundled source chapter keys. Source keys remain unchanged
 * for Room chapter queries, Paging, stable list keys, and migration safety. Generated
 * by scripts/generate_hadith_chapter_title_localization.py; it contains no Hadith text.
 */
internal object HadithChapterArabicTitles {
    private val byCollectionAndSource: Map<String, String> = mapOf(
        "abudawud|Battles (Kitab Al-Malahim)" to "كتاب الملاحم",
        "abudawud|Clothing (Kitab Al-Libas)" to "كتاب اللباس",
        "abudawud|Combing the Hair (Kitab Al-Tarajjul)" to "كتاب الترجّل",
        "abudawud|Commercial Transactions (Kitab Al-Buyu)" to "كتاب البيو",
        "abudawud|Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)" to "كتاب الحروف والقراءات",
        "abudawud|Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)" to "كتاب الكهنة والتطير",
        "abudawud|Divorce (Kitab Al-Talaq)" to "كتاب الطلاق",
        "abudawud|Drinks (Kitab Al-Ashribah)" to "كتاب الأشربة",
        "abudawud|Fasting (Kitab Al-Siyam)" to "كتاب الصيام",
        "abudawud|Foods (Kitab Al-At'imah)" to "كتاب الأطعمة",
        "abudawud|Funerals (Kitab Al-Jana'iz)" to "كتاب الجنائز",
        "abudawud|Game (Kitab Al-Said)" to "كتاب الصيد",
        "abudawud|General Behavior (Kitab Al-Adab)" to "كتاب الآداب",
        "abudawud|Hot Baths (Kitab Al-Hammam)" to "كتاب الهمام",
        "abudawud|Jihad (Kitab Al-Jihad)" to "كتاب الجهاد",
        "abudawud|Knowledge (Kitab Al-Ilm)" to "كتاب العلم",
        "abudawud|Marriage (Kitab Al-Nikah)" to "كتاب النكاح",
        "abudawud|Medicine (Kitab Al-Tibb)" to "كتاب الطب",
        "abudawud|Model Behavior of the Prophet (Kitab Al-Sunnah)" to "كتاب السنة",
        "abudawud|Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)" to "كتاب الأيمان والنذور",
        "abudawud|Prayer (Kitab Al-Salat)" to "كتاب الصلاة",
        "abudawud|Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan" to "كتاب الصلاة",
        "abudawud|Prayer (Kitab Al-Salat): Detailed Injunctions about Witr" to "كتاب الصلاة",
        "abudawud|Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey" to "كتاب الصلاة",
        "abudawud|Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an" to "كتاب الصلاة",
        "abudawud|Prayer (Kitab Al-Salat): Voluntary Prayers" to "كتاب الصلاة",
        "abudawud|Prescribed Punishments (Kitab Al-Hudud)" to "كتاب الحدود",
        "abudawud|Purification (Kitab Al-Taharah)" to "كتاب الطهارة",
        "abudawud|Sacrifice (Kitab Al-Dahaya)" to "كتاب الأضاحي",
        "abudawud|Shares of Inheritance (Kitab Al-Fara'id)" to "كتاب الفرائض",
        "abudawud|Signet-Rings (Kitab Al-Khatam)" to "كتاب الختم",
        "abudawud|The Book Of The Prayer For Rain (Kitab al-Istisqa')" to "كتاب الصلاة",
        "abudawud|The Book of Lost and Found Items" to "كتاب المفقودات والموجودات",
        "abudawud|The Book of Manumission of Slaves" to "كتاب عتاق العبيد",
        "abudawud|The Office of the Judge (Kitab Al-Aqdiyah)" to "كتاب العقدية",
        "abudawud|The Promised Deliverer (Kitab Al-Mahdi)" to "كتاب المهدي",
        "abudawud|The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)" to "كتاب المناسك والحج",
        "abudawud|Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)" to "كتاب الفتن والملاحم",
        "abudawud|Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)" to "كتاب الخراج، والفياء والعمارة",
        "abudawud|Types of Blood-Wit (Kitab Al-Diyat)" to "كتاب الديات",
        "abudawud|Wages (Kitab Al-Ijarah)" to "كتاب الإجارة",
        "abudawud|Wills (Kitab Al-Wasaya)" to "كتاب الوصايا",
        "abudawud|Zakat (Kitab Al-Zakat)" to "كتاب الزكاة",
        "bukhari|(Statements made under) Coercion" to "(التصريحات تحت عنوان) الإكراه",
        "bukhari|Ablutions (Wudu')" to "كتاب الوضوء",
        "bukhari|Accepting Information Given by a Truthful Person" to "قبول المعلومات المقدمة من شخص صادق",
        "bukhari|Actions while Praying" to "الأفعال أثناء الصلاة",
        "bukhari|Afflictions and the End of the World" to "الآلام ونهاية العالم",
        "bukhari|Agriculture" to "زراعة",
        "bukhari|Al-Adha Festival Sacrifice (Adaahi)" to "كتاب الأضاحي",
        "bukhari|Apostates" to "المرتدين",
        "bukhari|Asking Permission" to "طلب الإذن",
        "bukhari|Bathing (Ghusl)" to "كتاب الغسل",
        "bukhari|Beginning of Creation" to "بداية الخلق",
        "bukhari|Belief" to "كتاب الإيمان",
        "bukhari|Blood Money (Ad-Diyat)" to "كتاب الديات",
        "bukhari|Call to Prayers (Adhaan)" to "كتاب الصلاة",
        "bukhari|Companions of the Prophet" to "أصحاب النبي",
        "bukhari|Conditions" to "شروط",
        "bukhari|Distribution of Water" to "توزيع المياه",
        "bukhari|Divine Will (Al-Qadar)" to "كتاب القدر",
        "bukhari|Divorce" to "كتاب الطلاق",
        "bukhari|Dress" to "كتاب اللباس",
        "bukhari|Drinks" to "كتاب الأشربة",
        "bukhari|Eclipses" to "الكسوف",
        "bukhari|Expiation for Unfulfilled Oaths" to "كتاب الأيمان والنذور",
        "bukhari|Fasting" to "كتاب الصيام",
        "bukhari|Fear Prayer" to "كتاب الصلاة",
        "bukhari|Fighting for the Cause of Allah (Jihaad)" to "القتال في سبيل الله (الجهاد)",
        "bukhari|Food, Meals" to "الغذاء، الوجبات",
        "bukhari|Forgetfulness in Prayer" to "كتاب الصلاة",
        "bukhari|Friday Prayer" to "كتاب الصلاة",
        "bukhari|Funerals (Al-Janaa'iz)" to "كتاب الجنائز",
        "bukhari|Gifts" to "الهدايا",
        "bukhari|Good Manners and Form (Al-Adab)" to "كتاب الأدب",
        "bukhari|Hajj (Pilgrimage)" to "كتاب المناسك",
        "bukhari|Hiring" to "التوظيف",
        "bukhari|Holding Fast to the Qur'an and Sunnah" to "كتاب السنة",
        "bukhari|Hunting, Slaughtering" to "كتاب الصيد",
        "bukhari|Interpretation of Dreams" to "تفسير الاحلام",
        "bukhari|Invocations" to "الدعوات",
        "bukhari|Invoking Allah for Rain (Istisqaa)" to "دعاء المطر (الاستسقاء)",
        "bukhari|Jizyah and Mawaada'ah" to "الجزية والمودة",
        "bukhari|Judgments (Ahkaam)" to "الأحكام (الأحكام)",
        "bukhari|Kafalah" to "كفالة",
        "bukhari|Khusoomaat" to "خسومات",
        "bukhari|Knowledge" to "كتاب العلم",
        "bukhari|Laws of Inheritance (Al-Faraa'id)" to "كتاب الفرائض",
        "bukhari|Limits and Punishments set by Allah (Hudood)" to "كتاب الحدود",
        "bukhari|Loans, Payment of Loans, Freezing of Property, Bankruptcy" to "القروض، سداد القروض، تجميد الممتلكات، الإفلاس",
        "bukhari|Lost Things Picked up by Someone (Luqatah)" to "الأشياء المفقودة التي التقطها شخص ما (لقطة)",
        "bukhari|Makaatib" to "مكاتيب",
        "bukhari|Manumission of Slaves" to "إعتاق العبيد",
        "bukhari|Medicine" to "كتاب الطب",
        "bukhari|Menstrual Periods" to "كتاب الحيض",
        "bukhari|Merits of the Helpers in Madinah (Ansaar)" to "فضل الأنصار في المدينة المنورة (الأنصار)",
        "bukhari|Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)" to "الحملات العسكرية التي قادها النبي (ص) (المغازي)",
        "bukhari|Mortgaging" to "رهن",
        "bukhari|Oaths and Vows" to "كتاب الأيمان والنذور",
        "bukhari|Obligatory Charity Tax (Zakat)" to "كتاب الزكاة",
        "bukhari|One-fifth of Booty to the Cause of Allah (Khumus)" to "(خمس الغنيمة في سبيل الله)",
        "bukhari|Oneness, Uniqueness of Allah (Tawheed)" to "الوحدانية، توحيد الله (التوحيد)",
        "bukhari|Oppressions" to "الاضطهاد",
        "bukhari|Partnership" to "شراكة",
        "bukhari|Patients" to "مرضى",
        "bukhari|Peacemaking" to "صنع السلام",
        "bukhari|Penalty of Hunting while on Pilgrimage" to "كتاب المناسك",
        "bukhari|Pilgrims Prevented from Completing the Pilgrimage" to "كتاب المناسك",
        "bukhari|Prayer at Night (Tahajjud)" to "كتاب الصلاة",
        "bukhari|Prayers (Salat)" to "كتاب الصلاة",
        "bukhari|Praying at Night in Ramadaan (Taraweeh)" to "صلاة قيام الليل في رمضان (التراويح)",
        "bukhari|Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))" to "التفسير النبوي للقرآن (تفسير النبي (ص))",
        "bukhari|Prophets" to "الأنبياء",
        "bukhari|Prostration During Recital of Qur'an" to "السجود أثناء تلاوة القرآن",
        "bukhari|Representation, Authorization, Business by Proxy" to "التمثيل والتفويض والأعمال التجارية بالوكالة",
        "bukhari|Retiring to a Mosque for Remembrance of Allah (I'tikaf)" to "الاعتكاف في المسجد لذكر الله",
        "bukhari|Revelation" to "كتاب بدء الوحي",
        "bukhari|Rubbing hands and feet with dust (Tayammum)" to "كتاب التيمم",
        "bukhari|Sacrifice on Occasion of Birth (`Aqiqa)" to "كتاب الأضاحي",
        "bukhari|Sales and Trade" to "المبيعات والتجارة",
        "bukhari|Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)" to "كتاب السلام",
        "bukhari|Shortening the Prayers (At-Taqseer)" to "كتاب الصلاة",
        "bukhari|Shuf'a" to "شوفة",
        "bukhari|Supporting the Family" to "دعم الأسرة",
        "bukhari|The Two Festivals (Eids)" to "العيدان (الأعياد)",
        "bukhari|Times of the Prayers" to "كتاب الصلاة",
        "bukhari|To make the Heart Tender (Ar-Riqaq)" to "لجعل القلب رقيقًا (الرقاق)",
        "bukhari|Transferance of a Debt from One Person to Another (Al-Hawaala)" to "كتاب الحوالة",
        "bukhari|Tricks" to "الحيل",
        "bukhari|Virtues and Merits of the Prophet (pbuh) and his Companions" to "فضائل النبي صلى الله عليه وسلم وأصحابه",
        "bukhari|Virtues of Madinah" to "فضائل المدينة المنورة",
        "bukhari|Virtues of Prayer at Masjid Makkah and Madinah" to "كتاب الصلاة",
        "bukhari|Virtues of the Night of Qadr" to "فضائل ليلة القدر",
        "bukhari|Virtues of the Qur'an" to "فضائل القرآن",
        "bukhari|Wedlock, Marriage (Nikaah)" to "كتاب النكاح",
        "bukhari|Wills and Testaments (Wasaayaa)" to "كتاب الوصايا",
        "bukhari|Wishes" to "التمنيات",
        "bukhari|Witnesses" to "شهود",
        "bukhari|Witr Prayer" to "كتاب الصلاة",
        "bukhari|`Umrah (Minor pilgrimage)" to "كتاب المناسك",
        "ibnmajah|Chapters Regarding Funerals" to "كتاب الجنائز",
        "ibnmajah|Chapters on Dress" to "كتاب اللباس",
        "ibnmajah|Chapters on Drinks" to "كتاب الأشربة",
        "ibnmajah|Chapters on Food" to "فصول في الغذاء",
        "ibnmajah|Chapters on Hajj Rituals" to "أبواب مناسك الحج",
        "ibnmajah|Chapters on Hunting" to "كتاب الصيد",
        "ibnmajah|Chapters on Medicine" to "كتاب الطب",
        "ibnmajah|Chapters on Sacrifices" to "كتاب الأضاحي",
        "ibnmajah|Chapters on Shares of Inheritance" to "كتاب الفرائض",
        "ibnmajah|Chapters on Slaughtering" to "فصول في الذبح",
        "ibnmajah|Establishing the Prayer and the Sunnah Regarding Them" to "كتاب الصلاة",
        "ibnmajah|Etiquette" to "كتاب الأدب",
        "ibnmajah|Fasting" to "كتاب الصيام",
        "ibnmajah|Interpretation of Dreams" to "تفسير الاحلام",
        "ibnmajah|Supplication" to "الدعاء",
        "ibnmajah|The Book On The Mosques And The Congregations" to "كتاب المساجد والجماعات",
        "ibnmajah|The Book of Purification and its Sunnah" to "كتاب الطهارة",
        "ibnmajah|The Book of the Adhan and the Sunnah Regarding It" to "كتاب السنة",
        "ibnmajah|The Book of the Prayer" to "كتاب الصلاة",
        "ibnmajah|The Book of the Sunnah" to "كتاب السنة",
        "ibnmajah|The Chapters Regarding Zakat" to "كتاب الزكاة",
        "ibnmajah|The Chapters on Blood Money" to "كتاب الديات",
        "ibnmajah|The Chapters on Business Transactions" to "أبواب المعاملات التجارية",
        "ibnmajah|The Chapters on Charity" to "أبواب الإحسان",
        "ibnmajah|The Chapters on Divorce" to "كتاب الطلاق",
        "ibnmajah|The Chapters on Expiation" to "أبواب الكفارة",
        "ibnmajah|The Chapters on Gifts" to "فصول الهدايا",
        "ibnmajah|The Chapters on Jihad" to "كتاب الجهاد",
        "ibnmajah|The Chapters on Legal Punishments" to "كتاب الحدود",
        "ibnmajah|The Chapters on Lost Property" to "فصول الممتلكات المفقودة",
        "ibnmajah|The Chapters on Manumission (of Slaves)" to "أبواب العتاق",
        "ibnmajah|The Chapters on Marriage" to "كتاب النكاح",
        "ibnmajah|The Chapters on Pawning" to "فصول الرهن",
        "ibnmajah|The Chapters on Pre-emption" to "أبواب الشفعة",
        "ibnmajah|The Chapters on Rulings" to "أبواب الأحكام",
        "ibnmajah|The Chapters on Wills" to "كتاب الوصايا",
        "ibnmajah|Tribulations" to "المحن",
        "ibnmajah|Zuhd" to "زهد",
        "muslim|Characteristics of The Hypocrites And Rulings Concerning Them" to "صفات المنافقين وأحكامهم",
        "muslim|Characteristics of the Day of Judgment, Paradise, and Hell" to "خصائص يوم القيامة والجنة والنار",
        "muslim|Introduction" to "مقدمة",
        "muslim|The Book Concerning the Use of Correct Words" to "كتاب في استعمال الألفاظ الصحيحة",
        "muslim|The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness" to "كتاب الذكر والدعاء والتوبة والاستغفار",
        "muslim|The Book of Clothes and Adornment" to "كتاب اللباس والزينة",
        "muslim|The Book of Commentary on the Qur'an" to "كتاب تفسير القرآن",
        "muslim|The Book of Destiny" to "كتاب القدر",
        "muslim|The Book of Divorce" to "كتاب الطلاق",
        "muslim|The Book of Dreams" to "كتاب الأحلام",
        "muslim|The Book of Drinks" to "كتاب الأشربة",
        "muslim|The Book of Emancipating Slaves" to "كتاب تحرير العبيد",
        "muslim|The Book of Faith" to "كتاب الإيمان",
        "muslim|The Book of Fasting" to "كتاب الصيام",
        "muslim|The Book of Gifts" to "كتاب الهدايا",
        "muslim|The Book of Greetings" to "كتاب التحية",
        "muslim|The Book of Heart-Melting Traditions" to "كتاب التقاليد التي تذوب القلب",
        "muslim|The Book of Hunting, Slaughter, and what may be Eaten" to "كتاب الصيد",
        "muslim|The Book of I'tikaf" to "كتاب الاعتكاف",
        "muslim|The Book of Invoking Curses" to "كتاب استدعاء اللعنات",
        "muslim|The Book of Jihad and Expeditions" to "كتاب الجهاد",
        "muslim|The Book of Judicial Decisions" to "كتاب القرارات القضائية",
        "muslim|The Book of Knowledge" to "كتاب العلم",
        "muslim|The Book of Legal Punishments" to "كتاب الحدود",
        "muslim|The Book of Lost Property" to "كتاب الممتلكات المفقودة",
        "muslim|The Book of Manners and Etiquette" to "كتاب الأدب",
        "muslim|The Book of Marriage" to "كتاب النكاح",
        "muslim|The Book of Menstruation" to "كتاب الحيض",
        "muslim|The Book of Mosques and Places of Prayer" to "كتاب الصلاة",
        "muslim|The Book of Musaqah" to "كتاب المساقاة",
        "muslim|The Book of Oaths" to "كتاب الأيمان والنذور",
        "muslim|The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)" to "كتاب الديات",
        "muslim|The Book of Paradise, its Description, its Bounties and its Inhabitants" to "كتاب الجنة ووصفها ونعيمها وأهلها",
        "muslim|The Book of Pilgrimage" to "كتاب المناسك",
        "muslim|The Book of Poetry" to "كتاب الشعر",
        "muslim|The Book of Prayer - Eclipses" to "كتاب الصلاة",
        "muslim|The Book of Prayer - Friday" to "كتاب الصلاة",
        "muslim|The Book of Prayer - Funerals" to "كتاب الصلاة",
        "muslim|The Book of Prayer - Rain" to "كتاب الصلاة",
        "muslim|The Book of Prayer - Travellers" to "كتاب الصلاة",
        "muslim|The Book of Prayer - Two Eids" to "كتاب الصلاة",
        "muslim|The Book of Prayers" to "كتاب الصلاة",
        "muslim|The Book of Purification" to "كتاب الطهارة",
        "muslim|The Book of Repentance" to "كتاب التوبة",
        "muslim|The Book of Sacrifices" to "كتاب الأضاحي",
        "muslim|The Book of Suckling" to "كتاب الرضاعة",
        "muslim|The Book of Transactions" to "كتاب المعاملات",
        "muslim|The Book of Tribulations and Portents of the Last Hour" to "كتاب الفتن وأشراط الساعة",
        "muslim|The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship" to "كتاب الأدب",
        "muslim|The Book of Virtues" to "كتاب الفضائل",
        "muslim|The Book of Vows" to "كتاب النذور",
        "muslim|The Book of Wills" to "كتاب الوصايا",
        "muslim|The Book of Zakat" to "كتاب الزكاة",
        "muslim|The Book of Zuhd and Softening of Hearts" to "كتاب الزهد وتلطيف القلوب",
        "muslim|The Book of the Merits of the Companions" to "كتاب فضائل الصحابة",
        "muslim|The Book of the Rules of Inheritance" to "كتاب الفرائض",
        "muslim|The Book on Government" to "كتاب الحكومة",
        "muwatta|Asking for Rain" to "يسأل عن المطر",
        "muwatta|Blood-Money" to "أموال الدم",
        "muwatta|Burials" to "كتاب الجنائز",
        "muwatta|Business Transactions" to "المعاملات التجارية",
        "muwatta|Divorce" to "كتاب الطلاق",
        "muwatta|Dress" to "كتاب اللباس",
        "muwatta|Drinks" to "كتاب الأشربة",
        "muwatta|Fara'id" to "كتاب الفرائض",
        "muwatta|Fasting" to "كتاب الصيام",
        "muwatta|Forgetfulness in Prayer" to "كتاب الصلاة",
        "muwatta|Game" to "كتاب الصيد",
        "muwatta|General Subjects" to "مواضيع عامة",
        "muwatta|Good Character" to "شخصية جيدة",
        "muwatta|Greetings" to "تحيات",
        "muwatta|Hair" to "شعر",
        "muwatta|Hajj" to "كتاب المناسك",
        "muwatta|Hudud" to "كتاب الحدود",
        "muwatta|I'tikaf in Ramadan" to "الاعتكاف في رمضان",
        "muwatta|Jahannam" to "جهنم",
        "muwatta|Jihad" to "كتاب الجهاد",
        "muwatta|Judgements" to "الأحكام",
        "muwatta|Jumu'a" to "جمعة",
        "muwatta|Knowledge" to "كتاب العلم",
        "muwatta|Madina" to "المدينة المنورة",
        "muwatta|Marriage" to "كتاب النكاح",
        "muwatta|Prayer" to "كتاب الصلاة",
        "muwatta|Prayer in Congregation" to "كتاب الصلاة",
        "muwatta|Prayer in Ramadan" to "كتاب الصلاة",
        "muwatta|Pre-emption in Property" to "الشفعة في الممتلكات",
        "muwatta|Purity" to "كتاب الطهارة",
        "muwatta|Qirad" to "قراد",
        "muwatta|Renting Land" to "تأجير الأراضي",
        "muwatta|Sacrificial Animals" to "حيوانات الأضحية",
        "muwatta|Sadaqa" to "صدقة",
        "muwatta|Setting Free and Wala'" to "تحرير وولاء",
        "muwatta|Sharecropping" to "المزارعة",
        "muwatta|Shortening the Prayer" to "كتاب الصلاة",
        "muwatta|Slaughtering Animals" to "ذبح الحيوانات",
        "muwatta|Speech" to "خطاب",
        "muwatta|Suckling" to "الرضاعة",
        "muwatta|Tahajjud" to "التهجد",
        "muwatta|The 'Aqiqa" to "العقيقة",
        "muwatta|The Decree" to "المرسوم",
        "muwatta|The Description of the Prophet, may Allah Bless Him and Grant Him Peace" to "صفة النبي صلى الله عليه وسلم",
        "muwatta|The Eclipse Prayer" to "كتاب الصلاة",
        "muwatta|The Evil Eye" to "العين الشريرة",
        "muwatta|The Fear Prayer" to "كتاب الصلاة",
        "muwatta|The Mudabbar" to "المدبر",
        "muwatta|The Mukatab" to "المكاتب",
        "muwatta|The Names of the Prophet, may Allah Bless Him and Grant Him Peace" to "أسماء النبي صلى الله عليه وسلم",
        "muwatta|The Oath of Allegiance" to "قسم الولاء",
        "muwatta|The Oath of Qasama" to "قسم القسام",
        "muwatta|The Qibla" to "القبلة",
        "muwatta|The Qur'an" to "القرآن",
        "muwatta|The Supplication of the Unjustly Wronged" to "دعاء المظلوم",
        "muwatta|The Times of Prayer" to "كتاب الصلاة",
        "muwatta|The Two 'Ids" to "المعرفان",
        "muwatta|Visions" to "رؤى",
        "muwatta|Vows and Oaths" to "كتاب الأيمان والنذور",
        "muwatta|Wills and Testaments" to "كتاب الوصايا",
        "muwatta|Zakat" to "كتاب الزكاة",
        "nasai|The Book Of Faith and its Signs" to "كتاب الإيمان",
        "nasai|The Book of 'Umra" to "كتاب العمرة",
        "nasai|The Book of Adornment" to "كتاب الزينة",
        "nasai|The Book of Agriculture" to "كتاب الزراعة",
        "nasai|The Book of Cutting off the Hand of the Thief" to "كتاب قطع يد السارق",
        "nasai|The Book of Distribution of Al-Fay'" to "كتاب توزيع الفيء",
        "nasai|The Book of Divorce" to "كتاب الطلاق",
        "nasai|The Book of Drinks" to "كتاب الأشربة",
        "nasai|The Book of Eclipses" to "كتاب الخسوف",
        "nasai|The Book of Endowments" to "كتاب الأوقاف",
        "nasai|The Book of Fasting" to "كتاب الصيام",
        "nasai|The Book of Fighting [The Prohibition of Bloodshed]" to "كتاب القتال [تحريم الدماء]",
        "nasai|The Book of Financial Transactions" to "كتاب المعاملات المالية",
        "nasai|The Book of Forgetfulness (In Prayer)" to "كتاب الصلاة",
        "nasai|The Book of Funerals" to "كتاب الجنائز",
        "nasai|The Book of Ghusl and Tayammum" to "كتاب الغسل",
        "nasai|The Book of Gifts" to "كتاب الهدايا",
        "nasai|The Book of Hajj" to "كتاب الحج",
        "nasai|The Book of Horses, Races and Shooting" to "كتاب الخيل والأجناس والرماية",
        "nasai|The Book of Hunting and Slaughtering" to "كتاب الصيد",
        "nasai|The Book of Jihad" to "كتاب الجهاد",
        "nasai|The Book of Jumu'ah (Friday Prayer)" to "كتاب الصلاة",
        "nasai|The Book of Leading the Prayer (Al-Imamah)" to "كتاب الصلاة",
        "nasai|The Book of Marriage" to "كتاب النكاح",
        "nasai|The Book of Menstruation and Istihadah" to "كتاب الحيض",
        "nasai|The Book of Oaths (qasamah), Retaliation and Blood Money" to "كتاب الديات",
        "nasai|The Book of Praying for Rain (Al-Istisqa')" to "كتاب الاستسقاء",
        "nasai|The Book of Presents" to "كتاب الهدايا",
        "nasai|The Book of Purification" to "كتاب الطهارة",
        "nasai|The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day" to "كتاب الصلاة",
        "nasai|The Book of Salah" to "كتاب صلاح",
        "nasai|The Book of Seeking Refuge with Allah" to "كتاب الاستعاذة بالله",
        "nasai|The Book of Shortening the Prayer When Traveling" to "كتاب الصلاة",
        "nasai|The Book of The At-Tatbiq (Clasping One's Hands Together)" to "كتاب التطبيق (شبك اليدين)",
        "nasai|The Book of Water" to "كتاب الماء",
        "nasai|The Book of Wills" to "كتاب الوصايا",
        "nasai|The Book of Zakah" to "كتاب الزكاة",
        "nasai|The Book of ad-Dahaya (Sacrifices)" to "كتاب الأضاحي",
        "nasai|The Book of al-'Aqiqah" to "كتاب العقيقة",
        "nasai|The Book of al-Bay'ah" to "كتاب البيعة",
        "nasai|The Book of al-Fara' and al-'Atirah" to "كتاب الفراء والعطيرة",
        "nasai|The Book of ar-Ruqba" to "كتاب الركبه",
        "nasai|The Book of the Adhan (The Call to Prayer)" to "كتاب الصلاة",
        "nasai|The Book of the Commencement of the Prayer" to "كتاب الصلاة",
        "nasai|The Book of the Etiquette of Judges" to "كتاب الأدب",
        "nasai|The Book of the Fear Prayer" to "كتاب الصلاة",
        "nasai|The Book of the Kind Treatment of Women" to "كتاب العشرة بالنساء",
        "nasai|The Book of the Masjids" to "كتاب المساجد",
        "nasai|The Book of the Prayer for the Two 'Eids" to "كتاب الصلاة",
        "nasai|The Book of the Qiblah" to "كتاب القبلة",
        "nasai|The Book of the Times (of Prayer)" to "كتاب الصلاة",
        "nawawi40|Forty Hadith of an-Nawawi" to "الأربعون النووية",
        "riyad|The Book About the Etiquette of Eating" to "كتاب آداب الطعام",
        "riyad|The Book of Dress" to "كتاب اللباس",
        "riyad|The Book of Du'a (Supplications)" to "كتاب الدعوات",
        "riyad|The Book of Etiquette of Traveling" to "كتاب آداب السفر",
        "riyad|The Book of Forgiveness" to "كتاب الاستغفار",
        "riyad|The Book of Good Manners" to "كتاب الأدب",
        "riyad|The Book of Greetings" to "كتاب السلام",
        "riyad|The Book of Hajj" to "كتاب الحج",
        "riyad|The Book of I'tikaf" to "كتاب الاعتكاف",
        "riyad|The Book of Jihad" to "كتاب الجهاد",
        "riyad|The Book of Knowledge" to "كتاب العلم",
        "riyad|The Book of Miscellaneous ahadith of Significant Values" to "كتاب المنثورات والملح",
        "riyad|The Book of Miscellany" to "كتاب الأمور المنهي عنها",
        "riyad|The Book of Praise and Gratitude to Allah" to "كتاب حمد الله تعالى وشكره",
        "riyad|The Book of Supplicating Allah to Exalt the Mention of Allah's Messenger" to "كتاب الصلاة على رسول الله ﷺ",
        "riyad|The Book of Virtues" to "كتاب الفضائل",
        "riyad|The Book of Visiting the Sick" to "كتاب عيادة المريض",
        "riyad|The Book of the Etiquette of Sleeping, Lying and Sitting etc" to "كتاب آداب النوم والاضطجاع والقعود",
        "riyad|The Book of the Prohibited actions" to "كتاب المنهيات",
        "riyad|The Book of the Remembrance of Allah" to "كتاب الأذكار",
        "tirmidhi|Chapters On Al-Fitan" to "فصول في الفتن",
        "tirmidhi|Chapters On Al-Qadar" to "فصول في القدر",
        "tirmidhi|Chapters On Dreams" to "فصول في الأحلام",
        "tirmidhi|Chapters On Inheritance" to "كتاب الفرائض",
        "tirmidhi|Chapters On Wala' And Gifts" to "فصول في الولاء والهدايا",
        "tirmidhi|Chapters On Wasaya (Wills and Testament)" to "كتاب الوصايا",
        "tirmidhi|Chapters On Witnesses" to "فصول في الشهود",
        "tirmidhi|Chapters On Zuhd" to "فصول في الزهد",
        "tirmidhi|Chapters on Knowledge" to "كتاب العلم",
        "tirmidhi|Chapters on Manners" to "كتاب الأدب",
        "tirmidhi|Chapters on Medicine" to "كتاب الطب",
        "tirmidhi|Chapters on Parables" to "فصول في الأمثال",
        "tirmidhi|Chapters on Recitation" to "فصول في التلاوة",
        "tirmidhi|Chapters on Righteousness And Maintaining Good Relations With Relatives" to "فصول في البر وحسن العلاقات مع الأرحام",
        "tirmidhi|Chapters on Seeking Permission" to "فصول في طلب الإذن",
        "tirmidhi|Chapters on Supplication" to "فصول في الدعاء",
        "tirmidhi|Chapters on Tafsir" to "فصول في التفسير",
        "tirmidhi|Chapters on The Virtues of the Qur'an" to "أبواب في فضائل القرآن",
        "tirmidhi|Chapters on Virtues" to "فصول في الفضائل",
        "tirmidhi|Chapters on the description of Paradise" to "أبواب في صفة الجنة",
        "tirmidhi|Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'" to "أبواب صفة يوم القيامة والرقاق والوراء",
        "tirmidhi|The Book on Al-Witr" to "كتاب الوتر",
        "tirmidhi|The Book on Blood Money" to "كتاب الديات",
        "tirmidhi|The Book on Business" to "كتاب الأعمال",
        "tirmidhi|The Book on Clothing" to "كتاب اللباس",
        "tirmidhi|The Book on Divorce and Li'an" to "كتاب الطلاق",
        "tirmidhi|The Book on Drinks" to "كتاب الأشربة",
        "tirmidhi|The Book on Faith" to "كتاب الإيمان",
        "tirmidhi|The Book on Fasting" to "كتاب الصيام",
        "tirmidhi|The Book on Food" to "كتاب الغذاء",
        "tirmidhi|The Book on Hajj" to "كتاب الحج",
        "tirmidhi|The Book on Hunting" to "كتاب الصيد",
        "tirmidhi|The Book on Jana''iz (Funerals)" to "كتاب الجنائز",
        "tirmidhi|The Book on Jihad" to "كتاب الجهاد",
        "tirmidhi|The Book on Legal Punishments (Al-Hudud)" to "كتاب الحدود",
        "tirmidhi|The Book on Marriage" to "كتاب النكاح",
        "tirmidhi|The Book on Military Expeditions" to "كتاب البعثات العسكرية",
        "tirmidhi|The Book on Purification" to "كتاب الطهارة",
        "tirmidhi|The Book on Sacrifices" to "كتاب الأضاحي",
        "tirmidhi|The Book on Salat (Prayer)" to "كتاب الصلاة",
        "tirmidhi|The Book on Suckling" to "كتاب الرضاعة",
        "tirmidhi|The Book on Traveling" to "كتاب السفر",
        "tirmidhi|The Book on Virtues of Jihad" to "كتاب الجهاد",
        "tirmidhi|The Book on Vows and Oaths" to "كتاب الأيمان والنذور",
        "tirmidhi|The Book on Zakat" to "كتاب الزكاة",
        "tirmidhi|The Book on the Day of Friday" to "كتاب يوم الجمعة",
        "tirmidhi|The Book on the Description of Hellfire" to "كتاب صفة النار",
        "tirmidhi|The Book on the Two Eids" to "كتاب العيدين",
        "tirmidhi|The Chapters On Judgements From The Messenger of Allah" to "أبواب الأحكام عن رسول الله صلى الله عليه وسلم",
    )

    fun displayTitle(collection: HadithCollection, sourceTitle: String): String =
        byCollectionAndSource["${collection.id}|$sourceTitle"] ?: sourceTitle
}
