package org.muslim.app.feature.family.domain

/**
 * Curated expansion for the baby-name catalogue.
 *
 * Meanings are concise language aids rather than religious rulings. Entries with
 * a historical note identify well-known Quranic or early-Muslim usage without
 * treating that association as a guarantee that every spelling or modern usage
 * is automatically recommended.
 */
object FamilyNamesExpansion {
    val names: List<IslamicBabyName> = listOf(
        prophet("zakariya", "زكريا", "Zakariya", BabyNameGender.Boy, "اسم نبي من أنبياء الله", "The name of a prophet", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("yahya", "يحيى", "Yahya", BabyNameGender.Boy, "اسم نبي من أنبياء الله", "The name of a prophet", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("isa", "عيسى", "Isa", BabyNameGender.Boy, "اسم نبي الله عيسى", "The name of Prophet Isa", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("dawud", "داود", "Dawud", BabyNameGender.Boy, "اسم نبي الله داود", "The name of Prophet Dawud", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("sulayman", "سليمان", "Sulayman", BabyNameGender.Boy, "اسم نبي الله سليمان", "The name of Prophet Sulayman", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("ayyub", "أيوب", "Ayyub", BabyNameGender.Boy, "اسم نبي ارتبط بالصبر", "The name of a prophet associated with patience", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("idris", "إدريس", "Idris", BabyNameGender.Boy, "اسم نبي من أنبياء الله", "The name of a prophet", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("harun", "هارون", "Harun", BabyNameGender.Boy, "اسم نبي الله هارون", "The name of Prophet Harun", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("ishaq", "إسحاق", "Ishaq", BabyNameGender.Boy, "اسم نبي الله إسحاق", "The name of Prophet Ishaq", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("yaqub", "يعقوب", "Yaqub", BabyNameGender.Boy, "اسم نبي الله يعقوب", "The name of Prophet Yaqub", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("nuh", "نوح", "Nuh", BabyNameGender.Boy, "اسم نبي الله نوح", "The name of Prophet Nuh", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("hud", "هود", "Hud", BabyNameGender.Boy, "اسم نبي الله هود", "The name of Prophet Hud", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("salih", "صالح", "Salih", BabyNameGender.Boy, "الصالح المستقيم، واسم نبي", "Righteous and upright; also the name of a prophet", "اسم عربي واسم نبي ورد في القرآن", "An Arabic name and a prophet named in the Quran"),
        prophet("shuayb", "شعيب", "Shuayb", BabyNameGender.Boy, "اسم نبي الله شعيب", "The name of Prophet Shuayb", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("ilyas", "إلياس", "Ilyas", BabyNameGender.Boy, "اسم نبي من أنبياء الله", "The name of a prophet", "اسم نبي ورد في القرآن", "A prophet named in the Quran"),
        prophet("luqman", "لقمان", "Luqman", BabyNameGender.Boy, "اسم لقمان الحكيم", "The name of Luqman the Wise", "ورد اسمه في القرآن", "His name appears in the Quran"),
        arabic("imran", "عمران", "Imran", BabyNameGender.Boy, "العمران والبناء والازدهار", "Building, flourishing and prosperity", "ورد الاسم في القرآن", "The name appears in the Quran"),
        arabic("talha", "طلحة", "Talha", BabyNameGender.Boy, "اسم شجرة، واسم صحابي مشهور", "A tree name and the name of a well-known companion", "اسم صحابي مشهور", "A well-known companion's name"),
        arabic("zubayr", "الزبير", "Zubayr", BabyNameGender.Boy, "اسم عربي قديم", "A classical Arabic name", "اسم صحابي مشهور", "A well-known companion's name"),
        arabic("musab", "مصعب", "Musab", BabyNameGender.Boy, "القوي أو المحتمل للشدة", "Strong or able to endure hardship", "اسم صحابي مشهور", "A well-known companion's name"),
        arabic("jaafar", "جعفر", "Jaafar", BabyNameGender.Boy, "النهر الصغير أو كثير الماء", "A small river or abundant water", "اسم عربي قديم", "A classical Arabic name"),
        arabic("tariq", "طارق", "Tariq", BabyNameGender.Boy, "الآتي ليلًا، والطارق اسم وارد في القرآن", "One who arrives by night; al-Tariq also appears in the Quran", "اسم عربي قرآني الاستعمال", "An Arabic name with Quranic usage"),
        arabic("bashir", "بشير", "Bashir", BabyNameGender.Boy, "حامل البشارة والخبر السار", "Bearer of glad tidings", "اسم عربي حسن المعنى", "An Arabic name with a positive meaning"),
        arabic("munir", "منير", "Munir", BabyNameGender.Boy, "المضيء والمشرق", "Luminous and bright", "اسم عربي", "Arabic"),
        arabic("mahir", "ماهر", "Mahir", BabyNameGender.Boy, "المتقن والبارع", "Skilled and proficient", "اسم عربي", "Arabic"),
        arabic("adil", "عادل", "Adil", BabyNameGender.Boy, "المتصف بالعدل", "Just and fair", "اسم عربي", "Arabic"),
        arabic("amin", "أمين", "Amin", BabyNameGender.Boy, "الموثوق الصادق", "Trustworthy and honest", "اسم عربي", "Arabic"),
        arabic("rafiq", "رفيق", "Rafiq", BabyNameGender.Boy, "الصاحب اللطيف", "A kind companion", "اسم عربي", "Arabic"),
        arabic("hakim", "حكيم", "Hakim", BabyNameGender.Boy, "ذو الحكمة وحسن التقدير", "Wise and sound in judgment", "اسم عربي؛ ويُراعى عدم قصد الاسم الإلهي المختص", "Arabic; avoid intending a divine name in a uniquely divine sense"),
        arabic("rashid", "راشد", "Rashid", BabyNameGender.Boy, "المهتدي إلى الصواب", "Rightly guided and sensible", "اسم عربي", "Arabic"),
        arabic("faisal", "فيصل", "Faisal", BabyNameGender.Boy, "الفاصل والحاكم بين الأمور", "One who distinguishes or decides between matters", "اسم عربي", "Arabic"),
        arabic("iyad", "إياد", "Iyad", BabyNameGender.Boy, "السند والقوة", "Support and strength", "اسم عربي", "Arabic"),
        arabic("tamim", "تميم", "Tamim", BabyNameGender.Boy, "التام في صفاته", "Complete or well-formed", "اسم عربي قديم", "A classical Arabic name"),
        arabic("thabit", "ثابت", "Thabit", BabyNameGender.Boy, "الراسخ المستقر", "Steadfast and firm", "اسم عربي", "Arabic"),
        arabic("badr", "بدر", "Badr", BabyNameGender.Boy, "القمر ليلة اكتماله", "The full moon", "اسم عربي", "Arabic"),
        arabic("fadl", "فضل", "Fadl", BabyNameGender.Boy, "الزيادة والخير والإحسان", "Grace, goodness and generosity", "اسم عربي", "Arabic"),
        arabic("ridwan", "رضوان", "Ridwan", BabyNameGender.Boy, "الرضا والقبول", "Contentment and approval", "اسم عربي", "Arabic"),
        arabic("suhayb", "صهيب", "Suhayb", BabyNameGender.Boy, "اسم عربي قديم", "A classical Arabic name", "اسم صحابي مشهور", "A well-known companion's name"),
        arabic("hudhayfah", "حذيفة", "Hudhayfah", BabyNameGender.Boy, "اسم عربي قديم", "A classical Arabic name", "اسم صحابي مشهور", "A well-known companion's name"),
        arabic("miqdad", "المقداد", "Miqdad", BabyNameGender.Boy, "اسم عربي قديم", "A classical Arabic name", "اسم صحابي مشهور", "A well-known companion's name"),

        arabic("aminah", "آمنة", "Aminah", BabyNameGender.Girl, "الآمنة المطمئنة", "Safe and secure", "اسم عربي مشهور في السيرة", "A classical Arabic name known from the sira"),
        arabic("halimah", "حليمة", "Halimah", BabyNameGender.Girl, "الحليمة الصبورة المتأنية", "Forbearing, patient and gentle", "اسم عربي مشهور في السيرة", "A classical Arabic name known from the sira"),
        arabic("juwayriyah", "جويرية", "Juwayriyah", BabyNameGender.Girl, "اسم عربي قديم", "A classical Arabic name", "اسم أم من أمهات المؤمنين", "The name of a Mother of the Believers"),
        arabic("maymunah", "ميمونة", "Maymunah", BabyNameGender.Girl, "المباركة والميمونة", "Blessed and fortunate", "اسم أم من أمهات المؤمنين", "The name of a Mother of the Believers"),
        arabic("nusaybah", "نسيبة", "Nusaybah", BabyNameGender.Girl, "اسم عربي قديم", "A classical Arabic name", "اسم صحابية مشهورة", "A well-known companion woman's name"),
        arabic("rufaida", "رفيدة", "Rufaida", BabyNameGender.Girl, "العون والدعم", "Aid and support", "اسم عربي متداول", "An Arabic name in common usage"),
        arabic("shifa", "شفاء", "Shifa", BabyNameGender.Girl, "البرء والعافية", "Healing and recovery", "لفظ عربي ورد في القرآن", "An Arabic word used in the Quran"),
        arabic("marwa", "مروة", "Marwa", BabyNameGender.Girl, "اسم جبل المروة من شعائر الحج", "The name of al-Marwah, one of the Hajj landmarks", "اسم مرتبط بشعيرة الصفا والمروة", "Associated with the rite of Safa and Marwah"),
        arabic("safa", "صفا", "Safa", BabyNameGender.Girl, "الصفاء، واسم جبل الصفا", "Clarity and purity; also al-Safa", "اسم مرتبط بشعيرة الصفا والمروة", "Associated with the rite of Safa and Marwah"),
        arabic("kawthar", "كوثر", "Kawthar", BabyNameGender.Girl, "الخير الكثير", "Abundant goodness", "لفظ قرآني", "A Quranic word"),
        arabic("firdaus", "فردوس", "Firdaus", BabyNameGender.Girl, "الفردوس والجنة العالية", "Paradise and the highest gardens", "لفظ وارد في القرآن", "A word used in the Quran"),
        arabic("duha", "ضحى", "Duha", BabyNameGender.Girl, "وقت ارتفاع النهار وإشراقه", "The bright forenoon", "لفظ قرآني واسم سورة", "A Quranic word and surah name"),
        arabic("shuruq", "شروق", "Shuruq", BabyNameGender.Girl, "طلوع الشمس وإضاءتها", "Sunrise and first light", "اسم عربي", "Arabic"),
        arabic("amal", "أمل", "Amal", BabyNameGender.Girl, "الرجاء والتطلع إلى الخير", "Hope and positive expectation", "اسم عربي", "Arabic"),
        arabic("nada", "ندى", "Nada", BabyNameGender.Girl, "قطرات الندى والكرم", "Dewdrops and generosity", "اسم عربي", "Arabic"),
        arabic("wafa", "وفاء", "Wafa", BabyNameGender.Girl, "الإخلاص والوفاء بالعهد", "Loyalty and faithfulness", "اسم عربي", "Arabic"),
        arabic("najwa", "نجوى", "Najwa", BabyNameGender.Girl, "الحديث الخفي والمناجاة", "Private conversation or intimate supplication", "لفظ عربي ورد في القرآن", "An Arabic word used in the Quran"),
        arabic("manal", "منال", "Manal", BabyNameGender.Girl, "ما يُنال ويُدرك", "That which is attained", "اسم عربي", "Arabic"),
        arabic("reem", "ريم", "Reem", BabyNameGender.Girl, "الغزال الأبيض في الاستعمال العربي", "A white gazelle in Arabic usage", "اسم عربي", "Arabic"),
        arabic("ghada", "غادة", "Ghada", BabyNameGender.Girl, "الرقيقة اللينة", "Graceful and gentle", "اسم عربي", "Arabic"),
        arabic("lamia", "لمياء", "Lamia", BabyNameGender.Girl, "اسم عربي قديم من أوصاف الجمال", "A classical Arabic name associated with beauty", "اسم عربي", "Arabic"),
        arabic("rania", "رانيا", "Rania", BabyNameGender.Girl, "الناظرة بإمعان", "One who looks attentively", "اسم عربي", "Arabic"),
        arabic("samira", "سميرة", "Samira", BabyNameGender.Girl, "رفيقة السمر والحديث ليلًا", "A companion in evening conversation", "اسم عربي", "Arabic"),
        arabic("suhaila", "سهيلة", "Suhaila", BabyNameGender.Girl, "السهلة اللطيفة", "Gentle and easy-going", "اسم عربي", "Arabic"),
        arabic("karima", "كريمة", "Karima", BabyNameGender.Girl, "الكريمة الشريفة السخية", "Generous and noble", "اسم عربي", "Arabic"),
        arabic("afaf", "عفاف", "Afaf", BabyNameGender.Girl, "العفة والنزاهة", "Chastity and integrity", "اسم عربي", "Arabic"),
        arabic("ihsan", "إحسان", "Ihsan", BabyNameGender.Girl, "الإتقان وفعل الخير", "Excellence and doing good", "لفظ عربي قرآني", "An Arabic Quranic term"),
        arabic("sakinah", "سكينة", "Sakinah", BabyNameGender.Girl, "الطمأنينة والهدوء", "Tranquillity and calm", "لفظ وارد في القرآن", "A word used in the Quran"),
        arabic("mawaddah", "مودة", "Mawaddah", BabyNameGender.Girl, "المحبة الصادقة", "Deep affection", "لفظ وارد في القرآن", "A word used in the Quran"),
        arabic("hikmah", "حكمة", "Hikmah", BabyNameGender.Girl, "الحكمة وحسن التقدير", "Wisdom and sound judgment", "لفظ عربي قرآني", "An Arabic Quranic term"),
    )

    private fun arabic(
        id: String,
        arabic: String,
        transliteration: String,
        gender: BabyNameGender,
        meaningArabic: String,
        meaningEnglish: String,
        noteArabic: String,
        noteEnglish: String,
    ) = IslamicBabyName(
        id = id,
        nameArabic = arabic,
        transliteration = transliteration,
        gender = gender,
        meaningArabic = meaningArabic,
        meaningEnglish = meaningEnglish,
        origin = LocalizedFamilyText("عربي أو مستعمل عربيًا", "Arabic or established Arabic usage"),
        note = LocalizedFamilyText(noteArabic, noteEnglish),
    )

    private fun prophet(
        id: String,
        arabic: String,
        transliteration: String,
        gender: BabyNameGender,
        meaningArabic: String,
        meaningEnglish: String,
        noteArabic: String,
        noteEnglish: String,
    ) = IslamicBabyName(
        id = id,
        nameArabic = arabic,
        transliteration = transliteration,
        gender = gender,
        meaningArabic = meaningArabic,
        meaningEnglish = meaningEnglish,
        note = LocalizedFamilyText(noteArabic, noteEnglish),
    )
}
