import java.util.Base64
import java.util.Properties

// Derives versionCode/versionName from the nearest `v*` git tag so the release
// version is never hardcoded (PROJECT_PROMPT.md §8). scripts/release.sh pushes
// the tag before building, so `git describe` returns e.g. "v1.3.0"; VERSION_TAG
// is an explicit override for CI where tags are not reachable from HEAD.
val gitVersionTag = providers.exec {
    commandLine("git", "describe", "--tags", "--match", "v*", "--always")
    workingDir = rootProject.projectDir
    isIgnoreExitValue = true
}.standardOutput.asText.map { it.trim() }

fun deriveVersion(describe: String, envTag: String): Pair<Int, String> {
    val match = Regex("v?(\\d+)\\.(\\d+)\\.(\\d+)").find(envTag.ifBlank { describe })
    val major = match?.groupValues?.get(1)?.toIntOrNull() ?: 1
    val minor = match?.groupValues?.get(2)?.toIntOrNull() ?: 0
    val patch = match?.groupValues?.get(3)?.toIntOrNull() ?: 0
    val versionCode = major * 10_000 + minor * 100 + patch
    val versionName = if (match == null) "1.0.0-dev" else "$major.$minor.$patch"
    return versionCode to versionName
}

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = "org.muslim.app"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "org.muslim.app"
        minSdk = 26
        targetSdk = 37
        val (code, name) = deriveVersion(gitVersionTag.get(), System.getenv("VERSION_TAG").orEmpty())
        versionCode = code
        versionName = name
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        // Release signing resolution order (same stable key everywhere so
        // updates install over existing installs without uninstalling):
        //   1. keystore.properties — machine-local, generated by
        //      scripts/create-signing-keystore.sh (git-ignored).
        //   2. CI env secrets (SIGNING_KEYSTORE base64 + passwords) — uploaded
        //      once by scripts/setup-github-signing.sh.
        //   3. Debug key fallback so `assembleRelease` works out of the box.
        create("release") {
            val props = Properties().apply {
                val file = rootProject.file("keystore.properties")
                if (file.exists()) file.inputStream().use { load(it) }
            }
            val storeFilePath = props.getProperty("storeFile")
            if (storeFilePath != null) {
                storeFile = rootProject.file(storeFilePath)
                storePassword = props.getProperty("storePassword")
                keyAlias = props.getProperty("keyAlias")
                keyPassword = props.getProperty("keyPassword")
            } else {
                val envKeystore = System.getenv("SIGNING_KEYSTORE")
                if (!envKeystore.isNullOrBlank()) {
                    val decoded = Base64.getDecoder().decode(envKeystore)
                    val keystoreFile = File(System.getProperty("java.io.tmpdir"), "muslim-release-keystore.jks")
                    keystoreFile.writeBytes(decoded)
                    storeFile = keystoreFile
                    storePassword = System.getenv("SIGNING_STORE_PASSWORD")
                    keyAlias = System.getenv("SIGNING_KEY_ALIAS")
                    keyPassword = System.getenv("SIGNING_KEY_PASSWORD")
                }
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.getByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    lint {
        // False positive: AAPT2 only accepts <adaptive-icon> resources inside a
        // version-qualified `mipmap-anydpi-v26` folder even though minSdk is 26
        // (the plain `mipmap-anydpi` folder fails resource linking).
        disable += "ObsoleteSdkInt"
        // The "newer version available" hints for KSP / the Compose compiler
        // plugin require a Kotlin newer than AGP 9.3's built-in 2.2.10 — the
        // versions in the catalog are pinned to the built-in Kotlin on purpose.
        disable += "GradleDependency"
        disable += "NewerVersionAvailable"
        // app_name is professionally translated in every locale folder; the
        // remaining UI strings are curated in ar/en and intentionally fall
        // back to the default (Arabic) in other locales.
        disable += "MissingTranslation"
        // The project logs through android.util.Log; Timber is not a declared
        // dependency, the check only fires because some transitive dependency
        // pulls it onto the classpath.
        disable += "LogNotTimber"
    }
}

kotlin {
    compilerOptions {
        // KT-73255: apply injected parameter annotations to the backing field
        // as well as the constructor parameter for Hilt-managed properties.
        freeCompilerArgs.add("-Xannotation-default-target=param-property")
    }
}

dependencies {
    // Project modules
    implementation(project(":core:core-ui"))
    implementation(project(":core:core-common"))
    implementation(project(":core:core-datastore"))
    implementation(project(":core:core-notifications"))
    implementation(project(":core:core-permissions"))
    implementation(project(":core:core-location"))
    implementation(project(":feature:feature-prayer-times"))
    implementation(project(":feature:feature-qibla"))
    implementation(project(":feature:feature-quran"))
    implementation(project(":feature:feature-hadith"))
    implementation(project(":feature:feature-adhkar"))
    implementation(project(":feature:feature-tasbih"))
    implementation(project(":feature:feature-ramadan"))
    implementation(project(":feature:feature-zakat"))
    implementation(project(":feature:feature-finance"))
    implementation(project(":feature:feature-learn"))
    implementation(project(":feature:feature-settings"))
    implementation(project(":feature:feature-reference"))

    // AndroidX core
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.window)
    implementation(libs.google.play.services.wearable)

    // Compose (versions from BOM)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.material3.adaptive)

    // DI
    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation.compose)
    ksp(libs.hilt.compiler)

    // Debug tooling
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    // Unit tests
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockk)
    testImplementation(libs.turbine)
    testImplementation(libs.truth)

    // Instrumented tests
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
}
