package org.muslim.app.feature.zakat.domain

/**
 * A country with its local currency, used to price gold/silver nisab in the
 * user's own money (PROJECT_PROMPT.md §6 Phase 7: زكاة عالمية).
 *
 * @param code ISO 3166-1 alpha-2 country code
 * @param currency ISO 4217 currency code (what the FX provider keys on)
 * @param symbol the currency symbol shown next to amounts
 * @param nameArabic Arabic country name
 * @param nameEnglish English country name
 */
data class CountryCurrency(
    val code: String,
    val currency: String,
    val symbol: String,
    val nameArabic: String,
    val nameEnglish: String,
)

/**
 * Global catalog of every country in the world with its local currency —
 * all 193 UN members plus the observer states (Palestine, Vatican) and the
 * widely-recognised Taiwan and Kosovo. The ISO 4217 currency codes match the
 * FX provider's keys (open.er-api.com, which serves daily ECB/Open Exchange
 * Rates data), so gold/silver prices can be fetched live for any country.
 */
object CountryCurrencies {

    val ALL: List<CountryCurrency> = listOf(
        // ===== الشرق الأوسط والخليج =====
        CountryCurrency("SA", "SAR", "ر.س", "السعودية", "Saudi Arabia"),
        CountryCurrency("AE", "AED", "د.إ", "الإمارات", "United Arab Emirates"),
        CountryCurrency("KW", "KWD", "د.ك", "الكويت", "Kuwait"),
        CountryCurrency("QA", "QAR", "ر.ق", "قطر", "Qatar"),
        CountryCurrency("BH", "BHD", "د.ب", "البحرين", "Bahrain"),
        CountryCurrency("OM", "OMR", "ر.ع", "عُمان", "Oman"),
        CountryCurrency("YE", "YER", "ر.ي", "اليمن", "Yemen"),
        CountryCurrency("IQ", "IQD", "د.ع", "العراق", "Iraq"),
        CountryCurrency("JO", "JOD", "د.أ", "الأردن", "Jordan"),
        CountryCurrency("PS", "ILS", "₪", "فلسطين", "Palestine"),
        CountryCurrency("IL", "ILS", "₪", "إسرائيل", "Israel"),
        CountryCurrency("LB", "LBP", "ل.ل", "لبنان", "Lebanon"),
        CountryCurrency("SY", "SYP", "ل.س", "سوريا", "Syria"),
        CountryCurrency("TR", "TRY", "₺", "تركيا", "Türkiye"),
        CountryCurrency("IR", "IRR", "﷼", "إيران", "Iran"),
        // ===== شمال أفريقيا =====
        CountryCurrency("EG", "EGP", "ج.م", "مصر", "Egypt"),
        CountryCurrency("LY", "LYD", "د.ل", "ليبيا", "Libya"),
        CountryCurrency("TN", "TND", "د.ت", "تونس", "Tunisia"),
        CountryCurrency("DZ", "DZD", "د.ج", "الجزائر", "Algeria"),
        CountryCurrency("MA", "MAD", "د.م", "المغرب", "Morocco"),
        CountryCurrency("SD", "SDG", "ج.س", "السودان", "Sudan"),
        CountryCurrency("SS", "SSP", "ج.ج", "جنوب السودان", "South Sudan"),
        CountryCurrency("ER", "ERN", "نكفا", "إريتريا", "Eritrea"),
        CountryCurrency("DJ", "DJF", "ف.ج", "جيبوتي", "Djibouti"),
        CountryCurrency("SO", "SOS", "ش.ص", "الصومال", "Somalia"),
        CountryCurrency("MR", "MRU", "أ.م", "موريتانيا", "Mauritania"),
        // ===== أفريقيا جنوب الصحراء =====
        CountryCurrency("NG", "NGN", "₦", "نيجيريا", "Nigeria"),
        CountryCurrency("KE", "KES", "KSh", "كينيا", "Kenya"),
        CountryCurrency("ZA", "ZAR", "ر.ج", "جنوب أفريقيا", "South Africa"),
        CountryCurrency("GH", "GHS", "₵", "غانا", "Ghana"),
        CountryCurrency("TZ", "TZS", "ش.ت", "تنزانيا", "Tanzania"),
        CountryCurrency("UG", "UGX", "ش.أ", "أوغندا", "Uganda"),
        CountryCurrency("ET", "ETB", "ب.إ", "إثيوبيا", "Ethiopia"),
        CountryCurrency("ZM", "ZMW", "ك.ز", "زامبيا", "Zambia"),
        CountryCurrency("ZW", "ZWL", "د.ز", "زيمبابوي", "Zimbabwe"),
        CountryCurrency("MZ", "MZN", "م.م", "موزمبيق", "Mozambique"),
        CountryCurrency("AO", "AOA", "ك.أ", "أنغولا", "Angola"),
        CountryCurrency("CM", "XAF", "CFA", "الكاميرون", "Cameroon"),
        CountryCurrency("CI", "XOF", "CFA", "ساحل العاج", "Côte d'Ivoire"),
        CountryCurrency("SN", "XOF", "CFA", "السنغال", "Senegal"),
        CountryCurrency("ML", "XOF", "CFA", "مالي", "Mali"),
        CountryCurrency("BF", "XOF", "CFA", "بوركينا فاسو", "Burkina Faso"),
        CountryCurrency("NE", "XOF", "CFA", "النيجر", "Niger"),
        CountryCurrency("BJ", "XOF", "CFA", "بنين", "Benin"),
        CountryCurrency("TG", "XOF", "CFA", "توغو", "Togo"),
        CountryCurrency("GW", "XOF", "CFA", "غينيا بيساو", "Guinea-Bissau"),
        CountryCurrency("TD", "XAF", "CFA", "تشاد", "Chad"),
        CountryCurrency("CF", "XAF", "CFA", "جمهورية أفريقيا الوسطى", "Central African Republic"),
        CountryCurrency("CG", "XAF", "CFA", "جمهورية الكونغو", "Congo"),
        CountryCurrency("GA", "XAF", "CFA", "الغابون", "Gabon"),
        CountryCurrency("GQ", "XAF", "CFA", "غينيا الاستوائية", "Equatorial Guinea"),
        CountryCurrency("CD", "CDF", "ف.ك", "الكونغو الديمقراطية", "DR Congo"),
        CountryCurrency("GN", "GNF", "ف.غ", "غينيا", "Guinea"),
        CountryCurrency("SL", "SLE", "ل.س", "سيراليون", "Sierra Leone"),
        CountryCurrency("LR", "LRD", "د.ل", "ليبيريا", "Liberia"),
        CountryCurrency("GM", "GMD", "د.ج", "غامبيا", "Gambia"),
        CountryCurrency("RW", "RWF", "ف.ر", "رواندا", "Rwanda"),
        CountryCurrency("BI", "BIF", "ف.ب", "بوروندي", "Burundi"),
        CountryCurrency("MW", "MWK", "ك.م", "ملاوي", "Malawi"),
        CountryCurrency("NA", "NAD", "د.ن", "ناميبيا", "Namibia"),
        CountryCurrency("BW", "BWP", "ب.ب", "بوتسوانا", "Botswana"),
        CountryCurrency("LS", "LSL", "ل.ل", "ليسوتو", "Lesotho"),
        CountryCurrency("SZ", "SZL", "ل.إ", "إسواتيني", "Eswatini"),
        CountryCurrency("MG", "MGA", "أ.م", "مدغشقر", "Madagascar"),
        CountryCurrency("MU", "MUR", "ر.م", "موريشيوس", "Mauritius"),
        CountryCurrency("SC", "SCR", "ر.س", "سيشل", "Seychelles"),
        CountryCurrency("KM", "KMF", "ف.ق", "جزر القمر", "Comoros"),
        CountryCurrency("CV", "CVE", "إس.", "الرأس الأخضر", "Cape Verde"),
        CountryCurrency("ST", "STN", "د.س.ت", "ساو تومي وبرينسيبي", "São Tomé and Príncipe"),
        // ===== جنوب آسيا =====
        CountryCurrency("PK", "PKR", "ر.ب", "باكستان", "Pakistan"),
        CountryCurrency("IN", "INR", "₹", "الهند", "India"),
        CountryCurrency("BD", "BDT", "৳", "بنغلاديش", "Bangladesh"),
        CountryCurrency("AF", "AFN", "؋", "أفغانستان", "Afghanistan"),
        CountryCurrency("NP", "NPR", "रू", "نيبال", "Nepal"),
        CountryCurrency("BT", "BTN", "ن.ب", "بوتان", "Bhutan"),
        CountryCurrency("LK", "LKR", "ر.س", "سريلانكا", "Sri Lanka"),
        CountryCurrency("MV", "MVR", "ر.م", "المالديف", "Maldives"),
        // ===== آسيا الوسطى =====
        CountryCurrency("KZ", "KZT", "₸", "كازاخستان", "Kazakhstan"),
        CountryCurrency("UZ", "UZS", "س.أ", "أوزبكستان", "Uzbekistan"),
        CountryCurrency("TM", "TMT", "م.ت", "تركمانستان", "Turkmenistan"),
        CountryCurrency("KG", "KGS", "س.ق", "قيرغيزستان", "Kyrgyzstan"),
        CountryCurrency("TJ", "TJS", "س.ط", "طاجيكستان", "Tajikistan"),
        // ===== شرق آسيا =====
        CountryCurrency("CN", "CNY", "¥", "الصين", "China"),
        CountryCurrency("JP", "JPY", "¥", "اليابان", "Japan"),
        CountryCurrency("KR", "KRW", "₩", "كوريا الجنوبية", "South Korea"),
        CountryCurrency("KP", "KPW", "₩", "كوريا الشمالية", "North Korea"),
        CountryCurrency("MN", "MNT", "₮", "منغوليا", "Mongolia"),
        CountryCurrency("TW", "TWD", "NT$", "تايوان", "Taiwan"),
        CountryCurrency("HK", "HKD", "د.ه", "هونغ كونغ", "Hong Kong"),
        CountryCurrency("MO", "MOP", "ب.م", "ماكاو", "Macau"),
        // ===== جنوب شرق آسيا =====
        CountryCurrency("ID", "IDR", "ر.إ", "إندونيسيا", "Indonesia"),
        CountryCurrency("MY", "MYR", "ر.م", "ماليزيا", "Malaysia"),
        CountryCurrency("SG", "SGD", "S$", "سنغافورة", "Singapore"),
        CountryCurrency("TH", "THB", "฿", "تايلاند", "Thailand"),
        CountryCurrency("VN", "VND", "₫", "فيتنام", "Vietnam"),
        CountryCurrency("PH", "PHP", "₱", "الفلبين", "Philippines"),
        CountryCurrency("MM", "MMK", "ك.م", "ميانمار", "Myanmar"),
        CountryCurrency("LA", "LAK", "₭", "لاوس", "Laos"),
        CountryCurrency("KH", "KHR", "៛", "كمبوديا", "Cambodia"),
        CountryCurrency("BN", "BND", "د.ب", "بروناي", "Brunei"),
        CountryCurrency("TL", "USD", "$", "تيمور الشرقية", "Timor-Leste"),
        // ===== أوقيانوسيا =====
        CountryCurrency("AU", "AUD", "A$", "أستراليا", "Australia"),
        CountryCurrency("NZ", "NZD", "د.ن", "نيوزيلندا", "New Zealand"),
        CountryCurrency("PG", "PGK", "ك.ب", "بابوا غينيا الجديدة", "Papua New Guinea"),
        CountryCurrency("FJ", "FJD", "د.ف", "فيجي", "Fiji"),
        CountryCurrency("SB", "SBD", "د.س", "جزر سليمان", "Solomon Islands"),
        CountryCurrency("VU", "VUV", "ف.ف", "فانواتو", "Vanuatu"),
        CountryCurrency("WS", "WST", "ت.س", "ساموا", "Samoa"),
        CountryCurrency("TO", "TOP", "ت.ب", "تونغا", "Tonga"),
        CountryCurrency("TV", "AUD", "A$", "توفالو", "Tuvalu"),
        CountryCurrency("KI", "AUD", "A$", "كيريباتي", "Kiribati"),
        CountryCurrency("NR", "AUD", "A$", "ناورو", "Nauru"),
        CountryCurrency("FM", "USD", "$", "ميكرونيزيا", "Micronesia"),
        CountryCurrency("MH", "USD", "$", "جزر مارشال", "Marshall Islands"),
        CountryCurrency("PW", "USD", "$", "بالاو", "Palau"),
        // ===== أوروبا =====
        CountryCurrency("GB", "GBP", "£", "بريطانيا", "United Kingdom"),
        CountryCurrency("IE", "EUR", "€", "أيرلندا", "Ireland"),
        CountryCurrency("DE", "EUR", "€", "ألمانيا", "Germany"),
        CountryCurrency("FR", "EUR", "€", "فرنسا", "France"),
        CountryCurrency("ES", "EUR", "€", "إسبانيا", "Spain"),
        CountryCurrency("PT", "EUR", "€", "البرتغال", "Portugal"),
        CountryCurrency("IT", "EUR", "€", "إيطاليا", "Italy"),
        CountryCurrency("NL", "EUR", "€", "هولندا", "Netherlands"),
        CountryCurrency("BE", "EUR", "€", "بلجيكا", "Belgium"),
        CountryCurrency("LU", "EUR", "€", "لوكسمبورغ", "Luxembourg"),
        CountryCurrency("AT", "EUR", "€", "النمسا", "Austria"),
        CountryCurrency("FI", "EUR", "€", "فنلندا", "Finland"),
        CountryCurrency("GR", "EUR", "€", "اليونان", "Greece"),
        CountryCurrency("CY", "EUR", "€", "قبرص", "Cyprus"),
        CountryCurrency("MT", "EUR", "€", "مالطا", "Malta"),
        CountryCurrency("SK", "EUR", "€", "سلوفاكيا", "Slovakia"),
        CountryCurrency("SI", "EUR", "€", "سلوفينيا", "Slovenia"),
        CountryCurrency("LV", "EUR", "€", "لاتفيا", "Latvia"),
        CountryCurrency("LT", "EUR", "€", "ليتوانيا", "Lithuania"),
        CountryCurrency("EE", "EUR", "€", "إستونيا", "Estonia"),
        CountryCurrency("HR", "EUR", "€", "كرواتيا", "Croatia"),
        CountryCurrency("SE", "SEK", "kr", "السويد", "Sweden"),
        CountryCurrency("NO", "NOK", "kr", "النرويج", "Norway"),
        CountryCurrency("DK", "DKK", "د.ك", "الدنمارك", "Denmark"),
        CountryCurrency("IS", "ISK", "ك.إ", "آيسلندا", "Iceland"),
        CountryCurrency("CH", "CHF", "₣", "سويسرا", "Switzerland"),
        CountryCurrency("LI", "CHF", "₣", "ليختنشتاين", "Liechtenstein"),
        CountryCurrency("RU", "RUB", "₽", "روسيا", "Russia"),
        CountryCurrency("UA", "UAH", "₴", "أوكرانيا", "Ukraine"),
        CountryCurrency("BY", "BYN", "ب.ب", "بيلاروسيا", "Belarus"),
        CountryCurrency("PL", "PLN", "ز.ب", "بولندا", "Poland"),
        CountryCurrency("CZ", "CZK", "ك.ج", "التشيك", "Czechia"),
        CountryCurrency("HU", "HUF", "ف.هـ", "المجر", "Hungary"),
        CountryCurrency("RO", "RON", "ل.ر", "رومانيا", "Romania"),
        CountryCurrency("BG", "BGN", "ل.ب", "بلغاريا", "Bulgaria"),
        CountryCurrency("RS", "RSD", "د.ر", "صربيا", "Serbia"),
        CountryCurrency("BA", "BAM", "ك.ب", "البوسنة والهرسك", "Bosnia and Herzegovina"),
        CountryCurrency("ME", "EUR", "€", "الجبل الأسود", "Montenegro"),
        CountryCurrency("MK", "MKD", "د.م", "مقدونيا الشمالية", "North Macedonia"),
        CountryCurrency("AL", "ALL", "ل.أ", "ألبانيا", "Albania"),
        CountryCurrency("XK", "EUR", "€", "كوسوفو", "Kosovo"),
        CountryCurrency("MD", "MDL", "ل.م", "مولدوفا", "Moldova"),
        CountryCurrency("GE", "GEL", "ل.ج", "جورجيا", "Georgia"),
        CountryCurrency("AM", "AMD", "د.أ", "أرمينيا", "Armenia"),
        CountryCurrency("AZ", "AZN", "م.أ", "أذربيجان", "Azerbaijan"),
        CountryCurrency("AD", "EUR", "€", "أندورا", "Andorra"),
        CountryCurrency("MC", "EUR", "€", "موناكو", "Monaco"),
        CountryCurrency("SM", "EUR", "€", "سان مارينو", "San Marino"),
        CountryCurrency("VA", "EUR", "€", "الفاتيكان", "Vatican City"),
        // ===== أمريكا الشمالية والوسطى والكاريبي =====
        CountryCurrency("US", "USD", "$", "الولايات المتحدة", "United States"),
        CountryCurrency("CA", "CAD", "C$", "كندا", "Canada"),
        CountryCurrency("MX", "MXN", "Mex$", "المكسيك", "Mexico"),
        CountryCurrency("GT", "GTQ", "ق", "غواتيمالا", "Guatemala"),
        CountryCurrency("BZ", "BZD", "د.ب", "بليز", "Belize"),
        CountryCurrency("SV", "USD", "$", "السلفادور", "El Salvador"),
        CountryCurrency("HN", "HNL", "ل.ه", "هندوراس", "Honduras"),
        CountryCurrency("NI", "NIO", "ك.ن", "نيكاراغوا", "Nicaragua"),
        CountryCurrency("CR", "CRC", "₡", "كوستاريكا", "Costa Rica"),
        CountryCurrency("PA", "USD", "$", "بنما", "Panama"),
        CountryCurrency("CU", "CUP", "ك.ك", "كوبا", "Cuba"),
        CountryCurrency("JM", "JMD", "د.ج", "جامايكا", "Jamaica"),
        CountryCurrency("HT", "HTG", "ج.ه", "هايتي", "Haiti"),
        CountryCurrency("DO", "DOP", "د.د", "جمهورية الدومينيكان", "Dominican Republic"),
        CountryCurrency("TT", "TTD", "د.ت", "ترينيداد وتوباغو", "Trinidad and Tobago"),
        CountryCurrency("BS", "BSD", "د.ب", "جزر البهاما", "Bahamas"),
        CountryCurrency("BB", "BBD", "د.ب", "باربادوس", "Barbados"),
        CountryCurrency("DM", "XCD", "د.ك.ش", "دومينيكا", "Dominica"),
        CountryCurrency("GD", "XCD", "د.ك.ش", "غرينادا", "Grenada"),
        CountryCurrency("KN", "XCD", "د.ك.ش", "سانت كيتس ونيفيس", "Saint Kitts and Nevis"),
        CountryCurrency("LC", "XCD", "د.ك.ش", "سانت لوسيا", "Saint Lucia"),
        CountryCurrency("VC", "XCD", "د.ك.ش", "سانت فنسنت وجزر غرينادين", "Saint Vincent and the Grenadines"),
        CountryCurrency("AG", "XCD", "د.ك.ش", "أنتيغوا وباربودا", "Antigua and Barbuda"),
        // ===== أمريكا الجنوبية =====
        CountryCurrency("BR", "BRL", "R$", "البرازيل", "Brazil"),
        CountryCurrency("AR", "ARS", "أ.ج", "الأرجنتين", "Argentina"),
        CountryCurrency("CL", "CLP", "ك.ش", "تشيلي", "Chile"),
        CountryCurrency("CO", "COP", "ك.ك", "كولومبيا", "Colombia"),
        CountryCurrency("PE", "PEN", "س.ب", "بيرو", "Peru"),
        CountryCurrency("VE", "VES", "ب.ف", "فنزويلا", "Venezuela"),
        CountryCurrency("EC", "USD", "$", "الإكوادور", "Ecuador"),
        CountryCurrency("BO", "BOB", "ب.ب", "بوليفيا", "Bolivia"),
        CountryCurrency("PY", "PYG", "₲", "باراغواي", "Paraguay"),
        CountryCurrency("UY", "UYU", "أ.ي", "أوروغواي", "Uruguay"),
        CountryCurrency("GY", "GYD", "د.غ", "غيانا", "Guyana"),
        CountryCurrency("SR", "SRD", "د.س", "سورينام", "Suriname"),
    )

    /** Looks up a catalog entry by country code; null for an unknown code. */
    fun byCountry(code: String): CountryCurrency? = ALL.firstOrNull { it.code == code }

    /** Looks up a catalog entry by currency code (first match). */
    fun byCurrency(currency: String): CountryCurrency? = ALL.firstOrNull { it.currency == currency }
}
