#!/usr/bin/env bash
# Creates the release signing keystore and keystore.properties (the 4 signing
# values: storeFile, storePassword, keyAlias, keyPassword) automatically.
#
# This is the local half of the stable-signing setup. The SAME keystore must
# sign every release (local AND CI) so users can install updates on top of an
# existing install without uninstalling first.
#
# Usage:
#   ./scripts/create-signing-keystore.sh            # create only if missing
#   ./scripts/create-signing-keystore.sh --force    # regenerate, keep a backup
#
# After running this, share the key with CI once:
#   ./scripts/setup-github-signing.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STORE_FILE="release.keystore"
STORE_PATH="$ROOT/$STORE_FILE"
PROPS="$ROOT/keystore.properties"
ALIAS="muslim"
DNAME="CN=Muslim, OU=Android, O=Muslim, L=Worldwide, C=US"
VALIDITY_DAYS=10000

# --- locate keytool ---------------------------------------------------------
KEYTOOL=""
if command -v keytool >/dev/null 2>&1; then
    KEYTOOL="keytool"
elif [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/keytool" ]; then
    KEYTOOL="$JAVA_HOME/bin/keytool"
else
    echo "keytool not found. Install a JDK or set JAVA_HOME." >&2
    exit 1
fi

# --- refuse to clobber unless --force ---------------------------------------
if [ -f "$PROPS" ] || [ -f "$STORE_PATH" ]; then
    if [ "${1:-}" != "--force" ]; then
        echo "Signing key already exists ($PROPS / $STORE_PATH)." >&2
        echo "Re-run with --force only if you understand that existing installs" >&2
        echo "will no longer be able to update over this key." >&2
        exit 0
    fi
    BACKUP="$STORE_PATH.bak.$(date +%Y%m%d%H%M%S)"
    [ -f "$STORE_PATH" ] && mv "$STORE_PATH" "$BACKUP" && echo "Backed up old keystore to $BACKUP"
    [ -f "$PROPS" ] && mv "$PROPS" "$PROPS.bak.$(date +%Y%m%d%H%M%S)" && echo "Backed up old keystore.properties"
fi

# --- random alphanumeric password (32 chars, no shell/properties escaping) ---
gen_pass() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 32
    else
        head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32
    fi
}
STORE_PASS="$(gen_pass)"
KEY_PASS="$STORE_PASS"

# --- generate the keystore (PKCS12, RSA 4096) --------------------------------
# Passwords go through env vars so they never appear on the process list.
export MUSLIM_STORE_PASS="$STORE_PASS"
export MUSLIM_KEY_PASS="$KEY_PASS"
"$KEYTOOL" -genkeypair \
    -keystore "$STORE_PATH" \
    -storetype PKCS12 \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 4096 \
    -validity "$VALIDITY_DAYS" \
    -dname "$DNAME" \
    -storepass:env MUSLIM_STORE_PASS \
    -keypass:env MUSLIM_KEY_PASS

# --- write keystore.properties (git-ignored) ---------------------------------
cat > "$PROPS" <<EOF
# Release signing configuration — generated by scripts/create-signing-keystore.sh
# Never commit this file. Share the key with CI via scripts/setup-github-signing.sh
storeFile=$STORE_FILE
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$KEY_PASS
EOF

# --- verify ------------------------------------------------------------------
echo "Keystore created: $STORE_PATH"
echo "Properties written: $PROPS (never commit)"
"$KEYTOOL" -list -keystore "$STORE_PATH" -storepass:env MUSLIM_STORE_PASS \
    | grep -E "Keystore type|Alias name|Valid from" || true

echo
echo "Next: upload the same key to CI so release APKs share this signature:"
echo "  ./scripts/setup-github-signing.sh"
